name: Publish PowerShell Script

on:
  workflow_dispatch:

jobs:
  Publish-Script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish to PowerShell Gallery
        shell: pwsh
        run: |
          $env:PSGalleryApiKey = "${{ secrets.NUGET_KEY }}"
          Publish-Script -Path ./IntuneBrew.ps1 -Repository PSGallery -NuGetApiKey $env:PSGalleryApiKey
