#!/bin/bash
# Uninstall script for Sketch
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Sketch..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Sketch if running..."
pkill -f "Sketch" 2>/dev/null || true

# Remove /Applications/Sketch.app
echo "Removing /Applications/Sketch.app..."
if [ -d "/Applications/Sketch.app" ]; then
    rm -rf "/Applications/Sketch.app" 2>/dev/null || true
elif [ -f "/Applications/Sketch.app" ]; then
    rm -f "/Applications/Sketch.app" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
