#!/bin/bash
# Uninstall script for AltTab
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling AltTab..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping AltTab if running..."
pkill -f "AltTab" 2>/dev/null || true

# Remove /Applications/AltTab.app
echo "Removing /Applications/AltTab.app..."
if [ -d "/Applications/AltTab.app" ]; then
    rm -rf "/Applications/AltTab.app" 2>/dev/null || true
elif [ -f "/Applications/AltTab.app" ]; then
    rm -f "/Applications/AltTab.app" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
