#!/bin/bash
# Uninstall script for OpenMTP
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling OpenMTP..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping OpenMTP if running..."
pkill -f "OpenMTP" 2>/dev/null || true

# Remove /Applications/OpenMTP.app
echo "Removing /Applications/OpenMTP.app..."
if [ -d "/Applications/OpenMTP.app" ]; then
    rm -rf "/Applications/OpenMTP.app" 2>/dev/null || true
elif [ -f "/Applications/OpenMTP.app" ]; then
    rm -f "/Applications/OpenMTP.app" 2>/dev/null || true
fi

# Remove $HOME/.io.ganeshrvel
echo "Removing $HOME/.io.ganeshrvel..."
if [ -d "$HOME/.io.ganeshrvel" ]; then
    rm -rf "$HOME/.io.ganeshrvel" 2>/dev/null || true
elif [ -f "$HOME/.io.ganeshrvel" ]; then
    rm -f "$HOME/.io.ganeshrvel" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/io.ganeshrvel.openmtp
echo "Removing $HOME/Library/Application Support/io.ganeshrvel.openmtp..."
if [ -d "$HOME/Library/Application Support/io.ganeshrvel.openmtp" ]; then
    rm -rf "$HOME/Library/Application Support/io.ganeshrvel.openmtp" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/io.ganeshrvel.openmtp" ]; then
    rm -f "$HOME/Library/Application Support/io.ganeshrvel.openmtp" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/OpenMTP
echo "Removing $HOME/Library/Application Support/OpenMTP..."
if [ -d "$HOME/Library/Application Support/OpenMTP" ]; then
    rm -rf "$HOME/Library/Application Support/OpenMTP" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/OpenMTP" ]; then
    rm -f "$HOME/Library/Application Support/OpenMTP" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/io.ganeshrvel.openmtp.plist
echo "Removing $HOME/Library/Preferences/io.ganeshrvel.openmtp.plist..."
if [ -d "$HOME/Library/Preferences/io.ganeshrvel.openmtp.plist" ]; then
    rm -rf "$HOME/Library/Preferences/io.ganeshrvel.openmtp.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/io.ganeshrvel.openmtp.plist" ]; then
    rm -f "$HOME/Library/Preferences/io.ganeshrvel.openmtp.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
