#!/bin/bash
# Uninstall script for iMazing
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling iMazing..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping iMazing if running..."
pkill -f "iMazing" 2>/dev/null || true

# Kill application with bundle ID com.DigiDNA.iMazing3.2.1.21398Mac if running
echo "Stopping application with bundle ID com.DigiDNA.iMazing3.2.1.21398Mac if running..."
killall -9 "com.DigiDNA.iMazing3.2.1.21398Mac" 2>/dev/null || true

# Kill application with bundle ID com.DigiDNA.iMazing3.2.1.21398Mac.Mini if running
echo "Stopping application with bundle ID com.DigiDNA.iMazing3.2.1.21398Mac.Mini if running..."
killall -9 "com.DigiDNA.iMazing3.2.1.21398Mac.Mini" 2>/dev/null || true

# Remove /Applications/iMazing.app
echo "Removing /Applications/iMazing.app..."
if [ -d "/Applications/iMazing.app" ]; then
    rm -rf "/Applications/iMazing.app" 2>/dev/null || true
elif [ -f "/Applications/iMazing.app" ]; then
    rm -f "/Applications/iMazing.app" 2>/dev/null || true
fi

# Remove /Users/Shared/iMazing Mini
echo "Removing /Users/Shared/iMazing Mini..."
if [ -d "/Users/Shared/iMazing Mini" ]; then
    rm -rf "/Users/Shared/iMazing Mini" 2>/dev/null || true
elif [ -f "/Users/Shared/iMazing Mini" ]; then
    rm -f "/Users/Shared/iMazing Mini" 2>/dev/null || true
fi

# Remove /Users/Shared/iMazing
echo "Removing /Users/Shared/iMazing..."
if [ -d "/Users/Shared/iMazing" ]; then
    rm -rf "/Users/Shared/iMazing" 2>/dev/null || true
elif [ -f "/Users/Shared/iMazing" ]; then
    rm -f "/Users/Shared/iMazing" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/iMazing Mini
echo "Removing $HOME/Library/Application Support/iMazing Mini..."
if [ -d "$HOME/Library/Application Support/iMazing Mini" ]; then
    rm -rf "$HOME/Library/Application Support/iMazing Mini" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/iMazing Mini" ]; then
    rm -f "$HOME/Library/Application Support/iMazing Mini" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/iMazing
echo "Removing $HOME/Library/Application Support/iMazing..."
if [ -d "$HOME/Library/Application Support/iMazing" ]; then
    rm -rf "$HOME/Library/Application Support/iMazing" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/iMazing" ]; then
    rm -f "$HOME/Library/Application Support/iMazing" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/MobileSync/Backup/iMazing.Versions
echo "Removing $HOME/Library/Application Support/MobileSync/Backup/iMazing.Versions..."
if [ -d "$HOME/Library/Application Support/MobileSync/Backup/iMazing.Versions" ]; then
    rm -rf "$HOME/Library/Application Support/MobileSync/Backup/iMazing.Versions" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/MobileSync/Backup/iMazing.Versions" ]; then
    rm -f "$HOME/Library/Application Support/MobileSync/Backup/iMazing.Versions" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.DigiDNA.iMazing3Mac
echo "Removing $HOME/Library/Caches/com.DigiDNA.iMazing3Mac..."
if [ -d "$HOME/Library/Caches/com.DigiDNA.iMazing3Mac" ]; then
    rm -rf "$HOME/Library/Caches/com.DigiDNA.iMazing3Mac" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.DigiDNA.iMazing3Mac" ]; then
    rm -f "$HOME/Library/Caches/com.DigiDNA.iMazing3Mac" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.DigiDNA.iMazing3Mac.Mini
echo "Removing $HOME/Library/Caches/com.DigiDNA.iMazing3Mac.Mini..."
if [ -d "$HOME/Library/Caches/com.DigiDNA.iMazing3Mac.Mini" ]; then
    rm -rf "$HOME/Library/Caches/com.DigiDNA.iMazing3Mac.Mini" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.DigiDNA.iMazing3Mac.Mini" ]; then
    rm -f "$HOME/Library/Caches/com.DigiDNA.iMazing3Mac.Mini" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.plausiblelabs.crashreporter.data/com.DigiDNA.iMazing3Mac.Mini
echo "Removing $HOME/Library/Caches/com.plausiblelabs.crashreporter.data/com.DigiDNA.iMazing3Mac.Mini..."
if [ -d "$HOME/Library/Caches/com.plausiblelabs.crashreporter.data/com.DigiDNA.iMazing3Mac.Mini" ]; then
    rm -rf "$HOME/Library/Caches/com.plausiblelabs.crashreporter.data/com.DigiDNA.iMazing3Mac.Mini" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.plausiblelabs.crashreporter.data/com.DigiDNA.iMazing3Mac.Mini" ]; then
    rm -f "$HOME/Library/Caches/com.plausiblelabs.crashreporter.data/com.DigiDNA.iMazing3Mac.Mini" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/iMazing
echo "Removing $HOME/Library/Caches/iMazing..."
if [ -d "$HOME/Library/Caches/iMazing" ]; then
    rm -rf "$HOME/Library/Caches/iMazing" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/iMazing" ]; then
    rm -f "$HOME/Library/Caches/iMazing" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.DigiDNA.iMazing3Mac.Mini.plist
echo "Removing $HOME/Library/Preferences/com.DigiDNA.iMazing3Mac.Mini.plist..."
if [ -d "$HOME/Library/Preferences/com.DigiDNA.iMazing3Mac.Mini.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.DigiDNA.iMazing3Mac.Mini.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.DigiDNA.iMazing3Mac.Mini.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.DigiDNA.iMazing3Mac.Mini.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.DigiDNA.iMazing3Mac.plist
echo "Removing $HOME/Library/Preferences/com.DigiDNA.iMazing3Mac.plist..."
if [ -d "$HOME/Library/Preferences/com.DigiDNA.iMazing3Mac.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.DigiDNA.iMazing3Mac.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.DigiDNA.iMazing3Mac.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.DigiDNA.iMazing3Mac.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
