#!/bin/bash
# Uninstall script for Snagit
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Snagit..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Snagit if running..."
pkill -f "Snagit" 2>/dev/null || true

# Remove /Applications/Snagit.app
echo "Removing /Applications/Snagit.app..."
if [ -d "/Applications/Snagit.app" ]; then
    rm -rf "/Applications/Snagit.app" 2>/dev/null || true
elif [ -f "/Applications/Snagit.app" ]; then
    rm -f "/Applications/Snagit.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.TechSmith.Snagit*
echo "Removing $HOME/Library/Caches/com.TechSmith.Snagit*..."
if [ -d "$HOME/Library/Caches/com.TechSmith.Snagit*" ]; then
    rm -rf "$HOME/Library/Caches/com.TechSmith.Snagit*" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.TechSmith.Snagit*" ]; then
    rm -f "$HOME/Library/Caches/com.TechSmith.Snagit*" 2>/dev/null || true
fi

# Remove $HOME/Library/Group Containers/*.com.techsmith.snagit
echo "Removing $HOME/Library/Group Containers/*.com.techsmith.snagit..."
if [ -d "$HOME/Library/Group Containers/*.com.techsmith.snagit" ]; then
    rm -rf "$HOME/Library/Group Containers/*.com.techsmith.snagit" 2>/dev/null || true
elif [ -f "$HOME/Library/Group Containers/*.com.techsmith.snagit" ]; then
    rm -f "$HOME/Library/Group Containers/*.com.techsmith.snagit" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.TechSmith.Snagit*.plist
echo "Removing $HOME/Library/Preferences/com.TechSmith.Snagit*.plist..."
if [ -d "$HOME/Library/Preferences/com.TechSmith.Snagit*.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.TechSmith.Snagit*.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.TechSmith.Snagit*.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.TechSmith.Snagit*.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.techsmith.snagit.capturehelper*.plist
echo "Removing $HOME/Library/Preferences/com.techsmith.snagit.capturehelper*.plist..."
if [ -d "$HOME/Library/Preferences/com.techsmith.snagit.capturehelper*.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.techsmith.snagit.capturehelper*.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.techsmith.snagit.capturehelper*.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.techsmith.snagit.capturehelper*.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.TechSmith.Snagit*.savedState
echo "Removing $HOME/Library/Saved Application State/com.TechSmith.Snagit*.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.TechSmith.Snagit*.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.TechSmith.Snagit*.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.TechSmith.Snagit*.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.TechSmith.Snagit*.savedState" 2>/dev/null || true
fi

# Remove $HOME/Library/WebKit/com.TechSmith.Snagit*
echo "Removing $HOME/Library/WebKit/com.TechSmith.Snagit*..."
if [ -d "$HOME/Library/WebKit/com.TechSmith.Snagit*" ]; then
    rm -rf "$HOME/Library/WebKit/com.TechSmith.Snagit*" 2>/dev/null || true
elif [ -f "$HOME/Library/WebKit/com.TechSmith.Snagit*" ]; then
    rm -f "$HOME/Library/WebKit/com.TechSmith.Snagit*" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
