#!/bin/bash
# Uninstall script for XCA
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling XCA..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping XCA if running..."
pkill -f "XCA" 2>/dev/null || true

# Remove /Applications/xca.app
echo "Removing /Applications/xca.app..."
if [ -d "/Applications/xca.app" ]; then
    rm -rf "/Applications/xca.app" 2>/dev/null || true
elif [ -f "/Applications/xca.app" ]; then
    rm -f "/Applications/xca.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/xca
echo "Removing $HOME/Library/Application Support/xca..."
if [ -d "$HOME/Library/Application Support/xca" ]; then
    rm -rf "$HOME/Library/Application Support/xca" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/xca" ]; then
    rm -f "$HOME/Library/Application Support/xca" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/de.hohnstaedt.xca.savedState
echo "Removing $HOME/Library/Saved Application State/de.hohnstaedt.xca.savedState..."
if [ -d "$HOME/Library/Saved Application State/de.hohnstaedt.xca.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/de.hohnstaedt.xca.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/de.hohnstaedt.xca.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/de.hohnstaedt.xca.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
