#!/bin/bash
# Uninstall script for Arduino IDE
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Arduino IDE..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Arduino IDE if running..."
pkill -f "Arduino IDE" 2>/dev/null || true

# Remove /Applications/Arduino IDE.app
echo "Removing /Applications/Arduino IDE.app..."
if [ -d "/Applications/Arduino IDE.app" ]; then
    rm -rf "/Applications/Arduino IDE.app" 2>/dev/null || true
elif [ -f "/Applications/Arduino IDE.app" ]; then
    rm -f "/Applications/Arduino IDE.app" 2>/dev/null || true
fi

# Remove $HOME/.arduinoIDE
echo "Removing $HOME/.arduinoIDE..."
if [ -d "$HOME/.arduinoIDE" ]; then
    rm -rf "$HOME/.arduinoIDE" 2>/dev/null || true
elif [ -f "$HOME/.arduinoIDE" ]; then
    rm -f "$HOME/.arduinoIDE" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/arduino-ide
echo "Removing $HOME/Library/Application Support/arduino-ide..."
if [ -d "$HOME/Library/Application Support/arduino-ide" ]; then
    rm -rf "$HOME/Library/Application Support/arduino-ide" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/arduino-ide" ]; then
    rm -f "$HOME/Library/Application Support/arduino-ide" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/cc.arduino.ide*.sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/cc.arduino.ide*.sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/cc.arduino.ide*.sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/cc.arduino.ide*.sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/cc.arduino.ide*.sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/cc.arduino.ide*.sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/cc.arduino.IDE*.plist
echo "Removing $HOME/Library/Preferences/cc.arduino.IDE*.plist..."
if [ -d "$HOME/Library/Preferences/cc.arduino.IDE*.plist" ]; then
    rm -rf "$HOME/Library/Preferences/cc.arduino.IDE*.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/cc.arduino.IDE*.plist" ]; then
    rm -f "$HOME/Library/Preferences/cc.arduino.IDE*.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/cc.arduino.IDE2.savedState
echo "Removing $HOME/Library/Saved Application State/cc.arduino.IDE2.savedState..."
if [ -d "$HOME/Library/Saved Application State/cc.arduino.IDE2.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/cc.arduino.IDE2.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/cc.arduino.IDE2.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/cc.arduino.IDE2.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
