#!/bin/bash
# Uninstall script for NoMachine
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling NoMachine..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping NoMachine if running..."
pkill -f "NoMachine" 2>/dev/null || true

# Unload service com.nomachine.localnxserver
echo "Unloading service com.nomachine.localnxserver..."
launchctl unload -w /Library/LaunchAgents/com.nomachine.localnxserver.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.nomachine.localnxserver.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.nomachine.localnxserver.plist 2>/dev/null || true

# Unload service com.nomachine.nxlaunchconf
echo "Unloading service com.nomachine.nxlaunchconf..."
launchctl unload -w /Library/LaunchAgents/com.nomachine.nxlaunchconf.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.nomachine.nxlaunchconf.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.nomachine.nxlaunchconf.plist 2>/dev/null || true

# Unload service com.nomachine.nxnode
echo "Unloading service com.nomachine.nxnode..."
launchctl unload -w /Library/LaunchAgents/com.nomachine.nxnode.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.nomachine.nxnode.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.nomachine.nxnode.plist 2>/dev/null || true

# Unload service com.nomachine.nxplayer
echo "Unloading service com.nomachine.nxplayer..."
launchctl unload -w /Library/LaunchAgents/com.nomachine.nxplayer.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.nomachine.nxplayer.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.nomachine.nxplayer.plist 2>/dev/null || true

# Unload service com.nomachine.nxrunner
echo "Unloading service com.nomachine.nxrunner..."
launchctl unload -w /Library/LaunchAgents/com.nomachine.nxrunner.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.nomachine.nxrunner.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.nomachine.nxrunner.plist 2>/dev/null || true

# Unload service com.nomachine.nxserver
echo "Unloading service com.nomachine.nxserver..."
launchctl unload -w /Library/LaunchAgents/com.nomachine.nxserver.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.nomachine.nxserver.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.nomachine.nxserver.plist 2>/dev/null || true

# Unload service com.nomachine.server
echo "Unloading service com.nomachine.server..."
launchctl unload -w /Library/LaunchAgents/com.nomachine.server.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.nomachine.server.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.nomachine.server.plist 2>/dev/null || true

# Unload service com.nomachine.uninstall
echo "Unloading service com.nomachine.uninstall..."
launchctl unload -w /Library/LaunchAgents/com.nomachine.uninstall.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.nomachine.uninstall.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.nomachine.uninstall.plist 2>/dev/null || true

# Unload service com.nomachine.uninstallAgent
echo "Unloading service com.nomachine.uninstallAgent..."
launchctl unload -w /Library/LaunchAgents/com.nomachine.uninstallAgent.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.nomachine.uninstallAgent.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.nomachine.uninstallAgent.plist 2>/dev/null || true

# Remove /Library/Application Support/NoMachine
echo "Removing /Library/Application Support/NoMachine..."
if [ -d "/Library/Application Support/NoMachine" ]; then
    rm -rf "/Library/Application Support/NoMachine" 2>/dev/null || true
elif [ -f "/Library/Application Support/NoMachine" ]; then
    rm -f "/Library/Application Support/NoMachine" 2>/dev/null || true
fi

# Remove $HOME/Documents/NoMachine
echo "Removing $HOME/Documents/NoMachine..."
if [ -d "$HOME/Documents/NoMachine" ]; then
    rm -rf "$HOME/Documents/NoMachine" 2>/dev/null || true
elif [ -f "$HOME/Documents/NoMachine" ]; then
    rm -f "$HOME/Documents/NoMachine" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.nomachine.nxdock.plist
echo "Removing $HOME/Library/Preferences/com.nomachine.nxdock.plist..."
if [ -d "$HOME/Library/Preferences/com.nomachine.nxdock.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.nomachine.nxdock.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.nomachine.nxdock.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.nomachine.nxdock.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
