#!/bin/bash
# Uninstall script for Arc
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Arc..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Arc if running..."
pkill -f "Arc" 2>/dev/null || true

# Remove /Applications/Arc.app
echo "Removing /Applications/Arc.app..."
if [ -d "/Applications/Arc.app" ]; then
    rm -rf "/Applications/Arc.app" 2>/dev/null || true
elif [ -f "/Applications/Arc.app" ]; then
    rm -f "/Applications/Arc.app" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
