#!/bin/bash
# Uninstall script for NeoFinder
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling NeoFinder..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping NeoFinder if running..."
pkill -f "NeoFinder" 2>/dev/null || true

# Remove /Applications/NeoFinder.app
echo "Removing /Applications/NeoFinder.app..."
if [ -d "/Applications/NeoFinder.app" ]; then
    rm -rf "/Applications/NeoFinder.app" 2>/dev/null || true
elif [ -f "/Applications/NeoFinder.app" ]; then
    rm -f "/Applications/NeoFinder.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/CrashReporter/NeoFinder_*
echo "Removing $HOME/Library/Application Support/CrashReporter/NeoFinder_*..."
if [ -d "$HOME/Library/Application Support/CrashReporter/NeoFinder_*" ]; then
    rm -rf "$HOME/Library/Application Support/CrashReporter/NeoFinder_*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/CrashReporter/NeoFinder_*" ]; then
    rm -f "$HOME/Library/Application Support/CrashReporter/NeoFinder_*" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/NeoFinder
echo "Removing $HOME/Library/Application Support/NeoFinder..."
if [ -d "$HOME/Library/Application Support/NeoFinder" ]; then
    rm -rf "$HOME/Library/Application Support/NeoFinder" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/NeoFinder" ]; then
    rm -f "$HOME/Library/Application Support/NeoFinder" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/de.wfs-apps.neofinder
echo "Removing $HOME/Library/Caches/de.wfs-apps.neofinder..."
if [ -d "$HOME/Library/Caches/de.wfs-apps.neofinder" ]; then
    rm -rf "$HOME/Library/Caches/de.wfs-apps.neofinder" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/de.wfs-apps.neofinder" ]; then
    rm -f "$HOME/Library/Caches/de.wfs-apps.neofinder" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/de.wfs-apps.neofinder.quicklaunch.cache
echo "Removing $HOME/Library/Caches/de.wfs-apps.neofinder.quicklaunch.cache..."
if [ -d "$HOME/Library/Caches/de.wfs-apps.neofinder.quicklaunch.cache" ]; then
    rm -rf "$HOME/Library/Caches/de.wfs-apps.neofinder.quicklaunch.cache" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/de.wfs-apps.neofinder.quicklaunch.cache" ]; then
    rm -f "$HOME/Library/Caches/de.wfs-apps.neofinder.quicklaunch.cache" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/de.wfs-apps.neofinder.plist
echo "Removing $HOME/Library/Preferences/de.wfs-apps.neofinder.plist..."
if [ -d "$HOME/Library/Preferences/de.wfs-apps.neofinder.plist" ]; then
    rm -rf "$HOME/Library/Preferences/de.wfs-apps.neofinder.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/de.wfs-apps.neofinder.plist" ]; then
    rm -f "$HOME/Library/Preferences/de.wfs-apps.neofinder.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/de.wfs-apps.neofinder.statusBar.plist
echo "Removing $HOME/Library/Preferences/de.wfs-apps.neofinder.statusBar.plist..."
if [ -d "$HOME/Library/Preferences/de.wfs-apps.neofinder.statusBar.plist" ]; then
    rm -rf "$HOME/Library/Preferences/de.wfs-apps.neofinder.statusBar.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/de.wfs-apps.neofinder.statusBar.plist" ]; then
    rm -f "$HOME/Library/Preferences/de.wfs-apps.neofinder.statusBar.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
