#!/bin/bash
# Uninstall script for Joplin
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Joplin..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Joplin if running..."
pkill -f "Joplin" 2>/dev/null || true

# Remove /Applications/Joplin.app
echo "Removing /Applications/Joplin.app..."
if [ -d "/Applications/Joplin.app" ]; then
    rm -rf "/Applications/Joplin.app" 2>/dev/null || true
elif [ -f "/Applications/Joplin.app" ]; then
    rm -f "/Applications/Joplin.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Joplin
echo "Removing $HOME/Library/Application Support/Joplin..."
if [ -d "$HOME/Library/Application Support/Joplin" ]; then
    rm -rf "$HOME/Library/Application Support/Joplin" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Joplin" ]; then
    rm -f "$HOME/Library/Application Support/Joplin" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/net.cozic.joplin-desktop.helper.plist
echo "Removing $HOME/Library/Preferences/net.cozic.joplin-desktop.helper.plist..."
if [ -d "$HOME/Library/Preferences/net.cozic.joplin-desktop.helper.plist" ]; then
    rm -rf "$HOME/Library/Preferences/net.cozic.joplin-desktop.helper.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/net.cozic.joplin-desktop.helper.plist" ]; then
    rm -f "$HOME/Library/Preferences/net.cozic.joplin-desktop.helper.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/net.cozic.joplin-desktop.plist
echo "Removing $HOME/Library/Preferences/net.cozic.joplin-desktop.plist..."
if [ -d "$HOME/Library/Preferences/net.cozic.joplin-desktop.plist" ]; then
    rm -rf "$HOME/Library/Preferences/net.cozic.joplin-desktop.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/net.cozic.joplin-desktop.plist" ]; then
    rm -f "$HOME/Library/Preferences/net.cozic.joplin-desktop.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/net.cozic.joplin-desktop.savedState
echo "Removing $HOME/Library/Saved Application State/net.cozic.joplin-desktop.savedState..."
if [ -d "$HOME/Library/Saved Application State/net.cozic.joplin-desktop.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/net.cozic.joplin-desktop.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/net.cozic.joplin-desktop.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/net.cozic.joplin-desktop.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
