#!/bin/bash
# Uninstall script for LocalSend
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling LocalSend..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping LocalSend if running..."
pkill -f "LocalSend" 2>/dev/null || true

# Remove /Applications/LocalSend.app
echo "Removing /Applications/LocalSend.app..."
if [ -d "/Applications/LocalSend.app" ]; then
    rm -rf "/Applications/LocalSend.app" 2>/dev/null || true
elif [ -f "/Applications/LocalSend.app" ]; then
    rm -f "/Applications/LocalSend.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/org.localsend.localsendApp
echo "Removing $HOME/Library/Application Scripts/org.localsend.localsendApp..."
if [ -d "$HOME/Library/Application Scripts/org.localsend.localsendApp" ]; then
    rm -rf "$HOME/Library/Application Scripts/org.localsend.localsendApp" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/org.localsend.localsendApp" ]; then
    rm -f "$HOME/Library/Application Scripts/org.localsend.localsendApp" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/org.localsend.localsendApp
echo "Removing $HOME/Library/Containers/org.localsend.localsendApp..."
if [ -d "$HOME/Library/Containers/org.localsend.localsendApp" ]; then
    rm -rf "$HOME/Library/Containers/org.localsend.localsendApp" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/org.localsend.localsendApp" ]; then
    rm -f "$HOME/Library/Containers/org.localsend.localsendApp" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/org.localsend.localsendApp.plist
echo "Removing $HOME/Library/Preferences/org.localsend.localsendApp.plist..."
if [ -d "$HOME/Library/Preferences/org.localsend.localsendApp.plist" ]; then
    rm -rf "$HOME/Library/Preferences/org.localsend.localsendApp.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/org.localsend.localsendApp.plist" ]; then
    rm -f "$HOME/Library/Preferences/org.localsend.localsendApp.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/org.localsend.localsendApp.savedState
echo "Removing $HOME/Library/Saved Application State/org.localsend.localsendApp.savedState..."
if [ -d "$HOME/Library/Saved Application State/org.localsend.localsendApp.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/org.localsend.localsendApp.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/org.localsend.localsendApp.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/org.localsend.localsendApp.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
