#!/bin/bash
# Uninstall script for Krita
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Krita..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Krita if running..."
pkill -f "Krita" 2>/dev/null || true

# Remove /Applications/krita.app
echo "Removing /Applications/krita.app..."
if [ -d "/Applications/krita.app" ]; then
    rm -rf "/Applications/krita.app" 2>/dev/null || true
elif [ -f "/Applications/krita.app" ]; then
    rm -f "/Applications/krita.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/krita
echo "Removing $HOME/Library/Application Support/krita..."
if [ -d "$HOME/Library/Application Support/krita" ]; then
    rm -rf "$HOME/Library/Application Support/krita" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/krita" ]; then
    rm -f "$HOME/Library/Application Support/krita" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/kritadisplayrc
echo "Removing $HOME/Library/Preferences/kritadisplayrc..."
if [ -d "$HOME/Library/Preferences/kritadisplayrc" ]; then
    rm -rf "$HOME/Library/Preferences/kritadisplayrc" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/kritadisplayrc" ]; then
    rm -f "$HOME/Library/Preferences/kritadisplayrc" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/kritarc
echo "Removing $HOME/Library/Preferences/kritarc..."
if [ -d "$HOME/Library/Preferences/kritarc" ]; then
    rm -rf "$HOME/Library/Preferences/kritarc" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/kritarc" ]; then
    rm -f "$HOME/Library/Preferences/kritarc" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/org.krita.savedState
echo "Removing $HOME/Library/Saved Application State/org.krita.savedState..."
if [ -d "$HOME/Library/Saved Application State/org.krita.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/org.krita.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/org.krita.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/org.krita.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
