#!/bin/bash
# Uninstall script for Steam
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Steam..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Steam if running..."
pkill -f "Steam" 2>/dev/null || true

# Unload service com.valvesoftware.steam.ipctool
echo "Unloading service com.valvesoftware.steam.ipctool..."
launchctl unload -w /Library/LaunchAgents/com.valvesoftware.steam.ipctool.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.valvesoftware.steam.ipctool.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.valvesoftware.steam.ipctool.plist 2>/dev/null || true

# Unload service com.valvesoftware.steamclean
echo "Unloading service com.valvesoftware.steamclean..."
launchctl unload -w /Library/LaunchAgents/com.valvesoftware.steamclean.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.valvesoftware.steamclean.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.valvesoftware.steamclean.plist 2>/dev/null || true

# Kill application with bundle ID com.valvesoftware.steam if running
echo "Stopping application with bundle ID com.valvesoftware.steam if running..."
killall -9 "com.valvesoftware.steam" 2>/dev/null || true

# Kill application with bundle ID com.valvesoftware.steam.helper if running
echo "Stopping application with bundle ID com.valvesoftware.steam.helper if running..."
killall -9 "com.valvesoftware.steam.helper" 2>/dev/null || true

# Kill application with bundle ID com.valvesoftware.steam.helper.EH if running
echo "Stopping application with bundle ID com.valvesoftware.steam.helper.EH if running..."
killall -9 "com.valvesoftware.steam.helper.EH" 2>/dev/null || true

# Remove /Applications/Steam.app
echo "Removing /Applications/Steam.app..."
if [ -d "/Applications/Steam.app" ]; then
    rm -rf "/Applications/Steam.app" 2>/dev/null || true
elif [ -f "/Applications/Steam.app" ]; then
    rm -f "/Applications/Steam.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Steam/
echo "Removing $HOME/Library/Application Support/Steam/..."
if [ -d "$HOME/Library/Application Support/Steam/" ]; then
    rm -rf "$HOME/Library/Application Support/Steam/" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Steam/" ]; then
    rm -f "$HOME/Library/Application Support/Steam/" 2>/dev/null || true
fi

# Remove $HOME/Library/LaunchAgents/com.valvesoftware.steamclean.plist
echo "Removing $HOME/Library/LaunchAgents/com.valvesoftware.steamclean.plist..."
if [ -d "$HOME/Library/LaunchAgents/com.valvesoftware.steamclean.plist" ]; then
    rm -rf "$HOME/Library/LaunchAgents/com.valvesoftware.steamclean.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/LaunchAgents/com.valvesoftware.steamclean.plist" ]; then
    rm -f "$HOME/Library/LaunchAgents/com.valvesoftware.steamclean.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.valvesoftware.steam.helper.plist
echo "Removing $HOME/Library/Preferences/com.valvesoftware.steam.helper.plist..."
if [ -d "$HOME/Library/Preferences/com.valvesoftware.steam.helper.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.valvesoftware.steam.helper.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.valvesoftware.steam.helper.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.valvesoftware.steam.helper.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.valvesoftware.steam.savedState/
echo "Removing $HOME/Library/Saved Application State/com.valvesoftware.steam.savedState/..."
if [ -d "$HOME/Library/Saved Application State/com.valvesoftware.steam.savedState/" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.valvesoftware.steam.savedState/" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.valvesoftware.steam.savedState/" ]; then
    rm -f "$HOME/Library/Saved Application State/com.valvesoftware.steam.savedState/" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
