#!/bin/bash
# Uninstall script for BatFi
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling BatFi..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping BatFi if running..."
pkill -f "BatFi" 2>/dev/null || true

# Kill application with bundle ID software.micropixels.BatFi if running
echo "Stopping application with bundle ID software.micropixels.BatFi if running..."
killall -9 "software.micropixels.BatFi" 2>/dev/null || true

# Remove /Applications/BatFi.app
echo "Removing /Applications/BatFi.app..."
if [ -d "/Applications/BatFi.app" ]; then
    rm -rf "/Applications/BatFi.app" 2>/dev/null || true
elif [ -f "/Applications/BatFi.app" ]; then
    rm -f "/Applications/BatFi.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/BatFi
echo "Removing $HOME/Library/Application Support/BatFi..."
if [ -d "$HOME/Library/Application Support/BatFi" ]; then
    rm -rf "$HOME/Library/Application Support/BatFi" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/BatFi" ]; then
    rm -f "$HOME/Library/Application Support/BatFi" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/software.micropixels.BatFi.plist
echo "Removing $HOME/Library/Preferences/software.micropixels.BatFi.plist..."
if [ -d "$HOME/Library/Preferences/software.micropixels.BatFi.plist" ]; then
    rm -rf "$HOME/Library/Preferences/software.micropixels.BatFi.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/software.micropixels.BatFi.plist" ]; then
    rm -f "$HOME/Library/Preferences/software.micropixels.BatFi.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
