#!/bin/bash
# Uninstall script for Zoom
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Zoom..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Zoom if running..."
pkill -f "Zoom" 2>/dev/null || true

# Unload service us.zoom.updater
echo "Unloading service us.zoom.updater..."
launchctl unload -w /Library/LaunchAgents/us.zoom.updater.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/us.zoom.updater.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/us.zoom.updater.plist 2>/dev/null || true

# Unload service us.zoom.updater.login.check
echo "Unloading service us.zoom.updater.login.check..."
launchctl unload -w /Library/LaunchAgents/us.zoom.updater.login.check.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/us.zoom.updater.login.check.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/us.zoom.updater.login.check.plist 2>/dev/null || true

# Unload service us.zoom.ZoomDaemon
echo "Unloading service us.zoom.ZoomDaemon..."
launchctl unload -w /Library/LaunchAgents/us.zoom.ZoomDaemon.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/us.zoom.ZoomDaemon.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/us.zoom.ZoomDaemon.plist 2>/dev/null || true

# Remove $HOME/.zoomus
echo "Removing $HOME/.zoomus..."
if [ -d "$HOME/.zoomus" ]; then
    rm -rf "$HOME/.zoomus" 2>/dev/null || true
elif [ -f "$HOME/.zoomus" ]; then
    rm -f "$HOME/.zoomus" 2>/dev/null || true
fi

# Remove $HOME/Desktop/Zoom
echo "Removing $HOME/Desktop/Zoom..."
if [ -d "$HOME/Desktop/Zoom" ]; then
    rm -rf "$HOME/Desktop/Zoom" 2>/dev/null || true
elif [ -f "$HOME/Desktop/Zoom" ]; then
    rm -f "$HOME/Desktop/Zoom" 2>/dev/null || true
fi

# Remove $HOME/Documents/Zoom
echo "Removing $HOME/Documents/Zoom..."
if [ -d "$HOME/Documents/Zoom" ]; then
    rm -rf "$HOME/Documents/Zoom" 2>/dev/null || true
elif [ -f "$HOME/Documents/Zoom" ]; then
    rm -f "$HOME/Documents/Zoom" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/*.ZoomClient3rd
echo "Removing $HOME/Library/Application Scripts/*.ZoomClient3rd..."
if [ -d "$HOME/Library/Application Scripts/*.ZoomClient3rd" ]; then
    rm -rf "$HOME/Library/Application Scripts/*.ZoomClient3rd" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/*.ZoomClient3rd" ]; then
    rm -f "$HOME/Library/Application Scripts/*.ZoomClient3rd" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/CloudDocs/session/containers/iCloud.us.zoom.videomeetings
echo "Removing $HOME/Library/Application Support/CloudDocs/session/containers/iCloud.us.zoom.videomeetings..."
if [ -d "$HOME/Library/Application Support/CloudDocs/session/containers/iCloud.us.zoom.videomeetings" ]; then
    rm -rf "$HOME/Library/Application Support/CloudDocs/session/containers/iCloud.us.zoom.videomeetings" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/CloudDocs/session/containers/iCloud.us.zoom.videomeetings" ]; then
    rm -f "$HOME/Library/Application Support/CloudDocs/session/containers/iCloud.us.zoom.videomeetings" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/CloudDocs/session/containers/iCloud.us.zoom.videomeetings.plist
echo "Removing $HOME/Library/Application Support/CloudDocs/session/containers/iCloud.us.zoom.videomeetings.plist..."
if [ -d "$HOME/Library/Application Support/CloudDocs/session/containers/iCloud.us.zoom.videomeetings.plist" ]; then
    rm -rf "$HOME/Library/Application Support/CloudDocs/session/containers/iCloud.us.zoom.videomeetings.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/CloudDocs/session/containers/iCloud.us.zoom.videomeetings.plist" ]; then
    rm -f "$HOME/Library/Application Support/CloudDocs/session/containers/iCloud.us.zoom.videomeetings.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/us.zoom*.sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/us.zoom*.sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/us.zoom*.sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/us.zoom*.sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/us.zoom*.sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/us.zoom*.sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/CrashReporter/zoom.us*
echo "Removing $HOME/Library/Application Support/CrashReporter/zoom.us*..."
if [ -d "$HOME/Library/Application Support/CrashReporter/zoom.us*" ]; then
    rm -rf "$HOME/Library/Application Support/CrashReporter/zoom.us*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/CrashReporter/zoom.us*" ]; then
    rm -f "$HOME/Library/Application Support/CrashReporter/zoom.us*" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/zoom.us
echo "Removing $HOME/Library/Application Support/zoom.us..."
if [ -d "$HOME/Library/Application Support/zoom.us" ]; then
    rm -rf "$HOME/Library/Application Support/zoom.us" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/zoom.us" ]; then
    rm -f "$HOME/Library/Application Support/zoom.us" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/ZoomUpdater
echo "Removing $HOME/Library/Application Support/ZoomUpdater..."
if [ -d "$HOME/Library/Application Support/ZoomUpdater" ]; then
    rm -rf "$HOME/Library/Application Support/ZoomUpdater" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/ZoomUpdater" ]; then
    rm -f "$HOME/Library/Application Support/ZoomUpdater" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/us.zoom.xos
echo "Removing $HOME/Library/Caches/us.zoom.xos..."
if [ -d "$HOME/Library/Caches/us.zoom.xos" ]; then
    rm -rf "$HOME/Library/Caches/us.zoom.xos" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/us.zoom.xos" ]; then
    rm -f "$HOME/Library/Caches/us.zoom.xos" 2>/dev/null || true
fi

# Remove $HOME/Library/Cookies/us.zoom.xos.binarycookies
echo "Removing $HOME/Library/Cookies/us.zoom.xos.binarycookies..."
if [ -d "$HOME/Library/Cookies/us.zoom.xos.binarycookies" ]; then
    rm -rf "$HOME/Library/Cookies/us.zoom.xos.binarycookies" 2>/dev/null || true
elif [ -f "$HOME/Library/Cookies/us.zoom.xos.binarycookies" ]; then
    rm -f "$HOME/Library/Cookies/us.zoom.xos.binarycookies" 2>/dev/null || true
fi

# Remove $HOME/Library/Group Containers/*.ZoomClient3rd
echo "Removing $HOME/Library/Group Containers/*.ZoomClient3rd..."
if [ -d "$HOME/Library/Group Containers/*.ZoomClient3rd" ]; then
    rm -rf "$HOME/Library/Group Containers/*.ZoomClient3rd" 2>/dev/null || true
elif [ -f "$HOME/Library/Group Containers/*.ZoomClient3rd" ]; then
    rm -f "$HOME/Library/Group Containers/*.ZoomClient3rd" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/us.zoom.xos
echo "Removing $HOME/Library/HTTPStorages/us.zoom.xos..."
if [ -d "$HOME/Library/HTTPStorages/us.zoom.xos" ]; then
    rm -rf "$HOME/Library/HTTPStorages/us.zoom.xos" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/us.zoom.xos" ]; then
    rm -f "$HOME/Library/HTTPStorages/us.zoom.xos" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/us.zoom.xos.binarycookies
echo "Removing $HOME/Library/HTTPStorages/us.zoom.xos.binarycookies..."
if [ -d "$HOME/Library/HTTPStorages/us.zoom.xos.binarycookies" ]; then
    rm -rf "$HOME/Library/HTTPStorages/us.zoom.xos.binarycookies" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/us.zoom.xos.binarycookies" ]; then
    rm -f "$HOME/Library/HTTPStorages/us.zoom.xos.binarycookies" 2>/dev/null || true
fi

# Remove $HOME/Library/Internet Plug-Ins/ZoomUsPlugIn.plugin
echo "Removing $HOME/Library/Internet Plug-Ins/ZoomUsPlugIn.plugin..."
if [ -d "$HOME/Library/Internet Plug-Ins/ZoomUsPlugIn.plugin" ]; then
    rm -rf "$HOME/Library/Internet Plug-Ins/ZoomUsPlugIn.plugin" 2>/dev/null || true
elif [ -f "$HOME/Library/Internet Plug-Ins/ZoomUsPlugIn.plugin" ]; then
    rm -f "$HOME/Library/Internet Plug-Ins/ZoomUsPlugIn.plugin" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/zoom.us
echo "Removing $HOME/Library/Logs/zoom.us..."
if [ -d "$HOME/Library/Logs/zoom.us" ]; then
    rm -rf "$HOME/Library/Logs/zoom.us" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/zoom.us" ]; then
    rm -f "$HOME/Library/Logs/zoom.us" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/zoominstall.log
echo "Removing $HOME/Library/Logs/zoominstall.log..."
if [ -d "$HOME/Library/Logs/zoominstall.log" ]; then
    rm -rf "$HOME/Library/Logs/zoominstall.log" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/zoominstall.log" ]; then
    rm -f "$HOME/Library/Logs/zoominstall.log" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/ZoomPhone
echo "Removing $HOME/Library/Logs/ZoomPhone..."
if [ -d "$HOME/Library/Logs/ZoomPhone" ]; then
    rm -rf "$HOME/Library/Logs/ZoomPhone" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/ZoomPhone" ]; then
    rm -f "$HOME/Library/Logs/ZoomPhone" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/us.zoom.*.plist
echo "Removing $HOME/Library/Preferences/us.zoom.*.plist..."
if [ -d "$HOME/Library/Preferences/us.zoom.*.plist" ]; then
    rm -rf "$HOME/Library/Preferences/us.zoom.*.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/us.zoom.*.plist" ]; then
    rm -f "$HOME/Library/Preferences/us.zoom.*.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/ZoomChat.plist
echo "Removing $HOME/Library/Preferences/ZoomChat.plist..."
if [ -d "$HOME/Library/Preferences/ZoomChat.plist" ]; then
    rm -rf "$HOME/Library/Preferences/ZoomChat.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/ZoomChat.plist" ]; then
    rm -f "$HOME/Library/Preferences/ZoomChat.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/us.zoom.xos.savedState
echo "Removing $HOME/Library/Saved Application State/us.zoom.xos.savedState..."
if [ -d "$HOME/Library/Saved Application State/us.zoom.xos.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/us.zoom.xos.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/us.zoom.xos.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/us.zoom.xos.savedState" 2>/dev/null || true
fi

# Remove $HOME/Library/WebKit/us.zoom.xos
echo "Removing $HOME/Library/WebKit/us.zoom.xos..."
if [ -d "$HOME/Library/WebKit/us.zoom.xos" ]; then
    rm -rf "$HOME/Library/WebKit/us.zoom.xos" 2>/dev/null || true
elif [ -f "$HOME/Library/WebKit/us.zoom.xos" ]; then
    rm -f "$HOME/Library/WebKit/us.zoom.xos" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
