#!/bin/bash
# Uninstall script for GrandPerspective
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling GrandPerspective..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping GrandPerspective if running..."
pkill -f "GrandPerspective" 2>/dev/null || true

# Remove /Applications/GrandPerspective.app
echo "Removing /Applications/GrandPerspective.app..."
if [ -d "/Applications/GrandPerspective.app" ]; then
    rm -rf "/Applications/GrandPerspective.app" 2>/dev/null || true
elif [ -f "/Applications/GrandPerspective.app" ]; then
    rm -f "/Applications/GrandPerspective.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/net.courceforge.grandperspectiv
echo "Removing $HOME/Library/Application Scripts/net.courceforge.grandperspectiv..."
if [ -d "$HOME/Library/Application Scripts/net.courceforge.grandperspectiv" ]; then
    rm -rf "$HOME/Library/Application Scripts/net.courceforge.grandperspectiv" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/net.courceforge.grandperspectiv" ]; then
    rm -f "$HOME/Library/Application Scripts/net.courceforge.grandperspectiv" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/net.sourceforge.grandperspectiv.sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/net.sourceforge.grandperspectiv.sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/net.sourceforge.grandperspectiv.sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/net.sourceforge.grandperspectiv.sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/net.sourceforge.grandperspectiv.sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/net.sourceforge.grandperspectiv.sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/net.sourceforge.grandperspectiv
echo "Removing $HOME/Library/Containers/net.sourceforge.grandperspectiv..."
if [ -d "$HOME/Library/Containers/net.sourceforge.grandperspectiv" ]; then
    rm -rf "$HOME/Library/Containers/net.sourceforge.grandperspectiv" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/net.sourceforge.grandperspectiv" ]; then
    rm -f "$HOME/Library/Containers/net.sourceforge.grandperspectiv" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/net.sourceforge.grandperspectiv.plist
echo "Removing $HOME/Library/Preferences/net.sourceforge.grandperspectiv.plist..."
if [ -d "$HOME/Library/Preferences/net.sourceforge.grandperspectiv.plist" ]; then
    rm -rf "$HOME/Library/Preferences/net.sourceforge.grandperspectiv.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/net.sourceforge.grandperspectiv.plist" ]; then
    rm -f "$HOME/Library/Preferences/net.sourceforge.grandperspectiv.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
