#!/bin/bash
# Uninstall script for Dataflare
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Dataflare..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Dataflare if running..."
pkill -f "Dataflare" 2>/dev/null || true

# Remove /Applications/Dataflare.app
echo "Removing /Applications/Dataflare.app..."
if [ -d "/Applications/Dataflare.app" ]; then
    rm -rf "/Applications/Dataflare.app" 2>/dev/null || true
elif [ -f "/Applications/Dataflare.app" ]; then
    rm -f "/Applications/Dataflare.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/app.dataflare.desktop
echo "Removing $HOME/Library/Application Support/app.dataflare.desktop..."
if [ -d "$HOME/Library/Application Support/app.dataflare.desktop" ]; then
    rm -rf "$HOME/Library/Application Support/app.dataflare.desktop" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/app.dataflare.desktop" ]; then
    rm -f "$HOME/Library/Application Support/app.dataflare.desktop" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/app.dataflare.desktop
echo "Removing $HOME/Library/Caches/app.dataflare.desktop..."
if [ -d "$HOME/Library/Caches/app.dataflare.desktop" ]; then
    rm -rf "$HOME/Library/Caches/app.dataflare.desktop" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/app.dataflare.desktop" ]; then
    rm -f "$HOME/Library/Caches/app.dataflare.desktop" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/Dataflare
echo "Removing $HOME/Library/Caches/Dataflare..."
if [ -d "$HOME/Library/Caches/Dataflare" ]; then
    rm -rf "$HOME/Library/Caches/Dataflare" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/Dataflare" ]; then
    rm -f "$HOME/Library/Caches/Dataflare" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/Dataflare.binarycookies
echo "Removing $HOME/Library/HTTPStorages/Dataflare.binarycookies..."
if [ -d "$HOME/Library/HTTPStorages/Dataflare.binarycookies" ]; then
    rm -rf "$HOME/Library/HTTPStorages/Dataflare.binarycookies" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/Dataflare.binarycookies" ]; then
    rm -f "$HOME/Library/HTTPStorages/Dataflare.binarycookies" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/app.dataflare.desktop.plist
echo "Removing $HOME/Library/Preferences/app.dataflare.desktop.plist..."
if [ -d "$HOME/Library/Preferences/app.dataflare.desktop.plist" ]; then
    rm -rf "$HOME/Library/Preferences/app.dataflare.desktop.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/app.dataflare.desktop.plist" ]; then
    rm -f "$HOME/Library/Preferences/app.dataflare.desktop.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/Dataflare.plist
echo "Removing $HOME/Library/Preferences/Dataflare.plist..."
if [ -d "$HOME/Library/Preferences/Dataflare.plist" ]; then
    rm -rf "$HOME/Library/Preferences/Dataflare.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/Dataflare.plist" ]; then
    rm -f "$HOME/Library/Preferences/Dataflare.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/WebKit/app.dataflare.desktop
echo "Removing $HOME/Library/WebKit/app.dataflare.desktop..."
if [ -d "$HOME/Library/WebKit/app.dataflare.desktop" ]; then
    rm -rf "$HOME/Library/WebKit/app.dataflare.desktop" 2>/dev/null || true
elif [ -f "$HOME/Library/WebKit/app.dataflare.desktop" ]; then
    rm -f "$HOME/Library/WebKit/app.dataflare.desktop" 2>/dev/null || true
fi

# Remove $HOME/Library/WebKit/Dataflare
echo "Removing $HOME/Library/WebKit/Dataflare..."
if [ -d "$HOME/Library/WebKit/Dataflare" ]; then
    rm -rf "$HOME/Library/WebKit/Dataflare" 2>/dev/null || true
elif [ -f "$HOME/Library/WebKit/Dataflare" ]; then
    rm -f "$HOME/Library/WebKit/Dataflare" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
