#!/bin/bash
# Uninstall script for TeX Live Utility
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling TeX Live Utility..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping TeX Live Utility if running..."
pkill -f "TeX Live Utility" 2>/dev/null || true

# Remove /Applications/TeX Live Utility.app
echo "Removing /Applications/TeX Live Utility.app..."
if [ -d "/Applications/TeX Live Utility.app" ]; then
    rm -rf "/Applications/TeX Live Utility.app" 2>/dev/null || true
elif [ -f "/Applications/TeX Live Utility.app" ]; then
    rm -f "/Applications/TeX Live Utility.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/TeX Live Utility
echo "Removing $HOME/Library/Application Support/TeX Live Utility..."
if [ -d "$HOME/Library/Application Support/TeX Live Utility" ]; then
    rm -rf "$HOME/Library/Application Support/TeX Live Utility" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/TeX Live Utility" ]; then
    rm -f "$HOME/Library/Application Support/TeX Live Utility" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.apple.helpd/SDMHelpData/Other/English/HelpSDMIndexFile/TeX Live Utility Help*
echo "Removing $HOME/Library/Caches/com.apple.helpd/SDMHelpData/Other/English/HelpSDMIndexFile/TeX Live Utility Help*..."
if [ -d "$HOME/Library/Caches/com.apple.helpd/SDMHelpData/Other/English/HelpSDMIndexFile/TeX Live Utility Help*" ]; then
    rm -rf "$HOME/Library/Caches/com.apple.helpd/SDMHelpData/Other/English/HelpSDMIndexFile/TeX Live Utility Help*" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.apple.helpd/SDMHelpData/Other/English/HelpSDMIndexFile/TeX Live Utility Help*" ]; then
    rm -f "$HOME/Library/Caches/com.apple.helpd/SDMHelpData/Other/English/HelpSDMIndexFile/TeX Live Utility Help*" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.googlecode.mactlmgr.tlu
echo "Removing $HOME/Library/Caches/com.googlecode.mactlmgr.tlu..."
if [ -d "$HOME/Library/Caches/com.googlecode.mactlmgr.tlu" ]; then
    rm -rf "$HOME/Library/Caches/com.googlecode.mactlmgr.tlu" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.googlecode.mactlmgr.tlu" ]; then
    rm -f "$HOME/Library/Caches/com.googlecode.mactlmgr.tlu" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.googlecode.mactlmgr.tlu
echo "Removing $HOME/Library/HTTPStorages/com.googlecode.mactlmgr.tlu..."
if [ -d "$HOME/Library/HTTPStorages/com.googlecode.mactlmgr.tlu" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.googlecode.mactlmgr.tlu" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.googlecode.mactlmgr.tlu" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.googlecode.mactlmgr.tlu" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.googlecode.mactlmgr.tlu.binarycookies
echo "Removing $HOME/Library/HTTPStorages/com.googlecode.mactlmgr.tlu.binarycookies..."
if [ -d "$HOME/Library/HTTPStorages/com.googlecode.mactlmgr.tlu.binarycookies" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.googlecode.mactlmgr.tlu.binarycookies" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.googlecode.mactlmgr.tlu.binarycookies" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.googlecode.mactlmgr.tlu.binarycookies" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.googlecode.mactlmgr.tlu.plist
echo "Removing $HOME/Library/Preferences/com.googlecode.mactlmgr.tlu.plist..."
if [ -d "$HOME/Library/Preferences/com.googlecode.mactlmgr.tlu.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.googlecode.mactlmgr.tlu.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.googlecode.mactlmgr.tlu.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.googlecode.mactlmgr.tlu.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.googlecode.mactlmgr.tlu.savedState
echo "Removing $HOME/Library/Saved Application State/com.googlecode.mactlmgr.tlu.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.googlecode.mactlmgr.tlu.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.googlecode.mactlmgr.tlu.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.googlecode.mactlmgr.tlu.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.googlecode.mactlmgr.tlu.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
