#!/bin/bash
# Uninstall script for Amazon Chime
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Amazon Chime..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Amazon Chime if running..."
pkill -f "Amazon Chime" 2>/dev/null || true

# Remove /Applications/Amazon Chime.app
echo "Removing /Applications/Amazon Chime.app..."
if [ -d "/Applications/Amazon Chime.app" ]; then
    rm -rf "/Applications/Amazon Chime.app" 2>/dev/null || true
elif [ -f "/Applications/Amazon Chime.app" ]; then
    rm -f "/Applications/Amazon Chime.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Amazon Chime
echo "Removing $HOME/Library/Application Support/Amazon Chime..."
if [ -d "$HOME/Library/Application Support/Amazon Chime" ]; then
    rm -rf "$HOME/Library/Application Support/Amazon Chime" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Amazon Chime" ]; then
    rm -f "$HOME/Library/Application Support/Amazon Chime" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.amazon.Amazon-Chime
echo "Removing $HOME/Library/Application Support/com.amazon.Amazon-Chime..."
if [ -d "$HOME/Library/Application Support/com.amazon.Amazon-Chime" ]; then
    rm -rf "$HOME/Library/Application Support/com.amazon.Amazon-Chime" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.amazon.Amazon-Chime" ]; then
    rm -f "$HOME/Library/Application Support/com.amazon.Amazon-Chime" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.amazon.Amazon-Chime
echo "Removing $HOME/Library/Caches/com.amazon.Amazon-Chime..."
if [ -d "$HOME/Library/Caches/com.amazon.Amazon-Chime" ]; then
    rm -rf "$HOME/Library/Caches/com.amazon.Amazon-Chime" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.amazon.Amazon-Chime" ]; then
    rm -f "$HOME/Library/Caches/com.amazon.Amazon-Chime" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/Amazon Chime
echo "Removing $HOME/Library/Logs/Amazon Chime..."
if [ -d "$HOME/Library/Logs/Amazon Chime" ]; then
    rm -rf "$HOME/Library/Logs/Amazon Chime" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/Amazon Chime" ]; then
    rm -f "$HOME/Library/Logs/Amazon Chime" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.amazon.Amazon-Chime.plist
echo "Removing $HOME/Library/Preferences/com.amazon.Amazon-Chime.plist..."
if [ -d "$HOME/Library/Preferences/com.amazon.Amazon-Chime.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.amazon.Amazon-Chime.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.amazon.Amazon-Chime.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.amazon.Amazon-Chime.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/WebKit/com.amazon.Amazon-Chime
echo "Removing $HOME/Library/WebKit/com.amazon.Amazon-Chime..."
if [ -d "$HOME/Library/WebKit/com.amazon.Amazon-Chime" ]; then
    rm -rf "$HOME/Library/WebKit/com.amazon.Amazon-Chime" 2>/dev/null || true
elif [ -f "$HOME/Library/WebKit/com.amazon.Amazon-Chime" ]; then
    rm -f "$HOME/Library/WebKit/com.amazon.Amazon-Chime" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
