#!/bin/bash
# Uninstall script for Synology Drive
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Synology Drive..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Synology Drive if running..."
pkill -f "Synology Drive" 2>/dev/null || true

# Unload service application.com.synology.CloudStationUI*
echo "Unloading service application.com.synology.CloudStationUI*..."
launchctl unload -w /Library/LaunchAgents/application.com.synology.CloudStationUI*.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/application.com.synology.CloudStationUI*.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/application.com.synology.CloudStationUI*.plist 2>/dev/null || true

# Unload service com.synology.Synology Cloud Station
echo "Unloading service com.synology.Synology Cloud Station..."
launchctl unload -w /Library/LaunchAgents/com.synology.Synology Cloud Station.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.synology.Synology Cloud Station.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.synology.Synology Cloud Station.plist 2>/dev/null || true

# Kill application with bundle ID com.synology.CloudStation if running
echo "Stopping application with bundle ID com.synology.CloudStation if running..."
killall -9 "com.synology.CloudStation" 2>/dev/null || true

# Kill application with bundle ID com.synology.SynologyDrive.FinderHelper if running
echo "Stopping application with bundle ID com.synology.SynologyDrive.FinderHelper if running..."
killall -9 "com.synology.SynologyDrive.FinderHelper" 2>/dev/null || true

# Kill application with bundle ID io.com.synology.CloudStationUI if running
echo "Stopping application with bundle ID io.com.synology.CloudStationUI if running..."
killall -9 "io.com.synology.CloudStationUI" 2>/dev/null || true

# Remove $HOME/Library/Application Scripts/com.synology.CloudStationUI.FileProvider
echo "Removing $HOME/Library/Application Scripts/com.synology.CloudStationUI.FileProvider..."
if [ -d "$HOME/Library/Application Scripts/com.synology.CloudStationUI.FileProvider" ]; then
    rm -rf "$HOME/Library/Application Scripts/com.synology.CloudStationUI.FileProvider" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/com.synology.CloudStationUI.FileProvider" ]; then
    rm -f "$HOME/Library/Application Scripts/com.synology.CloudStationUI.FileProvider" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/com.synology.SynologyDrive.FinderHelper*
echo "Removing $HOME/Library/Application Scripts/com.synology.SynologyDrive.FinderHelper*..."
if [ -d "$HOME/Library/Application Scripts/com.synology.SynologyDrive.FinderHelper*" ]; then
    rm -rf "$HOME/Library/Application Scripts/com.synology.SynologyDrive.FinderHelper*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/com.synology.SynologyDrive.FinderHelper*" ]; then
    rm -f "$HOME/Library/Application Scripts/com.synology.SynologyDrive.FinderHelper*" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/group.com.synology.CloudStationUI
echo "Removing $HOME/Library/Application Scripts/group.com.synology.CloudStationUI..."
if [ -d "$HOME/Library/Application Scripts/group.com.synology.CloudStationUI" ]; then
    rm -rf "$HOME/Library/Application Scripts/group.com.synology.CloudStationUI" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/group.com.synology.CloudStationUI" ]; then
    rm -f "$HOME/Library/Application Scripts/group.com.synology.CloudStationUI" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.synology.synologydrive.finderhelper.sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.synology.synologydrive.finderhelper.sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.synology.synologydrive.finderhelper.sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.synology.synologydrive.finderhelper.sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.synology.synologydrive.finderhelper.sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.synology.synologydrive.finderhelper.sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/FileProvider/com.synology.CloudStationUI.FileProvider
echo "Removing $HOME/Library/Application Support/FileProvider/com.synology.CloudStationUI.FileProvider..."
if [ -d "$HOME/Library/Application Support/FileProvider/com.synology.CloudStationUI.FileProvider" ]; then
    rm -rf "$HOME/Library/Application Support/FileProvider/com.synology.CloudStationUI.FileProvider" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/FileProvider/com.synology.CloudStationUI.FileProvider" ]; then
    rm -f "$HOME/Library/Application Support/FileProvider/com.synology.CloudStationUI.FileProvider" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/SynologyDrive
echo "Removing $HOME/Library/Application Support/SynologyDrive..."
if [ -d "$HOME/Library/Application Support/SynologyDrive" ]; then
    rm -rf "$HOME/Library/Application Support/SynologyDrive" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/SynologyDrive" ]; then
    rm -f "$HOME/Library/Application Support/SynologyDrive" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.synology.CloudStationUI.FileProvider
echo "Removing $HOME/Library/Containers/com.synology.CloudStationUI.FileProvider..."
if [ -d "$HOME/Library/Containers/com.synology.CloudStationUI.FileProvider" ]; then
    rm -rf "$HOME/Library/Containers/com.synology.CloudStationUI.FileProvider" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.synology.CloudStationUI.FileProvider" ]; then
    rm -f "$HOME/Library/Containers/com.synology.CloudStationUI.FileProvider" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.synology.SynologyDrive*
echo "Removing $HOME/Library/Containers/com.synology.SynologyDrive*..."
if [ -d "$HOME/Library/Containers/com.synology.SynologyDrive*" ]; then
    rm -rf "$HOME/Library/Containers/com.synology.SynologyDrive*" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.synology.SynologyDrive*" ]; then
    rm -f "$HOME/Library/Containers/com.synology.SynologyDrive*" 2>/dev/null || true
fi

# Remove $HOME/Library/Group Containers/group.com.synology.CloudStationUI
echo "Removing $HOME/Library/Group Containers/group.com.synology.CloudStationUI..."
if [ -d "$HOME/Library/Group Containers/group.com.synology.CloudStationUI" ]; then
    rm -rf "$HOME/Library/Group Containers/group.com.synology.CloudStationUI" 2>/dev/null || true
elif [ -f "$HOME/Library/Group Containers/group.com.synology.CloudStationUI" ]; then
    rm -f "$HOME/Library/Group Containers/group.com.synology.CloudStationUI" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.synology.CloudStationUI.plist
echo "Removing $HOME/Library/Preferences/com.synology.CloudStationUI.plist..."
if [ -d "$HOME/Library/Preferences/com.synology.CloudStationUI.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.synology.CloudStationUI.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.synology.CloudStationUI.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.synology.CloudStationUI.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
