#!/bin/bash
# Uninstall script for Camtasia
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Camtasia..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Camtasia if running..."
pkill -f "Camtasia" 2>/dev/null || true

# Remove /Applications/Camtasia.app
echo "Removing /Applications/Camtasia.app..."
if [ -d "/Applications/Camtasia.app" ]; then
    rm -rf "/Applications/Camtasia.app" 2>/dev/null || true
elif [ -f "/Applications/Camtasia.app" ]; then
    rm -f "/Applications/Camtasia.app" 2>/dev/null || true
fi

# Remove /Users/Shared/TechSmith/Camtasia
echo "Removing /Users/Shared/TechSmith/Camtasia..."
if [ -d "/Users/Shared/TechSmith/Camtasia" ]; then
    rm -rf "/Users/Shared/TechSmith/Camtasia" 2>/dev/null || true
elif [ -f "/Users/Shared/TechSmith/Camtasia" ]; then
    rm -f "/Users/Shared/TechSmith/Camtasia" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.techsmith.camtasia25.sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.techsmith.camtasia25.sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.techsmith.camtasia25.sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.techsmith.camtasia25.sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.techsmith.camtasia25.sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.techsmith.camtasia25.sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/TechSmith/Camtasia*
echo "Removing $HOME/Library/Application Support/TechSmith/Camtasia*..."
if [ -d "$HOME/Library/Application Support/TechSmith/Camtasia*" ]; then
    rm -rf "$HOME/Library/Application Support/TechSmith/Camtasia*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/TechSmith/Camtasia*" ]; then
    rm -f "$HOME/Library/Application Support/TechSmith/Camtasia*" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.plausiblelabs.crashreporter.data/com.techsmith.camtasia*
echo "Removing $HOME/Library/Caches/com.plausiblelabs.crashreporter.data/com.techsmith.camtasia*..."
if [ -d "$HOME/Library/Caches/com.plausiblelabs.crashreporter.data/com.techsmith.camtasia*" ]; then
    rm -rf "$HOME/Library/Caches/com.plausiblelabs.crashreporter.data/com.techsmith.camtasia*" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.plausiblelabs.crashreporter.data/com.techsmith.camtasia*" ]; then
    rm -f "$HOME/Library/Caches/com.plausiblelabs.crashreporter.data/com.techsmith.camtasia*" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.techsmith.camtasia*
echo "Removing $HOME/Library/Caches/com.techsmith.camtasia*..."
if [ -d "$HOME/Library/Caches/com.techsmith.camtasia*" ]; then
    rm -rf "$HOME/Library/Caches/com.techsmith.camtasia*" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.techsmith.camtasia*" ]; then
    rm -f "$HOME/Library/Caches/com.techsmith.camtasia*" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.techsmith.camtasia*
echo "Removing $HOME/Library/HTTPStorages/com.techsmith.camtasia*..."
if [ -d "$HOME/Library/HTTPStorages/com.techsmith.camtasia*" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.techsmith.camtasia*" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.techsmith.camtasia*" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.techsmith.camtasia*" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.techsmith.camtasia*.binarycookies
echo "Removing $HOME/Library/HTTPStorages/com.techsmith.camtasia*.binarycookies..."
if [ -d "$HOME/Library/HTTPStorages/com.techsmith.camtasia*.binarycookies" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.techsmith.camtasia*.binarycookies" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.techsmith.camtasia*.binarycookies" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.techsmith.camtasia*.binarycookies" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.techsmith.camtasia*.plist
echo "Removing $HOME/Library/Preferences/com.techsmith.camtasia*.plist..."
if [ -d "$HOME/Library/Preferences/com.techsmith.camtasia*.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.techsmith.camtasia*.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.techsmith.camtasia*.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.techsmith.camtasia*.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.techsmith.camtasia*.savedState
echo "Removing $HOME/Library/Saved Application State/com.techsmith.camtasia*.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.techsmith.camtasia*.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.techsmith.camtasia*.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.techsmith.camtasia*.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.techsmith.camtasia*.savedState" 2>/dev/null || true
fi

# Remove $HOME/Library/WebKit/com.techsmith.camtasia*
echo "Removing $HOME/Library/WebKit/com.techsmith.camtasia*..."
if [ -d "$HOME/Library/WebKit/com.techsmith.camtasia*" ]; then
    rm -rf "$HOME/Library/WebKit/com.techsmith.camtasia*" 2>/dev/null || true
elif [ -f "$HOME/Library/WebKit/com.techsmith.camtasia*" ]; then
    rm -f "$HOME/Library/WebKit/com.techsmith.camtasia*" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
