#!/bin/bash
# Uninstall script for Last Window Quits
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Last Window Quits..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Last Window Quits if running..."
pkill -f "Last Window Quits" 2>/dev/null || true

# Remove /Applications/Last Window Quits.app
echo "Removing /Applications/Last Window Quits.app..."
if [ -d "/Applications/Last Window Quits.app" ]; then
    rm -rf "/Applications/Last Window Quits.app" 2>/dev/null || true
elif [ -f "/Applications/Last Window Quits.app" ]; then
    rm -f "/Applications/Last Window Quits.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/io.lawand.last-window-quits
echo "Removing $HOME/Library/Application Support/io.lawand.last-window-quits..."
if [ -d "$HOME/Library/Application Support/io.lawand.last-window-quits" ]; then
    rm -rf "$HOME/Library/Application Support/io.lawand.last-window-quits" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/io.lawand.last-window-quits" ]; then
    rm -f "$HOME/Library/Application Support/io.lawand.last-window-quits" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/io.lawand.last-window-quits
echo "Removing $HOME/Library/HTTPStorages/io.lawand.last-window-quits..."
if [ -d "$HOME/Library/HTTPStorages/io.lawand.last-window-quits" ]; then
    rm -rf "$HOME/Library/HTTPStorages/io.lawand.last-window-quits" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/io.lawand.last-window-quits" ]; then
    rm -f "$HOME/Library/HTTPStorages/io.lawand.last-window-quits" 2>/dev/null || true
fi

# Remove $HOME/Library/LaunchAgents/io.lawand.last-window-quits.plist
echo "Removing $HOME/Library/LaunchAgents/io.lawand.last-window-quits.plist..."
if [ -d "$HOME/Library/LaunchAgents/io.lawand.last-window-quits.plist" ]; then
    rm -rf "$HOME/Library/LaunchAgents/io.lawand.last-window-quits.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/LaunchAgents/io.lawand.last-window-quits.plist" ]; then
    rm -f "$HOME/Library/LaunchAgents/io.lawand.last-window-quits.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/io.lawand.last-window-quits.plist
echo "Removing $HOME/Library/Preferences/io.lawand.last-window-quits.plist..."
if [ -d "$HOME/Library/Preferences/io.lawand.last-window-quits.plist" ]; then
    rm -rf "$HOME/Library/Preferences/io.lawand.last-window-quits.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/io.lawand.last-window-quits.plist" ]; then
    rm -f "$HOME/Library/Preferences/io.lawand.last-window-quits.plist" 2>/dev/null || true
fi

# Remove $HOME/LWQ Debug Logs
echo "Removing $HOME/LWQ Debug Logs..."
if [ -d "$HOME/LWQ Debug Logs" ]; then
    rm -rf "$HOME/LWQ Debug Logs" 2>/dev/null || true
elif [ -f "$HOME/LWQ Debug Logs" ]; then
    rm -f "$HOME/LWQ Debug Logs" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
