#!/bin/bash
# Uninstall script for Name Mangler
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Name Mangler..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Name Mangler if running..."
pkill -f "Name Mangler" 2>/dev/null || true

# Remove /Applications/Name Mangler.app
echo "Removing /Applications/Name Mangler.app..."
if [ -d "/Applications/Name Mangler.app" ]; then
    rm -rf "/Applications/Name Mangler.app" 2>/dev/null || true
elif [ -f "/Applications/Name Mangler.app" ]; then
    rm -f "/Applications/Name Mangler.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Name Mangler
echo "Removing $HOME/Library/Application Support/Name Mangler..."
if [ -d "$HOME/Library/Application Support/Name Mangler" ]; then
    rm -rf "$HOME/Library/Application Support/Name Mangler" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Name Mangler" ]; then
    rm -f "$HOME/Library/Application Support/Name Mangler" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.manytricks.NameMangler.plist
echo "Removing $HOME/Library/Preferences/com.manytricks.NameMangler.plist..."
if [ -d "$HOME/Library/Preferences/com.manytricks.NameMangler.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.manytricks.NameMangler.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.manytricks.NameMangler.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.manytricks.NameMangler.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
