#!/bin/bash
# Uninstall script for Thonny
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Thonny..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Thonny if running..."
pkill -f "Thonny" 2>/dev/null || true

# Kill application with bundle ID org.thonny.Thonny if running
echo "Stopping application with bundle ID org.thonny.Thonny if running..."
killall -9 "org.thonny.Thonny" 2>/dev/null || true

# Remove $HOME/Library/Saved Application State/org.thonny.Thonny.savedState
echo "Removing $HOME/Library/Saved Application State/org.thonny.Thonny.savedState..."
if [ -d "$HOME/Library/Saved Application State/org.thonny.Thonny.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/org.thonny.Thonny.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/org.thonny.Thonny.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/org.thonny.Thonny.savedState" 2>/dev/null || true
fi

# Remove $HOME/Library/Thonny
echo "Removing $HOME/Library/Thonny..."
if [ -d "$HOME/Library/Thonny" ]; then
    rm -rf "$HOME/Library/Thonny" 2>/dev/null || true
elif [ -f "$HOME/Library/Thonny" ]; then
    rm -f "$HOME/Library/Thonny" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
