#!/bin/bash
# Uninstall script for Aircall
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Aircall..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Aircall if running..."
pkill -f "Aircall" 2>/dev/null || true

# Remove /Applications/Aircall.app
echo "Removing /Applications/Aircall.app..."
if [ -d "/Applications/Aircall.app" ]; then
    rm -rf "/Applications/Aircall.app" 2>/dev/null || true
elif [ -f "/Applications/Aircall.app" ]; then
    rm -f "/Applications/Aircall.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Aircall
echo "Removing $HOME/Library/Application Support/Aircall..."
if [ -d "$HOME/Library/Application Support/Aircall" ]; then
    rm -rf "$HOME/Library/Application Support/Aircall" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Aircall" ]; then
    rm -f "$HOME/Library/Application Support/Aircall" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/io.aircall.phone
echo "Removing $HOME/Library/Caches/io.aircall.phone..."
if [ -d "$HOME/Library/Caches/io.aircall.phone" ]; then
    rm -rf "$HOME/Library/Caches/io.aircall.phone" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/io.aircall.phone" ]; then
    rm -f "$HOME/Library/Caches/io.aircall.phone" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/io.aircall.phone.ShipIt
echo "Removing $HOME/Library/Caches/io.aircall.phone.ShipIt..."
if [ -d "$HOME/Library/Caches/io.aircall.phone.ShipIt" ]; then
    rm -rf "$HOME/Library/Caches/io.aircall.phone.ShipIt" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/io.aircall.phone.ShipIt" ]; then
    rm -f "$HOME/Library/Caches/io.aircall.phone.ShipIt" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/io.aircall.phone.plist
echo "Removing $HOME/Library/Preferences/io.aircall.phone.plist..."
if [ -d "$HOME/Library/Preferences/io.aircall.phone.plist" ]; then
    rm -rf "$HOME/Library/Preferences/io.aircall.phone.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/io.aircall.phone.plist" ]; then
    rm -f "$HOME/Library/Preferences/io.aircall.phone.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
