#!/bin/bash
# Uninstall script for Little Snitch
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Little Snitch..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Little Snitch if running..."
pkill -f "Little Snitch" 2>/dev/null || true

# Remove /Applications/Little Snitch.app
echo "Removing /Applications/Little Snitch.app..."
if [ -d "/Applications/Little Snitch.app" ]; then
    rm -rf "/Applications/Little Snitch.app" 2>/dev/null || true
elif [ -f "/Applications/Little Snitch.app" ]; then
    rm -f "/Applications/Little Snitch.app" 2>/dev/null || true
fi

# Remove /Library/Application Support/Objective Development/Little Snitch
echo "Removing /Library/Application Support/Objective Development/Little Snitch..."
if [ -d "/Library/Application Support/Objective Development/Little Snitch" ]; then
    rm -rf "/Library/Application Support/Objective Development/Little Snitch" 2>/dev/null || true
elif [ -f "/Library/Application Support/Objective Development/Little Snitch" ]; then
    rm -f "/Library/Application Support/Objective Development/Little Snitch" 2>/dev/null || true
fi

# Remove /Library/Caches/at.obdev.LittleSnitchConfiguration
echo "Removing /Library/Caches/at.obdev.LittleSnitchConfiguration..."
if [ -d "/Library/Caches/at.obdev.LittleSnitchConfiguration" ]; then
    rm -rf "/Library/Caches/at.obdev.LittleSnitchConfiguration" 2>/dev/null || true
elif [ -f "/Library/Caches/at.obdev.LittleSnitchConfiguration" ]; then
    rm -f "/Library/Caches/at.obdev.LittleSnitchConfiguration" 2>/dev/null || true
fi

# Remove /Library/Extensions/LittleSnitch.kext
echo "Removing /Library/Extensions/LittleSnitch.kext..."
if [ -d "/Library/Extensions/LittleSnitch.kext" ]; then
    rm -rf "/Library/Extensions/LittleSnitch.kext" 2>/dev/null || true
elif [ -f "/Library/Extensions/LittleSnitch.kext" ]; then
    rm -f "/Library/Extensions/LittleSnitch.kext" 2>/dev/null || true
fi

# Remove /Library/Little Snitch
echo "Removing /Library/Little Snitch..."
if [ -d "/Library/Little Snitch" ]; then
    rm -rf "/Library/Little Snitch" 2>/dev/null || true
elif [ -f "/Library/Little Snitch" ]; then
    rm -f "/Library/Little Snitch" 2>/dev/null || true
fi

# Remove /Library/Logs/LittleSnitchDaemon.log
echo "Removing /Library/Logs/LittleSnitchDaemon.log..."
if [ -d "/Library/Logs/LittleSnitchDaemon.log" ]; then
    rm -rf "/Library/Logs/LittleSnitchDaemon.log" 2>/dev/null || true
elif [ -f "/Library/Logs/LittleSnitchDaemon.log" ]; then
    rm -f "/Library/Logs/LittleSnitchDaemon.log" 2>/dev/null || true
fi

# Remove /Library/StagedExtensions/Library/Extensions/LittleSnitch.kext
echo "Removing /Library/StagedExtensions/Library/Extensions/LittleSnitch.kext..."
if [ -d "/Library/StagedExtensions/Library/Extensions/LittleSnitch.kext" ]; then
    rm -rf "/Library/StagedExtensions/Library/Extensions/LittleSnitch.kext" 2>/dev/null || true
elif [ -f "/Library/StagedExtensions/Library/Extensions/LittleSnitch.kext" ]; then
    rm -f "/Library/StagedExtensions/Library/Extensions/LittleSnitch.kext" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Little Snitch
echo "Removing $HOME/Library/Application Support/Little Snitch..."
if [ -d "$HOME/Library/Application Support/Little Snitch" ]; then
    rm -rf "$HOME/Library/Application Support/Little Snitch" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Little Snitch" ]; then
    rm -f "$HOME/Library/Application Support/Little Snitch" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/at.obdev.LittleSnitchAgent
echo "Removing $HOME/Library/Caches/at.obdev.LittleSnitchAgent..."
if [ -d "$HOME/Library/Caches/at.obdev.LittleSnitchAgent" ]; then
    rm -rf "$HOME/Library/Caches/at.obdev.LittleSnitchAgent" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/at.obdev.LittleSnitchAgent" ]; then
    rm -f "$HOME/Library/Caches/at.obdev.LittleSnitchAgent" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/at.obdev.LittleSnitchConfiguration
echo "Removing $HOME/Library/Caches/at.obdev.LittleSnitchConfiguration..."
if [ -d "$HOME/Library/Caches/at.obdev.LittleSnitchConfiguration" ]; then
    rm -rf "$HOME/Library/Caches/at.obdev.LittleSnitchConfiguration" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/at.obdev.LittleSnitchConfiguration" ]; then
    rm -f "$HOME/Library/Caches/at.obdev.LittleSnitchConfiguration" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/at.obdev.LittleSnitchHelper
echo "Removing $HOME/Library/Caches/at.obdev.LittleSnitchHelper..."
if [ -d "$HOME/Library/Caches/at.obdev.LittleSnitchHelper" ]; then
    rm -rf "$HOME/Library/Caches/at.obdev.LittleSnitchHelper" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/at.obdev.LittleSnitchHelper" ]; then
    rm -f "$HOME/Library/Caches/at.obdev.LittleSnitchHelper" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/at.obdev.LittleSnitchSoftwareUpdate
echo "Removing $HOME/Library/Caches/at.obdev.LittleSnitchSoftwareUpdate..."
if [ -d "$HOME/Library/Caches/at.obdev.LittleSnitchSoftwareUpdate" ]; then
    rm -rf "$HOME/Library/Caches/at.obdev.LittleSnitchSoftwareUpdate" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/at.obdev.LittleSnitchSoftwareUpdate" ]; then
    rm -f "$HOME/Library/Caches/at.obdev.LittleSnitchSoftwareUpdate" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.apple.helpd/Generated/at.obdev.LittleSnitchConfiguration.help*
echo "Removing $HOME/Library/Caches/com.apple.helpd/Generated/at.obdev.LittleSnitchConfiguration.help*..."
if [ -d "$HOME/Library/Caches/com.apple.helpd/Generated/at.obdev.LittleSnitchConfiguration.help*" ]; then
    rm -rf "$HOME/Library/Caches/com.apple.helpd/Generated/at.obdev.LittleSnitchConfiguration.help*" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.apple.helpd/Generated/at.obdev.LittleSnitchConfiguration.help*" ]; then
    rm -f "$HOME/Library/Caches/com.apple.helpd/Generated/at.obdev.LittleSnitchConfiguration.help*" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.apple.helpd/SDMHelpData/Other/English/HelpSDMIndexFile/at.obdev.LittleSnitchConfiguration.help*
echo "Removing $HOME/Library/Caches/com.apple.helpd/SDMHelpData/Other/English/HelpSDMIndexFile/at.obdev.LittleSnitchConfiguration.help*..."
if [ -d "$HOME/Library/Caches/com.apple.helpd/SDMHelpData/Other/English/HelpSDMIndexFile/at.obdev.LittleSnitchConfiguration.help*" ]; then
    rm -rf "$HOME/Library/Caches/com.apple.helpd/SDMHelpData/Other/English/HelpSDMIndexFile/at.obdev.LittleSnitchConfiguration.help*" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.apple.helpd/SDMHelpData/Other/English/HelpSDMIndexFile/at.obdev.LittleSnitchConfiguration.help*" ]; then
    rm -f "$HOME/Library/Caches/com.apple.helpd/SDMHelpData/Other/English/HelpSDMIndexFile/at.obdev.LittleSnitchConfiguration.help*" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/Little Snitch Agent.log
echo "Removing $HOME/Library/Logs/Little Snitch Agent.log..."
if [ -d "$HOME/Library/Logs/Little Snitch Agent.log" ]; then
    rm -rf "$HOME/Library/Logs/Little Snitch Agent.log" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/Little Snitch Agent.log" ]; then
    rm -f "$HOME/Library/Logs/Little Snitch Agent.log" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/Little Snitch Helper.log
echo "Removing $HOME/Library/Logs/Little Snitch Helper.log..."
if [ -d "$HOME/Library/Logs/Little Snitch Helper.log" ]; then
    rm -rf "$HOME/Library/Logs/Little Snitch Helper.log" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/Little Snitch Helper.log" ]; then
    rm -f "$HOME/Library/Logs/Little Snitch Helper.log" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/Little Snitch Installer.log
echo "Removing $HOME/Library/Logs/Little Snitch Installer.log..."
if [ -d "$HOME/Library/Logs/Little Snitch Installer.log" ]; then
    rm -rf "$HOME/Library/Logs/Little Snitch Installer.log" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/Little Snitch Installer.log" ]; then
    rm -f "$HOME/Library/Logs/Little Snitch Installer.log" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/Little Snitch Network Monitor.log
echo "Removing $HOME/Library/Logs/Little Snitch Network Monitor.log..."
if [ -d "$HOME/Library/Logs/Little Snitch Network Monitor.log" ]; then
    rm -rf "$HOME/Library/Logs/Little Snitch Network Monitor.log" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/Little Snitch Network Monitor.log" ]; then
    rm -f "$HOME/Library/Logs/Little Snitch Network Monitor.log" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/at.obdev.LittleSnitchAgent.plist
echo "Removing $HOME/Library/Preferences/at.obdev.LittleSnitchAgent.plist..."
if [ -d "$HOME/Library/Preferences/at.obdev.LittleSnitchAgent.plist" ]; then
    rm -rf "$HOME/Library/Preferences/at.obdev.LittleSnitchAgent.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/at.obdev.LittleSnitchAgent.plist" ]; then
    rm -f "$HOME/Library/Preferences/at.obdev.LittleSnitchAgent.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/at.obdev.LittleSnitchConfiguration.plist
echo "Removing $HOME/Library/Preferences/at.obdev.LittleSnitchConfiguration.plist..."
if [ -d "$HOME/Library/Preferences/at.obdev.LittleSnitchConfiguration.plist" ]; then
    rm -rf "$HOME/Library/Preferences/at.obdev.LittleSnitchConfiguration.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/at.obdev.LittleSnitchConfiguration.plist" ]; then
    rm -f "$HOME/Library/Preferences/at.obdev.LittleSnitchConfiguration.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/at.obdev.LittleSnitchInstaller.plist
echo "Removing $HOME/Library/Preferences/at.obdev.LittleSnitchInstaller.plist..."
if [ -d "$HOME/Library/Preferences/at.obdev.LittleSnitchInstaller.plist" ]; then
    rm -rf "$HOME/Library/Preferences/at.obdev.LittleSnitchInstaller.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/at.obdev.LittleSnitchInstaller.plist" ]; then
    rm -f "$HOME/Library/Preferences/at.obdev.LittleSnitchInstaller.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/at.obdev.LittleSnitchNetworkMonitor.plist
echo "Removing $HOME/Library/Preferences/at.obdev.LittleSnitchNetworkMonitor.plist..."
if [ -d "$HOME/Library/Preferences/at.obdev.LittleSnitchNetworkMonitor.plist" ]; then
    rm -rf "$HOME/Library/Preferences/at.obdev.LittleSnitchNetworkMonitor.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/at.obdev.LittleSnitchNetworkMonitor.plist" ]; then
    rm -f "$HOME/Library/Preferences/at.obdev.LittleSnitchNetworkMonitor.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/at.obdev.LittleSnitchSoftwareUpdate.plist
echo "Removing $HOME/Library/Preferences/at.obdev.LittleSnitchSoftwareUpdate.plist..."
if [ -d "$HOME/Library/Preferences/at.obdev.LittleSnitchSoftwareUpdate.plist" ]; then
    rm -rf "$HOME/Library/Preferences/at.obdev.LittleSnitchSoftwareUpdate.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/at.obdev.LittleSnitchSoftwareUpdate.plist" ]; then
    rm -f "$HOME/Library/Preferences/at.obdev.LittleSnitchSoftwareUpdate.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/at.obdev.LittleSnitchInstaller.savedState
echo "Removing $HOME/Library/Saved Application State/at.obdev.LittleSnitchInstaller.savedState..."
if [ -d "$HOME/Library/Saved Application State/at.obdev.LittleSnitchInstaller.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/at.obdev.LittleSnitchInstaller.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/at.obdev.LittleSnitchInstaller.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/at.obdev.LittleSnitchInstaller.savedState" 2>/dev/null || true
fi

# Remove $HOME/Library/WebKit/at.obdev.LittleSnitchConfiguration
echo "Removing $HOME/Library/WebKit/at.obdev.LittleSnitchConfiguration..."
if [ -d "$HOME/Library/WebKit/at.obdev.LittleSnitchConfiguration" ]; then
    rm -rf "$HOME/Library/WebKit/at.obdev.LittleSnitchConfiguration" 2>/dev/null || true
elif [ -f "$HOME/Library/WebKit/at.obdev.LittleSnitchConfiguration" ]; then
    rm -f "$HOME/Library/WebKit/at.obdev.LittleSnitchConfiguration" 2>/dev/null || true
fi

# Remove /Library/Application Support/Objective Development
echo "Removing /Library/Application Support/Objective Development..."
if [ -d "/Library/Application Support/Objective Development" ]; then
    rm -rf "/Library/Application Support/Objective Development" 2>/dev/null || true
elif [ -f "/Library/Application Support/Objective Development" ]; then
    rm -f "/Library/Application Support/Objective Development" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
