#!/bin/bash
# Uninstall script for Philips Hue Sync
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Philips Hue Sync..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Philips Hue Sync if running..."
pkill -f "Philips Hue Sync" 2>/dev/null || true

# Kill application with bundle ID com.lighting.huesync if running
echo "Stopping application with bundle ID com.lighting.huesync if running..."
killall -9 "com.lighting.huesync" 2>/dev/null || true

# Kill application with bundle ID com.lighting.huesync.watchdog if running
echo "Stopping application with bundle ID com.lighting.huesync.watchdog if running..."
killall -9 "com.lighting.huesync.watchdog" 2>/dev/null || true

# Remove $HOME/Library/Application Support/com.lighting.huesync
echo "Removing $HOME/Library/Application Support/com.lighting.huesync..."
if [ -d "$HOME/Library/Application Support/com.lighting.huesync" ]; then
    rm -rf "$HOME/Library/Application Support/com.lighting.huesync" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.lighting.huesync" ]; then
    rm -f "$HOME/Library/Application Support/com.lighting.huesync" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/Hue Sync
echo "Removing $HOME/Library/Caches/Hue Sync..."
if [ -d "$HOME/Library/Caches/Hue Sync" ]; then
    rm -rf "$HOME/Library/Caches/Hue Sync" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/Hue Sync" ]; then
    rm -f "$HOME/Library/Caches/Hue Sync" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.lighting.huesync.Hue Sync.plist
echo "Removing $HOME/Library/Preferences/com.lighting.huesync.Hue Sync.plist..."
if [ -d "$HOME/Library/Preferences/com.lighting.huesync.Hue Sync.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.lighting.huesync.Hue Sync.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.lighting.huesync.Hue Sync.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.lighting.huesync.Hue Sync.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
