#!/bin/bash
# Uninstall script for portx
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling portx..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping portx if running..."
pkill -f "portx" 2>/dev/null || true

# Remove /Applications/PortX.app
echo "Removing /Applications/PortX.app..."
if [ -d "/Applications/PortX.app" ]; then
    rm -rf "/Applications/PortX.app" 2>/dev/null || true
elif [ -f "/Applications/PortX.app" ]; then
    rm -f "/Applications/PortX.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.netsarang.portx.sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.netsarang.portx.sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.netsarang.portx.sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.netsarang.portx.sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.netsarang.portx.sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.netsarang.portx.sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/PortX
echo "Removing $HOME/Library/Application Support/PortX..."
if [ -d "$HOME/Library/Application Support/PortX" ]; then
    rm -rf "$HOME/Library/Application Support/PortX" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/PortX" ]; then
    rm -f "$HOME/Library/Application Support/PortX" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/PortX
echo "Removing $HOME/Library/Logs/PortX..."
if [ -d "$HOME/Library/Logs/PortX" ]; then
    rm -rf "$HOME/Library/Logs/PortX" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/PortX" ]; then
    rm -f "$HOME/Library/Logs/PortX" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.netsarang.portx.plist
echo "Removing $HOME/Library/Preferences/com.netsarang.portx.plist..."
if [ -d "$HOME/Library/Preferences/com.netsarang.portx.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.netsarang.portx.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.netsarang.portx.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.netsarang.portx.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.netsarang.portx.savedState
echo "Removing $HOME/Library/Saved Application State/com.netsarang.portx.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.netsarang.portx.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.netsarang.portx.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.netsarang.portx.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.netsarang.portx.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
