#!/bin/bash
# Uninstall script for Paintbrush
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Paintbrush..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Paintbrush if running..."
pkill -f "Paintbrush" 2>/dev/null || true

# Remove /Applications/Paintbrush.app
echo "Removing /Applications/Paintbrush.app..."
if [ -d "/Applications/Paintbrush.app" ]; then
    rm -rf "/Applications/Paintbrush.app" 2>/dev/null || true
elif [ -f "/Applications/Paintbrush.app" ]; then
    rm -f "/Applications/Paintbrush.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/com.soggywaffles.Paintbrush
echo "Removing $HOME/Library/Application Scripts/com.soggywaffles.Paintbrush..."
if [ -d "$HOME/Library/Application Scripts/com.soggywaffles.Paintbrush" ]; then
    rm -rf "$HOME/Library/Application Scripts/com.soggywaffles.Paintbrush" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/com.soggywaffles.Paintbrush" ]; then
    rm -f "$HOME/Library/Application Scripts/com.soggywaffles.Paintbrush" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.soggywaffles.paintbrush.sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.soggywaffles.paintbrush.sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.soggywaffles.paintbrush.sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.soggywaffles.paintbrush.sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.soggywaffles.paintbrush.sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.soggywaffles.paintbrush.sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.soggywaffles.Paintbrush
echo "Removing $HOME/Library/Caches/com.soggywaffles.Paintbrush..."
if [ -d "$HOME/Library/Caches/com.soggywaffles.Paintbrush" ]; then
    rm -rf "$HOME/Library/Caches/com.soggywaffles.Paintbrush" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.soggywaffles.Paintbrush" ]; then
    rm -f "$HOME/Library/Caches/com.soggywaffles.Paintbrush" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.soggywaffles.Paintbrush
echo "Removing $HOME/Library/Containers/com.soggywaffles.Paintbrush..."
if [ -d "$HOME/Library/Containers/com.soggywaffles.Paintbrush" ]; then
    rm -rf "$HOME/Library/Containers/com.soggywaffles.Paintbrush" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.soggywaffles.Paintbrush" ]; then
    rm -f "$HOME/Library/Containers/com.soggywaffles.Paintbrush" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.soggywaffles.Paintbrush.LSSharedFileList.plist
echo "Removing $HOME/Library/Preferences/com.soggywaffles.Paintbrush.LSSharedFileList.plist..."
if [ -d "$HOME/Library/Preferences/com.soggywaffles.Paintbrush.LSSharedFileList.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.soggywaffles.Paintbrush.LSSharedFileList.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.soggywaffles.Paintbrush.LSSharedFileList.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.soggywaffles.Paintbrush.LSSharedFileList.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.soggywaffles.Paintbrush.plist
echo "Removing $HOME/Library/Preferences/com.soggywaffles.Paintbrush.plist..."
if [ -d "$HOME/Library/Preferences/com.soggywaffles.Paintbrush.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.soggywaffles.Paintbrush.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.soggywaffles.Paintbrush.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.soggywaffles.Paintbrush.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
