#!/bin/bash
# Uninstall script for Huly
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Huly..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Huly if running..."
pkill -f "Huly" 2>/dev/null || true

# Remove /Applications/Huly.app
echo "Removing /Applications/Huly.app..."
if [ -d "/Applications/Huly.app" ]; then
    rm -rf "/Applications/Huly.app" 2>/dev/null || true
elif [ -f "/Applications/Huly.app" ]; then
    rm -f "/Applications/Huly.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/hc.hcengineering.huly.sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/hc.hcengineering.huly.sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/hc.hcengineering.huly.sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/hc.hcengineering.huly.sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/hc.hcengineering.huly.sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/hc.hcengineering.huly.sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Huly Desktop
echo "Removing $HOME/Library/Application Support/Huly Desktop..."
if [ -d "$HOME/Library/Application Support/Huly Desktop" ]; then
    rm -rf "$HOME/Library/Application Support/Huly Desktop" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Huly Desktop" ]; then
    rm -f "$HOME/Library/Application Support/Huly Desktop" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/Huly Desktop
echo "Removing $HOME/Library/Logs/Huly Desktop..."
if [ -d "$HOME/Library/Logs/Huly Desktop" ]; then
    rm -rf "$HOME/Library/Logs/Huly Desktop" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/Huly Desktop" ]; then
    rm -f "$HOME/Library/Logs/Huly Desktop" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/hc.hcengineering.Huly.plist
echo "Removing $HOME/Library/Preferences/hc.hcengineering.Huly.plist..."
if [ -d "$HOME/Library/Preferences/hc.hcengineering.Huly.plist" ]; then
    rm -rf "$HOME/Library/Preferences/hc.hcengineering.Huly.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/hc.hcengineering.Huly.plist" ]; then
    rm -f "$HOME/Library/Preferences/hc.hcengineering.Huly.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/hc.hcengineering.Huly.savedState
echo "Removing $HOME/Library/Saved Application State/hc.hcengineering.Huly.savedState..."
if [ -d "$HOME/Library/Saved Application State/hc.hcengineering.Huly.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/hc.hcengineering.Huly.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/hc.hcengineering.Huly.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/hc.hcengineering.Huly.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
