#!/bin/bash
# Uninstall script for DevToys
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling DevToys..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping DevToys if running..."
pkill -f "DevToys" 2>/dev/null || true

# Remove /Applications/DevToys.app
echo "Removing /Applications/DevToys.app..."
if [ -d "/Applications/DevToys.app" ]; then
    rm -rf "/Applications/DevToys.app" 2>/dev/null || true
elif [ -f "/Applications/DevToys.app" ]; then
    rm -f "/Applications/DevToys.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.devtoys
echo "Removing $HOME/Library/Caches/com.devtoys..."
if [ -d "$HOME/Library/Caches/com.devtoys" ]; then
    rm -rf "$HOME/Library/Caches/com.devtoys" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.devtoys" ]; then
    rm -f "$HOME/Library/Caches/com.devtoys" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.devtoys.preview
echo "Removing $HOME/Library/Caches/com.devtoys.preview..."
if [ -d "$HOME/Library/Caches/com.devtoys.preview" ]; then
    rm -rf "$HOME/Library/Caches/com.devtoys.preview" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.devtoys.preview" ]; then
    rm -f "$HOME/Library/Caches/com.devtoys.preview" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.devtoys.plist
echo "Removing $HOME/Library/Preferences/com.devtoys.plist..."
if [ -d "$HOME/Library/Preferences/com.devtoys.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.devtoys.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.devtoys.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.devtoys.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.yuki.DevToys.plist
echo "Removing $HOME/Library/Preferences/com.yuki.DevToys.plist..."
if [ -d "$HOME/Library/Preferences/com.yuki.DevToys.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.yuki.DevToys.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.yuki.DevToys.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.yuki.DevToys.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/WebKit/com.devtoys
echo "Removing $HOME/Library/WebKit/com.devtoys..."
if [ -d "$HOME/Library/WebKit/com.devtoys" ]; then
    rm -rf "$HOME/Library/WebKit/com.devtoys" 2>/dev/null || true
elif [ -f "$HOME/Library/WebKit/com.devtoys" ]; then
    rm -f "$HOME/Library/WebKit/com.devtoys" 2>/dev/null || true
fi

# Remove $HOME/Library/WebKit/com.devtoys.app
echo "Removing $HOME/Library/WebKit/com.devtoys.app..."
if [ -d "$HOME/Library/WebKit/com.devtoys.app" ]; then
    rm -rf "$HOME/Library/WebKit/com.devtoys.app" 2>/dev/null || true
elif [ -f "$HOME/Library/WebKit/com.devtoys.app" ]; then
    rm -f "$HOME/Library/WebKit/com.devtoys.app" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
