#!/bin/bash
# Uninstall script for QLab
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling QLab..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping QLab if running..."
pkill -f "QLab" 2>/dev/null || true

# Remove /Applications/QLab.app
echo "Removing /Applications/QLab.app..."
if [ -d "/Applications/QLab.app" ]; then
    rm -rf "/Applications/QLab.app" 2>/dev/null || true
elif [ -f "/Applications/QLab.app" ]; then
    rm -f "/Applications/QLab.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/QLab
echo "Removing $HOME/Library/Application Support/QLab..."
if [ -d "$HOME/Library/Application Support/QLab" ]; then
    rm -rf "$HOME/Library/Application Support/QLab" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/QLab" ]; then
    rm -f "$HOME/Library/Application Support/QLab" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.figure53.QLab.5
echo "Removing $HOME/Library/HTTPStorages/com.figure53.QLab.5..."
if [ -d "$HOME/Library/HTTPStorages/com.figure53.QLab.5" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.figure53.QLab.5" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.figure53.QLab.5" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.figure53.QLab.5" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.figure53.QLab.5.plist
echo "Removing $HOME/Library/Preferences/com.figure53.QLab.5.plist..."
if [ -d "$HOME/Library/Preferences/com.figure53.QLab.5.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.figure53.QLab.5.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.figure53.QLab.5.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.figure53.QLab.5.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.figure53.QLab.5.savedState
echo "Removing $HOME/Library/Saved Application State/com.figure53.QLab.5.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.figure53.QLab.5.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.figure53.QLab.5.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.figure53.QLab.5.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.figure53.QLab.5.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
