#!/bin/bash
# Uninstall script for Reqable
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Reqable..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Reqable if running..."
pkill -f "Reqable" 2>/dev/null || true

# Remove /Applications/Reqable.app
echo "Removing /Applications/Reqable.app..."
if [ -d "/Applications/Reqable.app" ]; then
    rm -rf "/Applications/Reqable.app" 2>/dev/null || true
elif [ -f "/Applications/Reqable.app" ]; then
    rm -f "/Applications/Reqable.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/Reqable
echo "Removing $HOME/Library/Caches/Reqable..."
if [ -d "$HOME/Library/Caches/Reqable" ]; then
    rm -rf "$HOME/Library/Caches/Reqable" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/Reqable" ]; then
    rm -f "$HOME/Library/Caches/Reqable" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.reqable.macosx.plist
echo "Removing $HOME/Library/Preferences/com.reqable.macosx.plist..."
if [ -d "$HOME/Library/Preferences/com.reqable.macosx.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.reqable.macosx.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.reqable.macosx.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.reqable.macosx.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
