#!/bin/bash
# Uninstall script for Git Credential Manager
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Git Credential Manager..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Git Credential Manager if running..."
pkill -f "Git Credential Manager" 2>/dev/null || true

# Remove $HOME/Library/Preferences/git-credential-manager-ui.plist
echo "Removing $HOME/Library/Preferences/git-credential-manager-ui.plist..."
if [ -d "$HOME/Library/Preferences/git-credential-manager-ui.plist" ]; then
    rm -rf "$HOME/Library/Preferences/git-credential-manager-ui.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/git-credential-manager-ui.plist" ]; then
    rm -f "$HOME/Library/Preferences/git-credential-manager-ui.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/git-credential-manager.plist
echo "Removing $HOME/Library/Preferences/git-credential-manager.plist..."
if [ -d "$HOME/Library/Preferences/git-credential-manager.plist" ]; then
    rm -rf "$HOME/Library/Preferences/git-credential-manager.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/git-credential-manager.plist" ]; then
    rm -f "$HOME/Library/Preferences/git-credential-manager.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
