#!/bin/bash
# Uninstall script for Todoist
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Todoist..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Todoist if running..."
pkill -f "Todoist" 2>/dev/null || true

# Remove /Applications/Todoist.app
echo "Removing /Applications/Todoist.app..."
if [ -d "/Applications/Todoist.app" ]; then
    rm -rf "/Applications/Todoist.app" 2>/dev/null || true
elif [ -f "/Applications/Todoist.app" ]; then
    rm -f "/Applications/Todoist.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/*com.todoist.mac*
echo "Removing $HOME/Library/Application Scripts/*com.todoist.mac*..."
if [ -d "$HOME/Library/Application Scripts/*com.todoist.mac*" ]; then
    rm -rf "$HOME/Library/Application Scripts/*com.todoist.mac*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/*com.todoist.mac*" ]; then
    rm -f "$HOME/Library/Application Scripts/*com.todoist.mac*" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Todoist
echo "Removing $HOME/Library/Application Support/Todoist..."
if [ -d "$HOME/Library/Application Support/Todoist" ]; then
    rm -rf "$HOME/Library/Application Support/Todoist" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Todoist" ]; then
    rm -f "$HOME/Library/Application Support/Todoist" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.todoist.mac.Todoist*
echo "Removing $HOME/Library/Containers/com.todoist.mac.Todoist*..."
if [ -d "$HOME/Library/Containers/com.todoist.mac.Todoist*" ]; then
    rm -rf "$HOME/Library/Containers/com.todoist.mac.Todoist*" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.todoist.mac.Todoist*" ]; then
    rm -f "$HOME/Library/Containers/com.todoist.mac.Todoist*" 2>/dev/null || true
fi

# Remove $HOME/Library/Group Containers/*com.todoist.mac*
echo "Removing $HOME/Library/Group Containers/*com.todoist.mac*..."
if [ -d "$HOME/Library/Group Containers/*com.todoist.mac*" ]; then
    rm -rf "$HOME/Library/Group Containers/*com.todoist.mac*" 2>/dev/null || true
elif [ -f "$HOME/Library/Group Containers/*com.todoist.mac*" ]; then
    rm -f "$HOME/Library/Group Containers/*com.todoist.mac*" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/Todoist
echo "Removing $HOME/Library/Logs/Todoist..."
if [ -d "$HOME/Library/Logs/Todoist" ]; then
    rm -rf "$HOME/Library/Logs/Todoist" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/Todoist" ]; then
    rm -f "$HOME/Library/Logs/Todoist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.todoist.mac.Todoist.plist
echo "Removing $HOME/Library/Preferences/com.todoist.mac.Todoist.plist..."
if [ -d "$HOME/Library/Preferences/com.todoist.mac.Todoist.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.todoist.mac.Todoist.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.todoist.mac.Todoist.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.todoist.mac.Todoist.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.todoist.mac.Todoist.savedState
echo "Removing $HOME/Library/Saved Application State/com.todoist.mac.Todoist.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.todoist.mac.Todoist.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.todoist.mac.Todoist.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.todoist.mac.Todoist.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.todoist.mac.Todoist.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
