#!/bin/bash
# Uninstall script for A Better Finder Rename
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling A Better Finder Rename..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping A Better Finder Rename if running..."
pkill -f "A Better Finder Rename" 2>/dev/null || true

# Remove /Applications/A Better Finder Rename 12.app
echo "Removing /Applications/A Better Finder Rename 12.app..."
if [ -d "/Applications/A Better Finder Rename 12.app" ]; then
    rm -rf "/Applications/A Better Finder Rename 12.app" 2>/dev/null || true
elif [ -f "/Applications/A Better Finder Rename 12.app" ]; then
    rm -f "/Applications/A Better Finder Rename 12.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/A Better Finder Rename 12
echo "Removing $HOME/Library/Application Support/A Better Finder Rename 12..."
if [ -d "$HOME/Library/Application Support/A Better Finder Rename 12" ]; then
    rm -rf "$HOME/Library/Application Support/A Better Finder Rename 12" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/A Better Finder Rename 12" ]; then
    rm -f "$HOME/Library/Application Support/A Better Finder Rename 12" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.apple.helpd/Generated/net.publicspace.abfr12.help*
echo "Removing $HOME/Library/Caches/com.apple.helpd/Generated/net.publicspace.abfr12.help*..."
if [ -d "$HOME/Library/Caches/com.apple.helpd/Generated/net.publicspace.abfr12.help*" ]; then
    rm -rf "$HOME/Library/Caches/com.apple.helpd/Generated/net.publicspace.abfr12.help*" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.apple.helpd/Generated/net.publicspace.abfr12.help*" ]; then
    rm -f "$HOME/Library/Caches/com.apple.helpd/Generated/net.publicspace.abfr12.help*" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/net.publicspace.abfr12
echo "Removing $HOME/Library/Caches/net.publicspace.abfr12..."
if [ -d "$HOME/Library/Caches/net.publicspace.abfr12" ]; then
    rm -rf "$HOME/Library/Caches/net.publicspace.abfr12" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/net.publicspace.abfr12" ]; then
    rm -f "$HOME/Library/Caches/net.publicspace.abfr12" 2>/dev/null || true
fi

# Remove $HOME/Library/Cookies/net.publicspace.abfr12.binarycookies
echo "Removing $HOME/Library/Cookies/net.publicspace.abfr12.binarycookies..."
if [ -d "$HOME/Library/Cookies/net.publicspace.abfr12.binarycookies" ]; then
    rm -rf "$HOME/Library/Cookies/net.publicspace.abfr12.binarycookies" 2>/dev/null || true
elif [ -f "$HOME/Library/Cookies/net.publicspace.abfr12.binarycookies" ]; then
    rm -f "$HOME/Library/Cookies/net.publicspace.abfr12.binarycookies" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/net.publicspace.abfr12.plist
echo "Removing $HOME/Library/Preferences/net.publicspace.abfr12.plist..."
if [ -d "$HOME/Library/Preferences/net.publicspace.abfr12.plist" ]; then
    rm -rf "$HOME/Library/Preferences/net.publicspace.abfr12.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/net.publicspace.abfr12.plist" ]; then
    rm -f "$HOME/Library/Preferences/net.publicspace.abfr12.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/net.publicspace.abfr12.savedState
echo "Removing $HOME/Library/Saved Application State/net.publicspace.abfr12.savedState..."
if [ -d "$HOME/Library/Saved Application State/net.publicspace.abfr12.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/net.publicspace.abfr12.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/net.publicspace.abfr12.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/net.publicspace.abfr12.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
