#!/bin/bash
# Uninstall script for NordLocker
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling NordLocker..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping NordLocker if running..."
pkill -f "NordLocker" 2>/dev/null || true

# Unload service com.nordlocker.macos.launcher
echo "Unloading service com.nordlocker.macos.launcher..."
launchctl unload -w /Library/LaunchAgents/com.nordlocker.macos.launcher.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.nordlocker.macos.launcher.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.nordlocker.macos.launcher.plist 2>/dev/null || true

# Unload service com.nordlocker.nordfs.Mounter.Helper
echo "Unloading service com.nordlocker.nordfs.Mounter.Helper..."
launchctl unload -w /Library/LaunchAgents/com.nordlocker.nordfs.Mounter.Helper.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.nordlocker.nordfs.Mounter.Helper.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.nordlocker.nordfs.Mounter.Helper.plist 2>/dev/null || true

# Kill application with bundle ID com.nordlocker.macos if running
echo "Stopping application with bundle ID com.nordlocker.macos if running..."
killall -9 "com.nordlocker.macos" 2>/dev/null || true

# Kill application with bundle ID com.nordlocker.macos.launcher if running
echo "Stopping application with bundle ID com.nordlocker.macos.launcher if running..."
killall -9 "com.nordlocker.macos.launcher" 2>/dev/null || true

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.nordlocker.macos.sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.nordlocker.macos.sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.nordlocker.macos.sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.nordlocker.macos.sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.nordlocker.macos.sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.nordlocker.macos.sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.nordlocker.macos
echo "Removing $HOME/Library/Caches/com.nordlocker.macos..."
if [ -d "$HOME/Library/Caches/com.nordlocker.macos" ]; then
    rm -rf "$HOME/Library/Caches/com.nordlocker.macos" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.nordlocker.macos" ]; then
    rm -f "$HOME/Library/Caches/com.nordlocker.macos" 2>/dev/null || true
fi

# Remove $HOME/Library/Cookies/com.nordlocker.macos.binarycookies
echo "Removing $HOME/Library/Cookies/com.nordlocker.macos.binarycookies..."
if [ -d "$HOME/Library/Cookies/com.nordlocker.macos.binarycookies" ]; then
    rm -rf "$HOME/Library/Cookies/com.nordlocker.macos.binarycookies" 2>/dev/null || true
elif [ -f "$HOME/Library/Cookies/com.nordlocker.macos.binarycookies" ]; then
    rm -f "$HOME/Library/Cookies/com.nordlocker.macos.binarycookies" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.nordlocker.macos.plist
echo "Removing $HOME/Library/Preferences/com.nordlocker.macos.plist..."
if [ -d "$HOME/Library/Preferences/com.nordlocker.macos.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.nordlocker.macos.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.nordlocker.macos.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.nordlocker.macos.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/group.com.nordlocker.macos.firebase.plist
echo "Removing $HOME/Library/Preferences/group.com.nordlocker.macos.firebase.plist..."
if [ -d "$HOME/Library/Preferences/group.com.nordlocker.macos.firebase.plist" ]; then
    rm -rf "$HOME/Library/Preferences/group.com.nordlocker.macos.firebase.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/group.com.nordlocker.macos.firebase.plist" ]; then
    rm -f "$HOME/Library/Preferences/group.com.nordlocker.macos.firebase.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.nordlocker.macos.savedState
echo "Removing $HOME/Library/Saved Application State/com.nordlocker.macos.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.nordlocker.macos.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.nordlocker.macos.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.nordlocker.macos.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.nordlocker.macos.savedState" 2>/dev/null || true
fi

# Remove $HOME/Library/WebKit/com.nordlocker.macos
echo "Removing $HOME/Library/WebKit/com.nordlocker.macos..."
if [ -d "$HOME/Library/WebKit/com.nordlocker.macos" ]; then
    rm -rf "$HOME/Library/WebKit/com.nordlocker.macos" 2>/dev/null || true
elif [ -f "$HOME/Library/WebKit/com.nordlocker.macos" ]; then
    rm -f "$HOME/Library/WebKit/com.nordlocker.macos" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
