#!/bin/bash
# Uninstall script for Grammarly Desktop
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Grammarly Desktop..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Grammarly Desktop if running..."
pkill -f "Grammarly Desktop" 2>/dev/null || true

# Remove /Applications/Grammarly Installer.app
echo "Removing /Applications/Grammarly Installer.app..."
if [ -d "/Applications/Grammarly Installer.app" ]; then
    rm -rf "/Applications/Grammarly Installer.app" 2>/dev/null || true
elif [ -f "/Applications/Grammarly Installer.app" ]; then
    rm -f "/Applications/Grammarly Installer.app" 2>/dev/null || true
fi

# Remove /Applications/{'target': 'Grammarly Desktop.app'}
echo "Removing /Applications/{'target': 'Grammarly Desktop.app'}..."
if [ -d "/Applications/{'target': 'Grammarly Desktop.app'}" ]; then
    rm -rf "/Applications/{'target': 'Grammarly Desktop.app'}" 2>/dev/null || true
elif [ -f "/Applications/{'target': 'Grammarly Desktop.app'}" ]; then
    rm -f "/Applications/{'target': 'Grammarly Desktop.app'}" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.grammarly.ProjectLlama
echo "Removing $HOME/Library/Application Support/com.grammarly.ProjectLlama..."
if [ -d "$HOME/Library/Application Support/com.grammarly.ProjectLlama" ]; then
    rm -rf "$HOME/Library/Application Support/com.grammarly.ProjectLlama" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.grammarly.ProjectLlama" ]; then
    rm -f "$HOME/Library/Application Support/com.grammarly.ProjectLlama" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.grammarly.ProjectLlama
echo "Removing $HOME/Library/Caches/com.grammarly.ProjectLlama..."
if [ -d "$HOME/Library/Caches/com.grammarly.ProjectLlama" ]; then
    rm -rf "$HOME/Library/Caches/com.grammarly.ProjectLlama" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.grammarly.ProjectLlama" ]; then
    rm -f "$HOME/Library/Caches/com.grammarly.ProjectLlama" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.grammarly.ProjectLlama.plist
echo "Removing $HOME/Library/Preferences/com.grammarly.ProjectLlama.plist..."
if [ -d "$HOME/Library/Preferences/com.grammarly.ProjectLlama.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.grammarly.ProjectLlama.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.grammarly.ProjectLlama.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.grammarly.ProjectLlama.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
