#!/bin/bash
# Uninstall script for Proxyman
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Proxyman..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Proxyman if running..."
pkill -f "Proxyman" 2>/dev/null || true

# Unload service com.proxyman.NSProxy.HelperTool
echo "Unloading service com.proxyman.NSProxy.HelperTool..."
launchctl unload -w /Library/LaunchAgents/com.proxyman.NSProxy.HelperTool.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.proxyman.NSProxy.HelperTool.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.proxyman.NSProxy.HelperTool.plist 2>/dev/null || true

# Kill application with bundle ID com.proxyman.NSProxy if running
echo "Stopping application with bundle ID com.proxyman.NSProxy if running..."
killall -9 "com.proxyman.NSProxy" 2>/dev/null || true

# Remove /Applications/Proxyman.app
echo "Removing /Applications/Proxyman.app..."
if [ -d "/Applications/Proxyman.app" ]; then
    rm -rf "/Applications/Proxyman.app" 2>/dev/null || true
elif [ -f "/Applications/Proxyman.app" ]; then
    rm -f "/Applications/Proxyman.app" 2>/dev/null || true
fi

# Remove binary /Applications/Proxyman.app/Proxyman.app/Contents/MacOS/proxyman-cli
echo "Removing binary /Applications/Proxyman.app/Proxyman.app/Contents/MacOS/proxyman-cli..."
if [ -f "/Applications/Proxyman.app/Proxyman.app/Contents/MacOS/proxyman-cli" ]; then
    rm -f "/Applications/Proxyman.app/Proxyman.app/Contents/MacOS/proxyman-cli" 2>/dev/null || true
fi

# Remove $HOME/.proxyman*
echo "Removing $HOME/.proxyman*..."
if [ -d "$HOME/.proxyman*" ]; then
    rm -rf "$HOME/.proxyman*" 2>/dev/null || true
elif [ -f "$HOME/.proxyman*" ]; then
    rm -f "$HOME/.proxyman*" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.proxyman.nsproxy.sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.proxyman.nsproxy.sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.proxyman.nsproxy.sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.proxyman.nsproxy.sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.proxyman.nsproxy.sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.proxyman.nsproxy.sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.proxyman
echo "Removing $HOME/Library/Application Support/com.proxyman..."
if [ -d "$HOME/Library/Application Support/com.proxyman" ]; then
    rm -rf "$HOME/Library/Application Support/com.proxyman" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.proxyman" ]; then
    rm -f "$HOME/Library/Application Support/com.proxyman" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.proxyman.NSProxy
echo "Removing $HOME/Library/Application Support/com.proxyman.NSProxy..."
if [ -d "$HOME/Library/Application Support/com.proxyman.NSProxy" ]; then
    rm -rf "$HOME/Library/Application Support/com.proxyman.NSProxy" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.proxyman.NSProxy" ]; then
    rm -f "$HOME/Library/Application Support/com.proxyman.NSProxy" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.plausiblelabs.crashreporter.data/com.proxyman.NSProxy
echo "Removing $HOME/Library/Caches/com.plausiblelabs.crashreporter.data/com.proxyman.NSProxy..."
if [ -d "$HOME/Library/Caches/com.plausiblelabs.crashreporter.data/com.proxyman.NSProxy" ]; then
    rm -rf "$HOME/Library/Caches/com.plausiblelabs.crashreporter.data/com.proxyman.NSProxy" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.plausiblelabs.crashreporter.data/com.proxyman.NSProxy" ]; then
    rm -f "$HOME/Library/Caches/com.plausiblelabs.crashreporter.data/com.proxyman.NSProxy" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.proxyman.NSProxy
echo "Removing $HOME/Library/Caches/com.proxyman.NSProxy..."
if [ -d "$HOME/Library/Caches/com.proxyman.NSProxy" ]; then
    rm -rf "$HOME/Library/Caches/com.proxyman.NSProxy" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.proxyman.NSProxy" ]; then
    rm -f "$HOME/Library/Caches/com.proxyman.NSProxy" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/Proxyman
echo "Removing $HOME/Library/Caches/Proxyman..."
if [ -d "$HOME/Library/Caches/Proxyman" ]; then
    rm -rf "$HOME/Library/Caches/Proxyman" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/Proxyman" ]; then
    rm -f "$HOME/Library/Caches/Proxyman" 2>/dev/null || true
fi

# Remove $HOME/Library/Cookies/com.proxyman.binarycookies
echo "Removing $HOME/Library/Cookies/com.proxyman.binarycookies..."
if [ -d "$HOME/Library/Cookies/com.proxyman.binarycookies" ]; then
    rm -rf "$HOME/Library/Cookies/com.proxyman.binarycookies" 2>/dev/null || true
elif [ -f "$HOME/Library/Cookies/com.proxyman.binarycookies" ]; then
    rm -f "$HOME/Library/Cookies/com.proxyman.binarycookies" 2>/dev/null || true
fi

# Remove $HOME/Library/Cookies/com.proxyman.NSProxy.binarycookies
echo "Removing $HOME/Library/Cookies/com.proxyman.NSProxy.binarycookies..."
if [ -d "$HOME/Library/Cookies/com.proxyman.NSProxy.binarycookies" ]; then
    rm -rf "$HOME/Library/Cookies/com.proxyman.NSProxy.binarycookies" 2>/dev/null || true
elif [ -f "$HOME/Library/Cookies/com.proxyman.NSProxy.binarycookies" ]; then
    rm -f "$HOME/Library/Cookies/com.proxyman.NSProxy.binarycookies" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.proxyman.NSProxy
echo "Removing $HOME/Library/HTTPStorages/com.proxyman.NSProxy..."
if [ -d "$HOME/Library/HTTPStorages/com.proxyman.NSProxy" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.proxyman.NSProxy" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.proxyman.NSProxy" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.proxyman.NSProxy" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.proxyman.iconappmanager.userdefaults.plist
echo "Removing $HOME/Library/Preferences/com.proxyman.iconappmanager.userdefaults.plist..."
if [ -d "$HOME/Library/Preferences/com.proxyman.iconappmanager.userdefaults.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.proxyman.iconappmanager.userdefaults.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.proxyman.iconappmanager.userdefaults.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.proxyman.iconappmanager.userdefaults.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.proxyman.NSProxy.plist
echo "Removing $HOME/Library/Preferences/com.proxyman.NSProxy.plist..."
if [ -d "$HOME/Library/Preferences/com.proxyman.NSProxy.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.proxyman.NSProxy.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.proxyman.NSProxy.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.proxyman.NSProxy.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.proxyman.plist
echo "Removing $HOME/Library/Preferences/com.proxyman.plist..."
if [ -d "$HOME/Library/Preferences/com.proxyman.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.proxyman.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.proxyman.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.proxyman.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.proxyman.NSProxy.savedState
echo "Removing $HOME/Library/Saved Application State/com.proxyman.NSProxy.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.proxyman.NSProxy.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.proxyman.NSProxy.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.proxyman.NSProxy.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.proxyman.NSProxy.savedState" 2>/dev/null || true
fi

# Remove $HOME/Library/WebKit/com.proxyman.NSProxy
echo "Removing $HOME/Library/WebKit/com.proxyman.NSProxy..."
if [ -d "$HOME/Library/WebKit/com.proxyman.NSProxy" ]; then
    rm -rf "$HOME/Library/WebKit/com.proxyman.NSProxy" 2>/dev/null || true
elif [ -f "$HOME/Library/WebKit/com.proxyman.NSProxy" ]; then
    rm -f "$HOME/Library/WebKit/com.proxyman.NSProxy" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
