#!/bin/bash
# Uninstall script for Retcon
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Retcon..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Retcon if running..."
pkill -f "Retcon" 2>/dev/null || true

# Remove /Applications/Retcon.app
echo "Removing /Applications/Retcon.app..."
if [ -d "/Applications/Retcon.app" ]; then
    rm -rf "/Applications/Retcon.app" 2>/dev/null || true
elif [ -f "/Applications/Retcon.app" ]; then
    rm -f "/Applications/Retcon.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/garden.lemon.retcon.sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/garden.lemon.retcon.sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/garden.lemon.retcon.sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/garden.lemon.retcon.sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/garden.lemon.retcon.sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/garden.lemon.retcon.sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Retcon
echo "Removing $HOME/Library/Application Support/Retcon..."
if [ -d "$HOME/Library/Application Support/Retcon" ]; then
    rm -rf "$HOME/Library/Application Support/Retcon" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Retcon" ]; then
    rm -f "$HOME/Library/Application Support/Retcon" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/garden.lemon.Retcon
echo "Removing $HOME/Library/Caches/garden.lemon.Retcon..."
if [ -d "$HOME/Library/Caches/garden.lemon.Retcon" ]; then
    rm -rf "$HOME/Library/Caches/garden.lemon.Retcon" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/garden.lemon.Retcon" ]; then
    rm -f "$HOME/Library/Caches/garden.lemon.Retcon" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/garden.lemon.Retcon
echo "Removing $HOME/Library/HTTPStorages/garden.lemon.Retcon..."
if [ -d "$HOME/Library/HTTPStorages/garden.lemon.Retcon" ]; then
    rm -rf "$HOME/Library/HTTPStorages/garden.lemon.Retcon" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/garden.lemon.Retcon" ]; then
    rm -f "$HOME/Library/HTTPStorages/garden.lemon.Retcon" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/garden.lemon.Retcon.plist
echo "Removing $HOME/Library/Preferences/garden.lemon.Retcon.plist..."
if [ -d "$HOME/Library/Preferences/garden.lemon.Retcon.plist" ]; then
    rm -rf "$HOME/Library/Preferences/garden.lemon.Retcon.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/garden.lemon.Retcon.plist" ]; then
    rm -f "$HOME/Library/Preferences/garden.lemon.Retcon.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/garden.lemon.Retcon.savedState
echo "Removing $HOME/Library/Saved Application State/garden.lemon.Retcon.savedState..."
if [ -d "$HOME/Library/Saved Application State/garden.lemon.Retcon.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/garden.lemon.Retcon.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/garden.lemon.Retcon.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/garden.lemon.Retcon.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
