#!/bin/bash
# Uninstall script for BLEUnlock
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling BLEUnlock..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping BLEUnlock if running..."
pkill -f "BLEUnlock" 2>/dev/null || true

# Remove /Applications/BLEUnlock.app
echo "Removing /Applications/BLEUnlock.app..."
if [ -d "/Applications/BLEUnlock.app" ]; then
    rm -rf "/Applications/BLEUnlock.app" 2>/dev/null || true
elif [ -f "/Applications/BLEUnlock.app" ]; then
    rm -f "/Applications/BLEUnlock.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/jp.sone.BLEUnlock
echo "Removing $HOME/Library/Application Scripts/jp.sone.BLEUnlock..."
if [ -d "$HOME/Library/Application Scripts/jp.sone.BLEUnlock" ]; then
    rm -rf "$HOME/Library/Application Scripts/jp.sone.BLEUnlock" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/jp.sone.BLEUnlock" ]; then
    rm -f "$HOME/Library/Application Scripts/jp.sone.BLEUnlock" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/jp.sone.BLEUnlock
echo "Removing $HOME/Library/Caches/jp.sone.BLEUnlock..."
if [ -d "$HOME/Library/Caches/jp.sone.BLEUnlock" ]; then
    rm -rf "$HOME/Library/Caches/jp.sone.BLEUnlock" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/jp.sone.BLEUnlock" ]; then
    rm -f "$HOME/Library/Caches/jp.sone.BLEUnlock" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/jp.sone.BLEUnlock.plist
echo "Removing $HOME/Library/Preferences/jp.sone.BLEUnlock.plist..."
if [ -d "$HOME/Library/Preferences/jp.sone.BLEUnlock.plist" ]; then
    rm -rf "$HOME/Library/Preferences/jp.sone.BLEUnlock.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/jp.sone.BLEUnlock.plist" ]; then
    rm -f "$HOME/Library/Preferences/jp.sone.BLEUnlock.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
