#!/bin/bash
# Uninstall script for HazeOver
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling HazeOver..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping HazeOver if running..."
pkill -f "HazeOver" 2>/dev/null || true

# Unload service com.pointum.hazeover.launcher
echo "Unloading service com.pointum.hazeover.launcher..."
launchctl unload -w /Library/LaunchAgents/com.pointum.hazeover.launcher.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.pointum.hazeover.launcher.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.pointum.hazeover.launcher.plist 2>/dev/null || true

# Kill application with bundle ID com.pointum.hazeover if running
echo "Stopping application with bundle ID com.pointum.hazeover if running..."
killall -9 "com.pointum.hazeover" 2>/dev/null || true

# Remove /Applications/HazeOver.app
echo "Removing /Applications/HazeOver.app..."
if [ -d "/Applications/HazeOver.app" ]; then
    rm -rf "/Applications/HazeOver.app" 2>/dev/null || true
elif [ -f "/Applications/HazeOver.app" ]; then
    rm -f "/Applications/HazeOver.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.pointum.hazeover
echo "Removing $HOME/Library/Caches/com.pointum.hazeover..."
if [ -d "$HOME/Library/Caches/com.pointum.hazeover" ]; then
    rm -rf "$HOME/Library/Caches/com.pointum.hazeover" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.pointum.hazeover" ]; then
    rm -f "$HOME/Library/Caches/com.pointum.hazeover" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.pointum.hazeover.plist
echo "Removing $HOME/Library/Preferences/com.pointum.hazeover.plist..."
if [ -d "$HOME/Library/Preferences/com.pointum.hazeover.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.pointum.hazeover.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.pointum.hazeover.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.pointum.hazeover.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
