#!/bin/bash
# Uninstall script for VimR
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling VimR..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping VimR if running..."
pkill -f "VimR" 2>/dev/null || true

# Remove /Applications/VimR.app
echo "Removing /Applications/VimR.app..."
if [ -d "/Applications/VimR.app" ]; then
    rm -rf "/Applications/VimR.app" 2>/dev/null || true
elif [ -f "/Applications/VimR.app" ]; then
    rm -f "/Applications/VimR.app" 2>/dev/null || true
fi

# Remove binary /Applications/VimR.app/VimR.app/Contents/Resources/vimr
echo "Removing binary /Applications/VimR.app/VimR.app/Contents/Resources/vimr..."
if [ -f "/Applications/VimR.app/VimR.app/Contents/Resources/vimr" ]; then
    rm -f "/Applications/VimR.app/VimR.app/Contents/Resources/vimr" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.qvacua.VimR
echo "Removing $HOME/Library/Caches/com.qvacua.VimR..."
if [ -d "$HOME/Library/Caches/com.qvacua.VimR" ]; then
    rm -rf "$HOME/Library/Caches/com.qvacua.VimR" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.qvacua.VimR" ]; then
    rm -f "$HOME/Library/Caches/com.qvacua.VimR" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.qvacua.VimR.menuitems.plist
echo "Removing $HOME/Library/Preferences/com.qvacua.VimR.menuitems.plist..."
if [ -d "$HOME/Library/Preferences/com.qvacua.VimR.menuitems.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.qvacua.VimR.menuitems.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.qvacua.VimR.menuitems.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.qvacua.VimR.menuitems.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.qvacua.VimR.plist
echo "Removing $HOME/Library/Preferences/com.qvacua.VimR.plist..."
if [ -d "$HOME/Library/Preferences/com.qvacua.VimR.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.qvacua.VimR.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.qvacua.VimR.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.qvacua.VimR.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.qvacua.VimR.savedState
echo "Removing $HOME/Library/Saved Application State/com.qvacua.VimR.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.qvacua.VimR.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.qvacua.VimR.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.qvacua.VimR.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.qvacua.VimR.savedState" 2>/dev/null || true
fi

# Remove $HOME/Library/WebKit/com.qvacua.VimR
echo "Removing $HOME/Library/WebKit/com.qvacua.VimR..."
if [ -d "$HOME/Library/WebKit/com.qvacua.VimR" ]; then
    rm -rf "$HOME/Library/WebKit/com.qvacua.VimR" 2>/dev/null || true
elif [ -f "$HOME/Library/WebKit/com.qvacua.VimR" ]; then
    rm -f "$HOME/Library/WebKit/com.qvacua.VimR" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
