#!/bin/bash
# Uninstall script for Elephas
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Elephas..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Elephas if running..."
pkill -f "Elephas" 2>/dev/null || true

# Remove /Applications/Elephas.app
echo "Removing /Applications/Elephas.app..."
if [ -d "/Applications/Elephas.app" ]; then
    rm -rf "/Applications/Elephas.app" 2>/dev/null || true
elif [ -f "/Applications/Elephas.app" ]; then
    rm -f "/Applications/Elephas.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Elephas
echo "Removing $HOME/Library/Application Support/Elephas..."
if [ -d "$HOME/Library/Application Support/Elephas" ]; then
    rm -rf "$HOME/Library/Application Support/Elephas" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Elephas" ]; then
    rm -f "$HOME/Library/Application Support/Elephas" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.kamban.elephas
echo "Removing $HOME/Library/Caches/com.kamban.elephas..."
if [ -d "$HOME/Library/Caches/com.kamban.elephas" ]; then
    rm -rf "$HOME/Library/Caches/com.kamban.elephas" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.kamban.elephas" ]; then
    rm -f "$HOME/Library/Caches/com.kamban.elephas" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.kamban.elephas
echo "Removing $HOME/Library/HTTPStorages/com.kamban.elephas..."
if [ -d "$HOME/Library/HTTPStorages/com.kamban.elephas" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.kamban.elephas" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.kamban.elephas" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.kamban.elephas" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.kamban.elephas.plist
echo "Removing $HOME/Library/Preferences/com.kamban.elephas.plist..."
if [ -d "$HOME/Library/Preferences/com.kamban.elephas.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.kamban.elephas.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.kamban.elephas.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.kamban.elephas.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
