#!/bin/bash
# Uninstall script for blip
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling blip..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping blip if running..."
pkill -f "blip" 2>/dev/null || true

# Remove /Applications/Blip.app
echo "Removing /Applications/Blip.app..."
if [ -d "/Applications/Blip.app" ]; then
    rm -rf "/Applications/Blip.app" 2>/dev/null || true
elif [ -f "/Applications/Blip.app" ]; then
    rm -f "/Applications/Blip.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/AY8UB8KTUX.blip
echo "Removing $HOME/Library/Application Scripts/AY8UB8KTUX.blip..."
if [ -d "$HOME/Library/Application Scripts/AY8UB8KTUX.blip" ]; then
    rm -rf "$HOME/Library/Application Scripts/AY8UB8KTUX.blip" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/AY8UB8KTUX.blip" ]; then
    rm -f "$HOME/Library/Application Scripts/AY8UB8KTUX.blip" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/net.blip.macos.preview-provider
echo "Removing $HOME/Library/Application Scripts/net.blip.macos.preview-provider..."
if [ -d "$HOME/Library/Application Scripts/net.blip.macos.preview-provider" ]; then
    rm -rf "$HOME/Library/Application Scripts/net.blip.macos.preview-provider" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/net.blip.macos.preview-provider" ]; then
    rm -f "$HOME/Library/Application Scripts/net.blip.macos.preview-provider" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/net.blip.macos.share
echo "Removing $HOME/Library/Application Scripts/net.blip.macos.share..."
if [ -d "$HOME/Library/Application Scripts/net.blip.macos.share" ]; then
    rm -rf "$HOME/Library/Application Scripts/net.blip.macos.share" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/net.blip.macos.share" ]; then
    rm -f "$HOME/Library/Application Scripts/net.blip.macos.share" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/net.blip.macos.sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/net.blip.macos.sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/net.blip.macos.sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/net.blip.macos.sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/net.blip.macos.sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/net.blip.macos.sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/net.blip.macos.preview-provider
echo "Removing $HOME/Library/Containers/net.blip.macos.preview-provider..."
if [ -d "$HOME/Library/Containers/net.blip.macos.preview-provider" ]; then
    rm -rf "$HOME/Library/Containers/net.blip.macos.preview-provider" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/net.blip.macos.preview-provider" ]; then
    rm -f "$HOME/Library/Containers/net.blip.macos.preview-provider" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/net.blip.macos.share
echo "Removing $HOME/Library/Containers/net.blip.macos.share..."
if [ -d "$HOME/Library/Containers/net.blip.macos.share" ]; then
    rm -rf "$HOME/Library/Containers/net.blip.macos.share" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/net.blip.macos.share" ]; then
    rm -f "$HOME/Library/Containers/net.blip.macos.share" 2>/dev/null || true
fi

# Remove $HOME/Library/Group Containers/AY8UB8KTUX.blip
echo "Removing $HOME/Library/Group Containers/AY8UB8KTUX.blip..."
if [ -d "$HOME/Library/Group Containers/AY8UB8KTUX.blip" ]; then
    rm -rf "$HOME/Library/Group Containers/AY8UB8KTUX.blip" 2>/dev/null || true
elif [ -f "$HOME/Library/Group Containers/AY8UB8KTUX.blip" ]; then
    rm -f "$HOME/Library/Group Containers/AY8UB8KTUX.blip" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/net.blip.macos
echo "Removing $HOME/Library/HTTPStorages/net.blip.macos..."
if [ -d "$HOME/Library/HTTPStorages/net.blip.macos" ]; then
    rm -rf "$HOME/Library/HTTPStorages/net.blip.macos" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/net.blip.macos" ]; then
    rm -f "$HOME/Library/HTTPStorages/net.blip.macos" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/net.blip.macos.binarycookies
echo "Removing $HOME/Library/HTTPStorages/net.blip.macos.binarycookies..."
if [ -d "$HOME/Library/HTTPStorages/net.blip.macos.binarycookies" ]; then
    rm -rf "$HOME/Library/HTTPStorages/net.blip.macos.binarycookies" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/net.blip.macos.binarycookies" ]; then
    rm -f "$HOME/Library/HTTPStorages/net.blip.macos.binarycookies" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/net.blip.macos.plist
echo "Removing $HOME/Library/Preferences/net.blip.macos.plist..."
if [ -d "$HOME/Library/Preferences/net.blip.macos.plist" ]; then
    rm -rf "$HOME/Library/Preferences/net.blip.macos.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/net.blip.macos.plist" ]; then
    rm -f "$HOME/Library/Preferences/net.blip.macos.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
