#!/bin/bash
# Uninstall script for Acronis True Image
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Acronis True Image..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Acronis True Image if running..."
pkill -f "Acronis True Image" 2>/dev/null || true

# Unload service com.acronis.aakore
echo "Unloading service com.acronis.aakore..."
launchctl unload -w /Library/LaunchAgents/com.acronis.aakore.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.acronis.aakore.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.acronis.aakore.plist 2>/dev/null || true

# Unload service com.acronis.acep
echo "Unloading service com.acronis.acep..."
launchctl unload -w /Library/LaunchAgents/com.acronis.acep.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.acronis.acep.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.acronis.acep.plist 2>/dev/null || true

# Unload service com.acronis.acroprld_client
echo "Unloading service com.acronis.acroprld_client..."
launchctl unload -w /Library/LaunchAgents/com.acronis.acroprld_client.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.acronis.acroprld_client.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.acronis.acroprld_client.plist 2>/dev/null || true

# Unload service com.acronis.active_protection
echo "Unloading service com.acronis.active_protection..."
launchctl unload -w /Library/LaunchAgents/com.acronis.active_protection.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.acronis.active_protection.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.acronis.active_protection.plist 2>/dev/null || true

# Unload service com.acronis.cyber-protect-service
echo "Unloading service com.acronis.cyber-protect-service..."
launchctl unload -w /Library/LaunchAgents/com.acronis.cyber-protect-service.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.acronis.cyber-protect-service.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.acronis.cyber-protect-service.plist 2>/dev/null || true

# Unload service com.acronis.escyberprotect
echo "Unloading service com.acronis.escyberprotect..."
launchctl unload -w /Library/LaunchAgents/com.acronis.escyberprotect.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.acronis.escyberprotect.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.acronis.escyberprotect.plist 2>/dev/null || true

# Unload service com.acronis.helpertool
echo "Unloading service com.acronis.helpertool..."
launchctl unload -w /Library/LaunchAgents/com.acronis.helpertool.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.acronis.helpertool.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.acronis.helpertool.plist 2>/dev/null || true

# Unload service com.acronis.mms_mini
echo "Unloading service com.acronis.mms_mini..."
launchctl unload -w /Library/LaunchAgents/com.acronis.mms_mini.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.acronis.mms_mini.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.acronis.mms_mini.plist 2>/dev/null || true

# Unload service com.acronis.mobile_backup_server
echo "Unloading service com.acronis.mobile_backup_server..."
launchctl unload -w /Library/LaunchAgents/com.acronis.mobile_backup_server.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.acronis.mobile_backup_server.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.acronis.mobile_backup_server.plist 2>/dev/null || true

# Unload service com.acronis.mobile_backup_status_server
echo "Unloading service com.acronis.mobile_backup_status_server..."
launchctl unload -w /Library/LaunchAgents/com.acronis.mobile_backup_status_server.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.acronis.mobile_backup_status_server.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.acronis.mobile_backup_status_server.plist 2>/dev/null || true

# Unload service com.acronis.monitor
echo "Unloading service com.acronis.monitor..."
launchctl unload -w /Library/LaunchAgents/com.acronis.monitor.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.acronis.monitor.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.acronis.monitor.plist 2>/dev/null || true

# Unload service com.acronis.scheduler
echo "Unloading service com.acronis.scheduler..."
launchctl unload -w /Library/LaunchAgents/com.acronis.scheduler.plist 2>/dev/null || true
launchctl unload -w /Library/LaunchDaemons/com.acronis.scheduler.plist 2>/dev/null || true
launchctl unload -w ~/Library/LaunchAgents/com.acronis.scheduler.plist 2>/dev/null || true

# Kill application with bundle ID com.acronis.CyberProtectHomeOffice if running
echo "Stopping application with bundle ID com.acronis.CyberProtectHomeOffice if running..."
killall -9 "com.acronis.CyberProtectHomeOffice" 2>/dev/null || true

# Kill application with bundle ID com.acronis.CyberProtectHomeOffice.FinderSyncExt if running
echo "Stopping application with bundle ID com.acronis.CyberProtectHomeOffice.FinderSyncExt if running..."
killall -9 "com.acronis.CyberProtectHomeOffice.FinderSyncExt" 2>/dev/null || true

# Kill application with bundle ID com.acronis.CyberProtectHomeOffice.help if running
echo "Stopping application with bundle ID com.acronis.CyberProtectHomeOffice.help if running..."
killall -9 "com.acronis.CyberProtectHomeOffice.help" 2>/dev/null || true

# Kill application with bundle ID com.acronis.CyberProtectHomeOffice.monitor if running
echo "Stopping application with bundle ID com.acronis.CyberProtectHomeOffice.monitor if running..."
killall -9 "com.acronis.CyberProtectHomeOffice.monitor" 2>/dev/null || true

# Kill application with bundle ID com.acronis.escyberprotect if running
echo "Stopping application with bundle ID com.acronis.escyberprotect if running..."
killall -9 "com.acronis.escyberprotect" 2>/dev/null || true

# Remove $HOME/Library/Application Scripts/com.acronis.CyberProtectHomeOffice.FinderSyncExt
echo "Removing $HOME/Library/Application Scripts/com.acronis.CyberProtectHomeOffice.FinderSyncExt..."
if [ -d "$HOME/Library/Application Scripts/com.acronis.CyberProtectHomeOffice.FinderSyncExt" ]; then
    rm -rf "$HOME/Library/Application Scripts/com.acronis.CyberProtectHomeOffice.FinderSyncExt" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/com.acronis.CyberProtectHomeOffice.FinderSyncExt" ]; then
    rm -f "$HOME/Library/Application Scripts/com.acronis.CyberProtectHomeOffice.FinderSyncExt" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Acronis
echo "Removing $HOME/Library/Application Support/Acronis..."
if [ -d "$HOME/Library/Application Support/Acronis" ]; then
    rm -rf "$HOME/Library/Application Support/Acronis" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Acronis" ]; then
    rm -f "$HOME/Library/Application Support/Acronis" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.acronis.CyberProtectHomeOffice.FinderSyncExt
echo "Removing $HOME/Library/Containers/com.acronis.CyberProtectHomeOffice.FinderSyncExt..."
if [ -d "$HOME/Library/Containers/com.acronis.CyberProtectHomeOffice.FinderSyncExt" ]; then
    rm -rf "$HOME/Library/Containers/com.acronis.CyberProtectHomeOffice.FinderSyncExt" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.acronis.CyberProtectHomeOffice.FinderSyncExt" ]; then
    rm -f "$HOME/Library/Containers/com.acronis.CyberProtectHomeOffice.FinderSyncExt" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.acronis.CyberProtectHomeOffice.monitor
echo "Removing $HOME/Library/HTTPStorages/com.acronis.CyberProtectHomeOffice.monitor..."
if [ -d "$HOME/Library/HTTPStorages/com.acronis.CyberProtectHomeOffice.monitor" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.acronis.CyberProtectHomeOffice.monitor" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.acronis.CyberProtectHomeOffice.monitor" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.acronis.CyberProtectHomeOffice.monitor" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/Acronis
echo "Removing $HOME/Library/Logs/Acronis..."
if [ -d "$HOME/Library/Logs/Acronis" ]; then
    rm -rf "$HOME/Library/Logs/Acronis" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/Acronis" ]; then
    rm -f "$HOME/Library/Logs/Acronis" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.acronis.CyberProtectHomeOffice.plist
echo "Removing $HOME/Library/Preferences/com.acronis.CyberProtectHomeOffice.plist..."
if [ -d "$HOME/Library/Preferences/com.acronis.CyberProtectHomeOffice.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.acronis.CyberProtectHomeOffice.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.acronis.CyberProtectHomeOffice.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.acronis.CyberProtectHomeOffice.plist" 2>/dev/null || true
fi

# Remove /Library/Application Support/Acronis
echo "Removing /Library/Application Support/Acronis..."
if [ -d "/Library/Application Support/Acronis" ]; then
    rm -rf "/Library/Application Support/Acronis" 2>/dev/null || true
elif [ -f "/Library/Application Support/Acronis" ]; then
    rm -f "/Library/Application Support/Acronis" 2>/dev/null || true
fi

# Remove /Library/Application Support/BackupClient
echo "Removing /Library/Application Support/BackupClient..."
if [ -d "/Library/Application Support/BackupClient" ]; then
    rm -rf "/Library/Application Support/BackupClient" 2>/dev/null || true
elif [ -f "/Library/Application Support/BackupClient" ]; then
    rm -f "/Library/Application Support/BackupClient" 2>/dev/null || true
fi

# Remove /Library/PrivilegedHelperTools/com.acronis.helpertool
echo "Removing /Library/PrivilegedHelperTools/com.acronis.helpertool..."
if [ -d "/Library/PrivilegedHelperTools/com.acronis.helpertool" ]; then
    rm -rf "/Library/PrivilegedHelperTools/com.acronis.helpertool" 2>/dev/null || true
elif [ -f "/Library/PrivilegedHelperTools/com.acronis.helpertool" ]; then
    rm -f "/Library/PrivilegedHelperTools/com.acronis.helpertool" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
