#!/bin/bash
# Uninstall script for Tofu
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Tofu..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Tofu if running..."
pkill -f "Tofu" 2>/dev/null || true

# Remove /Applications/Tofu.app
echo "Removing /Applications/Tofu.app..."
if [ -d "/Applications/Tofu.app" ]; then
    rm -rf "/Applications/Tofu.app" 2>/dev/null || true
elif [ -f "/Applications/Tofu.app" ]; then
    rm -f "/Applications/Tofu.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/com.asagoo.tofu
echo "Removing $HOME/Library/Application Scripts/com.asagoo.tofu..."
if [ -d "$HOME/Library/Application Scripts/com.asagoo.tofu" ]; then
    rm -rf "$HOME/Library/Application Scripts/com.asagoo.tofu" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/com.asagoo.tofu" ]; then
    rm -f "$HOME/Library/Application Scripts/com.asagoo.tofu" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.asagoo.tofu.sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.asagoo.tofu.sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.asagoo.tofu.sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.asagoo.tofu.sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.asagoo.tofu.sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.asagoo.tofu.sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.asagoo.tofu
echo "Removing $HOME/Library/Containers/com.asagoo.tofu..."
if [ -d "$HOME/Library/Containers/com.asagoo.tofu" ]; then
    rm -rf "$HOME/Library/Containers/com.asagoo.tofu" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.asagoo.tofu" ]; then
    rm -f "$HOME/Library/Containers/com.asagoo.tofu" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
