#!/bin/bash
# Uninstall script for Airy
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Airy..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Airy if running..."
pkill -f "Airy" 2>/dev/null || true

# Kill application with bundle ID com.eltima.Airy if running
echo "Stopping application with bundle ID com.eltima.Airy if running..."
killall -9 "com.eltima.Airy" 2>/dev/null || true

# Remove /Applications/Airy.app
echo "Removing /Applications/Airy.app..."
if [ -d "/Applications/Airy.app" ]; then
    rm -rf "/Applications/Airy.app" 2>/dev/null || true
elif [ -f "/Applications/Airy.app" ]; then
    rm -f "/Applications/Airy.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.eltima.Airy.plist
echo "Removing $HOME/Library/Preferences/com.eltima.Airy.plist..."
if [ -d "$HOME/Library/Preferences/com.eltima.Airy.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.eltima.Airy.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.eltima.Airy.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.eltima.Airy.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
