#!/bin/bash
# Uninstall script for AnyDesk
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling AnyDesk..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping AnyDesk if running..."
pkill -f "AnyDesk" 2>/dev/null || true

# Kill application with bundle ID com.philandro.anydesk if running
echo "Stopping application with bundle ID com.philandro.anydesk if running..."
killall -9 "com.philandro.anydesk" 2>/dev/null || true

# Kill application with bundle ID com.philandro.anydesk.Frontend if running
echo "Stopping application with bundle ID com.philandro.anydesk.Frontend if running..."
killall -9 "com.philandro.anydesk.Frontend" 2>/dev/null || true

# Kill application with bundle ID com.philandro.anydesk.Helper if running
echo "Stopping application with bundle ID com.philandro.anydesk.Helper if running..."
killall -9 "com.philandro.anydesk.Helper" 2>/dev/null || true

# Kill application with bundle ID com.philandro.anydesk.service if running
echo "Stopping application with bundle ID com.philandro.anydesk.service if running..."
killall -9 "com.philandro.anydesk.service" 2>/dev/null || true

# Remove /Applications/AnyDesk.app
echo "Removing /Applications/AnyDesk.app..."
if [ -d "/Applications/AnyDesk.app" ]; then
    rm -rf "/Applications/AnyDesk.app" 2>/dev/null || true
elif [ -f "/Applications/AnyDesk.app" ]; then
    rm -f "/Applications/AnyDesk.app" 2>/dev/null || true
fi

# Remove $HOME/.anydesk
echo "Removing $HOME/.anydesk..."
if [ -d "$HOME/.anydesk" ]; then
    rm -rf "$HOME/.anydesk" 2>/dev/null || true
elif [ -f "$HOME/.anydesk" ]; then
    rm -f "$HOME/.anydesk" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.philandro.anydesk.plist
echo "Removing $HOME/Library/Preferences/com.philandro.anydesk.plist..."
if [ -d "$HOME/Library/Preferences/com.philandro.anydesk.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.philandro.anydesk.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.philandro.anydesk.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.philandro.anydesk.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
