#!/bin/bash
# Uninstall script for WebStorm
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling WebStorm..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping WebStorm if running..."
pkill -f "WebStorm" 2>/dev/null || true

# Remove /Applications/WebStorm.app
echo "Removing /Applications/WebStorm.app..."
if [ -d "/Applications/WebStorm.app" ]; then
    rm -rf "/Applications/WebStorm.app" 2>/dev/null || true
elif [ -f "/Applications/WebStorm.app" ]; then
    rm -f "/Applications/WebStorm.app" 2>/dev/null || true
fi

# Remove binary /Applications/WebStorm.app/WebStorm.app/Contents/MacOS/webstorm
echo "Removing binary /Applications/WebStorm.app/WebStorm.app/Contents/MacOS/webstorm..."
if [ -f "/Applications/WebStorm.app/WebStorm.app/Contents/MacOS/webstorm" ]; then
    rm -f "/Applications/WebStorm.app/WebStorm.app/Contents/MacOS/webstorm" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/JetBrains/WebStorm2024.3
echo "Removing $HOME/Library/Application Support/JetBrains/WebStorm2024.3..."
if [ -d "$HOME/Library/Application Support/JetBrains/WebStorm2024.3" ]; then
    rm -rf "$HOME/Library/Application Support/JetBrains/WebStorm2024.3" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/JetBrains/WebStorm2024.3" ]; then
    rm -f "$HOME/Library/Application Support/JetBrains/WebStorm2024.3" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.apple.nsurlsessiond/Downloads/com.jetbrains.WebStorm
echo "Removing $HOME/Library/Caches/com.apple.nsurlsessiond/Downloads/com.jetbrains.WebStorm..."
if [ -d "$HOME/Library/Caches/com.apple.nsurlsessiond/Downloads/com.jetbrains.WebStorm" ]; then
    rm -rf "$HOME/Library/Caches/com.apple.nsurlsessiond/Downloads/com.jetbrains.WebStorm" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.apple.nsurlsessiond/Downloads/com.jetbrains.WebStorm" ]; then
    rm -f "$HOME/Library/Caches/com.apple.nsurlsessiond/Downloads/com.jetbrains.WebStorm" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/JetBrains/WebStorm2024.3
echo "Removing $HOME/Library/Caches/JetBrains/WebStorm2024.3..."
if [ -d "$HOME/Library/Caches/JetBrains/WebStorm2024.3" ]; then
    rm -rf "$HOME/Library/Caches/JetBrains/WebStorm2024.3" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/JetBrains/WebStorm2024.3" ]; then
    rm -f "$HOME/Library/Caches/JetBrains/WebStorm2024.3" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/JetBrains/WebStorm2024.3
echo "Removing $HOME/Library/Logs/JetBrains/WebStorm2024.3..."
if [ -d "$HOME/Library/Logs/JetBrains/WebStorm2024.3" ]; then
    rm -rf "$HOME/Library/Logs/JetBrains/WebStorm2024.3" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/JetBrains/WebStorm2024.3" ]; then
    rm -f "$HOME/Library/Logs/JetBrains/WebStorm2024.3" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.jetbrains.WebStorm.plist
echo "Removing $HOME/Library/Preferences/com.jetbrains.WebStorm.plist..."
if [ -d "$HOME/Library/Preferences/com.jetbrains.WebStorm.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.jetbrains.WebStorm.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.jetbrains.WebStorm.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.jetbrains.WebStorm.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/jetbrains.webstorm.*.plist
echo "Removing $HOME/Library/Preferences/jetbrains.webstorm.*.plist..."
if [ -d "$HOME/Library/Preferences/jetbrains.webstorm.*.plist" ]; then
    rm -rf "$HOME/Library/Preferences/jetbrains.webstorm.*.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/jetbrains.webstorm.*.plist" ]; then
    rm -f "$HOME/Library/Preferences/jetbrains.webstorm.*.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/WebStorm2024.3
echo "Removing $HOME/Library/Preferences/WebStorm2024.3..."
if [ -d "$HOME/Library/Preferences/WebStorm2024.3" ]; then
    rm -rf "$HOME/Library/Preferences/WebStorm2024.3" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/WebStorm2024.3" ]; then
    rm -f "$HOME/Library/Preferences/WebStorm2024.3" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/webstorm.plist
echo "Removing $HOME/Library/Preferences/webstorm.plist..."
if [ -d "$HOME/Library/Preferences/webstorm.plist" ]; then
    rm -rf "$HOME/Library/Preferences/webstorm.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/webstorm.plist" ]; then
    rm -f "$HOME/Library/Preferences/webstorm.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.jetbrains.WebStorm.savedState
echo "Removing $HOME/Library/Saved Application State/com.jetbrains.WebStorm.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.jetbrains.WebStorm.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.jetbrains.WebStorm.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.jetbrains.WebStorm.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.jetbrains.WebStorm.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
