#!/bin/bash
# Uninstall script for MultiViewer for F1
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling MultiViewer for F1..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping MultiViewer for F1 if running..."
pkill -f "MultiViewer for F1" 2>/dev/null || true

# Remove /Applications/MultiViewer for F1.app
echo "Removing /Applications/MultiViewer for F1.app..."
if [ -d "/Applications/MultiViewer for F1.app" ]; then
    rm -rf "/Applications/MultiViewer for F1.app" 2>/dev/null || true
elif [ -f "/Applications/MultiViewer for F1.app" ]; then
    rm -f "/Applications/MultiViewer for F1.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/MultiViewer for F1
echo "Removing $HOME/Library/Application Support/MultiViewer for F1..."
if [ -d "$HOME/Library/Application Support/MultiViewer for F1" ]; then
    rm -rf "$HOME/Library/Application Support/MultiViewer for F1" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/MultiViewer for F1" ]; then
    rm -f "$HOME/Library/Application Support/MultiViewer for F1" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.electron.multiviewer-for-f1
echo "Removing $HOME/Library/Caches/com.electron.multiviewer-for-f1..."
if [ -d "$HOME/Library/Caches/com.electron.multiviewer-for-f1" ]; then
    rm -rf "$HOME/Library/Caches/com.electron.multiviewer-for-f1" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.electron.multiviewer-for-f1" ]; then
    rm -f "$HOME/Library/Caches/com.electron.multiviewer-for-f1" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.electron.multiviewer-for-f1.ShipIt
echo "Removing $HOME/Library/Caches/com.electron.multiviewer-for-f1.ShipIt..."
if [ -d "$HOME/Library/Caches/com.electron.multiviewer-for-f1.ShipIt" ]; then
    rm -rf "$HOME/Library/Caches/com.electron.multiviewer-for-f1.ShipIt" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.electron.multiviewer-for-f1.ShipIt" ]; then
    rm -f "$HOME/Library/Caches/com.electron.multiviewer-for-f1.ShipIt" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.electron.multiviewer-for-f1
echo "Removing $HOME/Library/HTTPStorages/com.electron.multiviewer-for-f1..."
if [ -d "$HOME/Library/HTTPStorages/com.electron.multiviewer-for-f1" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.electron.multiviewer-for-f1" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.electron.multiviewer-for-f1" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.electron.multiviewer-for-f1" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.electron.multiviewer-for-f1.plist
echo "Removing $HOME/Library/Preferences/com.electron.multiviewer-for-f1.plist..."
if [ -d "$HOME/Library/Preferences/com.electron.multiviewer-for-f1.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.electron.multiviewer-for-f1.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.electron.multiviewer-for-f1.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.electron.multiviewer-for-f1.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.electron.multiviewer-for-f1.savedState
echo "Removing $HOME/Library/Saved Application State/com.electron.multiviewer-for-f1.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.electron.multiviewer-for-f1.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.electron.multiviewer-for-f1.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.electron.multiviewer-for-f1.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.electron.multiviewer-for-f1.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
