#!/bin/bash
# Uninstall script for iTerm2
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling iTerm2..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping iTerm2 if running..."
pkill -f "iTerm2" 2>/dev/null || true

# Remove /Applications/iTerm.app
echo "Removing /Applications/iTerm.app..."
if [ -d "/Applications/iTerm.app" ]; then
    rm -rf "/Applications/iTerm.app" 2>/dev/null || true
elif [ -f "/Applications/iTerm.app" ]; then
    rm -f "/Applications/iTerm.app" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
