#!/bin/bash
# Uninstall script for Microsoft Azure Storage Explorer
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Microsoft Azure Storage Explorer..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Microsoft Azure Storage Explorer if running..."
pkill -f "Microsoft Azure Storage Explorer" 2>/dev/null || true

# Remove /Applications/Microsoft Azure Storage Explorer.app
echo "Removing /Applications/Microsoft Azure Storage Explorer.app..."
if [ -d "/Applications/Microsoft Azure Storage Explorer.app" ]; then
    rm -rf "/Applications/Microsoft Azure Storage Explorer.app" 2>/dev/null || true
elif [ -f "/Applications/Microsoft Azure Storage Explorer.app" ]; then
    rm -f "/Applications/Microsoft Azure Storage Explorer.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/StorageExplorer
echo "Removing $HOME/Library/Application Support/StorageExplorer..."
if [ -d "$HOME/Library/Application Support/StorageExplorer" ]; then
    rm -rf "$HOME/Library/Application Support/StorageExplorer" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/StorageExplorer" ]; then
    rm -f "$HOME/Library/Application Support/StorageExplorer" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/StorageExplorer
echo "Removing $HOME/Library/Logs/StorageExplorer..."
if [ -d "$HOME/Library/Logs/StorageExplorer" ]; then
    rm -rf "$HOME/Library/Logs/StorageExplorer" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/StorageExplorer" ]; then
    rm -f "$HOME/Library/Logs/StorageExplorer" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.microsoft.StorageExplorer.plist
echo "Removing $HOME/Library/Preferences/com.microsoft.StorageExplorer.plist..."
if [ -d "$HOME/Library/Preferences/com.microsoft.StorageExplorer.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.microsoft.StorageExplorer.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.microsoft.StorageExplorer.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.microsoft.StorageExplorer.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
