#!/bin/bash
# Uninstall script for IsThereNet
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling IsThereNet..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping IsThereNet if running..."
pkill -f "IsThereNet" 2>/dev/null || true

# Kill application with bundle ID com.lowtechguys.IsThereNet if running
echo "Stopping application with bundle ID com.lowtechguys.IsThereNet if running..."
killall -9 "com.lowtechguys.IsThereNet" 2>/dev/null || true

# Remove /Applications/IsThereNet.app
echo "Removing /Applications/IsThereNet.app..."
if [ -d "/Applications/IsThereNet.app" ]; then
    rm -rf "/Applications/IsThereNet.app" 2>/dev/null || true
elif [ -f "/Applications/IsThereNet.app" ]; then
    rm -f "/Applications/IsThereNet.app" 2>/dev/null || true
fi

# Remove $HOME/.config/istherenet/
echo "Removing $HOME/.config/istherenet/..."
if [ -d "$HOME/.config/istherenet/" ]; then
    rm -rf "$HOME/.config/istherenet/" 2>/dev/null || true
elif [ -f "$HOME/.config/istherenet/" ]; then
    rm -f "$HOME/.config/istherenet/" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/com.lowtechguys.IsThereNet
echo "Removing $HOME/Library/Application Scripts/com.lowtechguys.IsThereNet..."
if [ -d "$HOME/Library/Application Scripts/com.lowtechguys.IsThereNet" ]; then
    rm -rf "$HOME/Library/Application Scripts/com.lowtechguys.IsThereNet" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/com.lowtechguys.IsThereNet" ]; then
    rm -f "$HOME/Library/Application Scripts/com.lowtechguys.IsThereNet" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.lowtechguys.IsThereNet.plist
echo "Removing $HOME/Library/Preferences/com.lowtechguys.IsThereNet.plist..."
if [ -d "$HOME/Library/Preferences/com.lowtechguys.IsThereNet.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.lowtechguys.IsThereNet.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.lowtechguys.IsThereNet.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.lowtechguys.IsThereNet.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/WebKit/com.lowtechguys.IsThereNet
echo "Removing $HOME/Library/WebKit/com.lowtechguys.IsThereNet..."
if [ -d "$HOME/Library/WebKit/com.lowtechguys.IsThereNet" ]; then
    rm -rf "$HOME/Library/WebKit/com.lowtechguys.IsThereNet" 2>/dev/null || true
elif [ -f "$HOME/Library/WebKit/com.lowtechguys.IsThereNet" ]; then
    rm -f "$HOME/Library/WebKit/com.lowtechguys.IsThereNet" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
