#!/bin/bash
# Uninstall script for DeepL
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling DeepL..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping DeepL if running..."
pkill -f "DeepL" 2>/dev/null || true

# Remove /Applications/DeepL.app
echo "Removing /Applications/DeepL.app..."
if [ -d "/Applications/DeepL.app" ]; then
    rm -rf "/Applications/DeepL.app" 2>/dev/null || true
elif [ -f "/Applications/DeepL.app" ]; then
    rm -f "/Applications/DeepL.app" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
