#!/bin/bash
# Uninstall script for Google Drive
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Google Drive..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Google Drive if running..."
pkill -f "Google Drive" 2>/dev/null || true

# Kill application with bundle ID com.google.drivefs if running
echo "Stopping application with bundle ID com.google.drivefs if running..."
killall -9 "com.google.drivefs" 2>/dev/null || true

# Kill application with bundle ID com.google.drivefs.finderhelper.findersync if running
echo "Stopping application with bundle ID com.google.drivefs.finderhelper.findersync if running..."
killall -9 "com.google.drivefs.finderhelper.findersync" 2>/dev/null || true

# Remove $HOME/Library/Application Scripts/com.google.drivefs*
echo "Removing $HOME/Library/Application Scripts/com.google.drivefs*..."
if [ -d "$HOME/Library/Application Scripts/com.google.drivefs*" ]; then
    rm -rf "$HOME/Library/Application Scripts/com.google.drivefs*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/com.google.drivefs*" ]; then
    rm -f "$HOME/Library/Application Scripts/com.google.drivefs*" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/EQHXZ8M8AV.group.com.google.drivefs
echo "Removing $HOME/Library/Application Scripts/EQHXZ8M8AV.group.com.google.drivefs..."
if [ -d "$HOME/Library/Application Scripts/EQHXZ8M8AV.group.com.google.drivefs" ]; then
    rm -rf "$HOME/Library/Application Scripts/EQHXZ8M8AV.group.com.google.drivefs" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/EQHXZ8M8AV.group.com.google.drivefs" ]; then
    rm -f "$HOME/Library/Application Scripts/EQHXZ8M8AV.group.com.google.drivefs" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/FileProvider/com.google.drivefs.fpext
echo "Removing $HOME/Library/Application Support/FileProvider/com.google.drivefs.fpext..."
if [ -d "$HOME/Library/Application Support/FileProvider/com.google.drivefs.fpext" ]; then
    rm -rf "$HOME/Library/Application Support/FileProvider/com.google.drivefs.fpext" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/FileProvider/com.google.drivefs.fpext" ]; then
    rm -f "$HOME/Library/Application Support/FileProvider/com.google.drivefs.fpext" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Google/DriveFS
echo "Removing $HOME/Library/Application Support/Google/DriveFS..."
if [ -d "$HOME/Library/Application Support/Google/DriveFS" ]; then
    rm -rf "$HOME/Library/Application Support/Google/DriveFS" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Google/DriveFS" ]; then
    rm -f "$HOME/Library/Application Support/Google/DriveFS" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.google.drivefs
echo "Removing $HOME/Library/Caches/com.google.drivefs..."
if [ -d "$HOME/Library/Caches/com.google.drivefs" ]; then
    rm -rf "$HOME/Library/Caches/com.google.drivefs" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.google.drivefs" ]; then
    rm -f "$HOME/Library/Caches/com.google.drivefs" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.google.drivefs*
echo "Removing $HOME/Library/Containers/com.google.drivefs*..."
if [ -d "$HOME/Library/Containers/com.google.drivefs*" ]; then
    rm -rf "$HOME/Library/Containers/com.google.drivefs*" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.google.drivefs*" ]; then
    rm -f "$HOME/Library/Containers/com.google.drivefs*" 2>/dev/null || true
fi

# Remove $HOME/Library/Group Containers/*group.com.google.drivefs
echo "Removing $HOME/Library/Group Containers/*group.com.google.drivefs..."
if [ -d "$HOME/Library/Group Containers/*group.com.google.drivefs" ]; then
    rm -rf "$HOME/Library/Group Containers/*group.com.google.drivefs" 2>/dev/null || true
elif [ -f "$HOME/Library/Group Containers/*group.com.google.drivefs" ]; then
    rm -f "$HOME/Library/Group Containers/*group.com.google.drivefs" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.google.drivefs*.plist
echo "Removing $HOME/Library/Preferences/com.google.drivefs*.plist..."
if [ -d "$HOME/Library/Preferences/com.google.drivefs*.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.google.drivefs*.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.google.drivefs*.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.google.drivefs*.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/Google Drive File Stream Helper.plist
echo "Removing $HOME/Library/Preferences/Google Drive File Stream Helper.plist..."
if [ -d "$HOME/Library/Preferences/Google Drive File Stream Helper.plist" ]; then
    rm -rf "$HOME/Library/Preferences/Google Drive File Stream Helper.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/Google Drive File Stream Helper.plist" ]; then
    rm -f "$HOME/Library/Preferences/Google Drive File Stream Helper.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
