#!/bin/bash
# Uninstall script for quarto
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling quarto..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping quarto if running..."
pkill -f "quarto" 2>/dev/null || true

# Remove $HOME/Library/Application Support/quarto
echo "Removing $HOME/Library/Application Support/quarto..."
if [ -d "$HOME/Library/Application Support/quarto" ]; then
    rm -rf "$HOME/Library/Application Support/quarto" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/quarto" ]; then
    rm -f "$HOME/Library/Application Support/quarto" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/quarto-writer
echo "Removing $HOME/Library/Application Support/quarto-writer..."
if [ -d "$HOME/Library/Application Support/quarto-writer" ]; then
    rm -rf "$HOME/Library/Application Support/quarto-writer" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/quarto-writer" ]; then
    rm -f "$HOME/Library/Application Support/quarto-writer" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/quarto
echo "Removing $HOME/Library/Caches/quarto..."
if [ -d "$HOME/Library/Caches/quarto" ]; then
    rm -rf "$HOME/Library/Caches/quarto" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/quarto" ]; then
    rm -f "$HOME/Library/Caches/quarto" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
