#!/bin/bash
# Uninstall script for Apifox
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Apifox..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Apifox if running..."
pkill -f "Apifox" 2>/dev/null || true

# Remove /Applications/Apifox.app
echo "Removing /Applications/Apifox.app..."
if [ -d "/Applications/Apifox.app" ]; then
    rm -rf "/Applications/Apifox.app" 2>/dev/null || true
elif [ -f "/Applications/Apifox.app" ]; then
    rm -f "/Applications/Apifox.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/apifox
echo "Removing $HOME/Library/Application Support/apifox..."
if [ -d "$HOME/Library/Application Support/apifox" ]; then
    rm -rf "$HOME/Library/Application Support/apifox" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/apifox" ]; then
    rm -f "$HOME/Library/Application Support/apifox" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/cn.apifox.app.plist
echo "Removing $HOME/Library/Preferences/cn.apifox.app.plist..."
if [ -d "$HOME/Library/Preferences/cn.apifox.app.plist" ]; then
    rm -rf "$HOME/Library/Preferences/cn.apifox.app.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/cn.apifox.app.plist" ]; then
    rm -f "$HOME/Library/Preferences/cn.apifox.app.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/cn.apifox.app.savedState
echo "Removing $HOME/Library/Saved Application State/cn.apifox.app.savedState..."
if [ -d "$HOME/Library/Saved Application State/cn.apifox.app.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/cn.apifox.app.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/cn.apifox.app.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/cn.apifox.app.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
