#!/bin/bash
# Uninstall script for Clop
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Clop..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Clop if running..."
pkill -f "Clop" 2>/dev/null || true

# Remove /Applications/Clop.app
echo "Removing /Applications/Clop.app..."
if [ -d "/Applications/Clop.app" ]; then
    rm -rf "/Applications/Clop.app" 2>/dev/null || true
elif [ -f "/Applications/Clop.app" ]; then
    rm -f "/Applications/Clop.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/com.lowtechguys.Clop
echo "Removing $HOME/Library/Application Scripts/com.lowtechguys.Clop..."
if [ -d "$HOME/Library/Application Scripts/com.lowtechguys.Clop" ]; then
    rm -rf "$HOME/Library/Application Scripts/com.lowtechguys.Clop" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/com.lowtechguys.Clop" ]; then
    rm -f "$HOME/Library/Application Scripts/com.lowtechguys.Clop" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/com.lowtechguys.Clop.FinderOptimiser
echo "Removing $HOME/Library/Application Scripts/com.lowtechguys.Clop.FinderOptimiser..."
if [ -d "$HOME/Library/Application Scripts/com.lowtechguys.Clop.FinderOptimiser" ]; then
    rm -rf "$HOME/Library/Application Scripts/com.lowtechguys.Clop.FinderOptimiser" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/com.lowtechguys.Clop.FinderOptimiser" ]; then
    rm -f "$HOME/Library/Application Scripts/com.lowtechguys.Clop.FinderOptimiser" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Clop
echo "Removing $HOME/Library/Application Support/Clop..."
if [ -d "$HOME/Library/Application Support/Clop" ]; then
    rm -rf "$HOME/Library/Application Support/Clop" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Clop" ]; then
    rm -f "$HOME/Library/Application Support/Clop" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/Clop
echo "Removing $HOME/Library/Caches/Clop..."
if [ -d "$HOME/Library/Caches/Clop" ]; then
    rm -rf "$HOME/Library/Caches/Clop" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/Clop" ]; then
    rm -f "$HOME/Library/Caches/Clop" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.lowtechguys.Clop.FinderOptimiser
echo "Removing $HOME/Library/Containers/com.lowtechguys.Clop.FinderOptimiser..."
if [ -d "$HOME/Library/Containers/com.lowtechguys.Clop.FinderOptimiser" ]; then
    rm -rf "$HOME/Library/Containers/com.lowtechguys.Clop.FinderOptimiser" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.lowtechguys.Clop.FinderOptimiser" ]; then
    rm -f "$HOME/Library/Containers/com.lowtechguys.Clop.FinderOptimiser" 2>/dev/null || true
fi

# Remove $HOME/Library/Daemon Containers/54F7B6C1*/Data/com.apple.kvs/ChangeTokens/NoEncryption/Clop/*.com.lowtechguys.Clop
echo "Removing $HOME/Library/Daemon Containers/54F7B6C1*/Data/com.apple.kvs/ChangeTokens/NoEncryption/Clop/*.com.lowtechguys.Clop..."
if [ -d "$HOME/Library/Daemon Containers/54F7B6C1*/Data/com.apple.kvs/ChangeTokens/NoEncryption/Clop/*.com.lowtechguys.Clop" ]; then
    rm -rf "$HOME/Library/Daemon Containers/54F7B6C1*/Data/com.apple.kvs/ChangeTokens/NoEncryption/Clop/*.com.lowtechguys.Clop" 2>/dev/null || true
elif [ -f "$HOME/Library/Daemon Containers/54F7B6C1*/Data/com.apple.kvs/ChangeTokens/NoEncryption/Clop/*.com.lowtechguys.Clop" ]; then
    rm -f "$HOME/Library/Daemon Containers/54F7B6C1*/Data/com.apple.kvs/ChangeTokens/NoEncryption/Clop/*.com.lowtechguys.Clop" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.lowtechguys.Clop
echo "Removing $HOME/Library/HTTPStorages/com.lowtechguys.Clop..."
if [ -d "$HOME/Library/HTTPStorages/com.lowtechguys.Clop" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.lowtechguys.Clop" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.lowtechguys.Clop" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.lowtechguys.Clop" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.lowtechguys.Clop.binarycookies
echo "Removing $HOME/Library/HTTPStorages/com.lowtechguys.Clop.binarycookies..."
if [ -d "$HOME/Library/HTTPStorages/com.lowtechguys.Clop.binarycookies" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.lowtechguys.Clop.binarycookies" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.lowtechguys.Clop.binarycookies" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.lowtechguys.Clop.binarycookies" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.lowtechguys.Clop.plist
echo "Removing $HOME/Library/Preferences/com.lowtechguys.Clop.plist..."
if [ -d "$HOME/Library/Preferences/com.lowtechguys.Clop.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.lowtechguys.Clop.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.lowtechguys.Clop.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.lowtechguys.Clop.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
