#!/bin/bash
# Uninstall script for QQ
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling QQ..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping QQ if running..."
pkill -f "QQ" 2>/dev/null || true

# Kill application with bundle ID com.tencent.qq if running
echo "Stopping application with bundle ID com.tencent.qq if running..."
killall -9 "com.tencent.qq" 2>/dev/null || true

# Remove /Applications/QQ.app
echo "Removing /Applications/QQ.app..."
if [ -d "/Applications/QQ.app" ]; then
    rm -rf "/Applications/QQ.app" 2>/dev/null || true
elif [ -f "/Applications/QQ.app" ]; then
    rm -f "/Applications/QQ.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/com.tencent.qq
echo "Removing $HOME/Library/Application Scripts/com.tencent.qq..."
if [ -d "$HOME/Library/Application Scripts/com.tencent.qq" ]; then
    rm -rf "$HOME/Library/Application Scripts/com.tencent.qq" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/com.tencent.qq" ]; then
    rm -f "$HOME/Library/Application Scripts/com.tencent.qq" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/FN2V63AD2J.com.tencent.localserver2
echo "Removing $HOME/Library/Application Scripts/FN2V63AD2J.com.tencent.localserver2..."
if [ -d "$HOME/Library/Application Scripts/FN2V63AD2J.com.tencent.localserver2" ]; then
    rm -rf "$HOME/Library/Application Scripts/FN2V63AD2J.com.tencent.localserver2" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/FN2V63AD2J.com.tencent.localserver2" ]; then
    rm -f "$HOME/Library/Application Scripts/FN2V63AD2J.com.tencent.localserver2" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Scripts/FN2V63AD2J.com.tencent.ScreenCapture2
echo "Removing $HOME/Library/Application Scripts/FN2V63AD2J.com.tencent.ScreenCapture2..."
if [ -d "$HOME/Library/Application Scripts/FN2V63AD2J.com.tencent.ScreenCapture2" ]; then
    rm -rf "$HOME/Library/Application Scripts/FN2V63AD2J.com.tencent.ScreenCapture2" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Scripts/FN2V63AD2J.com.tencent.ScreenCapture2" ]; then
    rm -f "$HOME/Library/Application Scripts/FN2V63AD2J.com.tencent.ScreenCapture2" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.tencent.qq.sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.tencent.qq.sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.tencent.qq.sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.tencent.qq.sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.tencent.qq.sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.tencent.qq.sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.tencent.qq
echo "Removing $HOME/Library/Caches/com.tencent.qq..."
if [ -d "$HOME/Library/Caches/com.tencent.qq" ]; then
    rm -rf "$HOME/Library/Caches/com.tencent.qq" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.tencent.qq" ]; then
    rm -f "$HOME/Library/Caches/com.tencent.qq" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.tencent.qq
echo "Removing $HOME/Library/Containers/com.tencent.qq..."
if [ -d "$HOME/Library/Containers/com.tencent.qq" ]; then
    rm -rf "$HOME/Library/Containers/com.tencent.qq" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.tencent.qq" ]; then
    rm -f "$HOME/Library/Containers/com.tencent.qq" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.tencent.qq.share
echo "Removing $HOME/Library/Containers/com.tencent.qq.share..."
if [ -d "$HOME/Library/Containers/com.tencent.qq.share" ]; then
    rm -rf "$HOME/Library/Containers/com.tencent.qq.share" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.tencent.qq.share" ]; then
    rm -f "$HOME/Library/Containers/com.tencent.qq.share" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/FN2V63AD2J.com.tencent.localserver2
echo "Removing $HOME/Library/Containers/FN2V63AD2J.com.tencent.localserver2..."
if [ -d "$HOME/Library/Containers/FN2V63AD2J.com.tencent.localserver2" ]; then
    rm -rf "$HOME/Library/Containers/FN2V63AD2J.com.tencent.localserver2" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/FN2V63AD2J.com.tencent.localserver2" ]; then
    rm -f "$HOME/Library/Containers/FN2V63AD2J.com.tencent.localserver2" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/FN2V63AD2J.com.tencent.ScreenCapture2
echo "Removing $HOME/Library/Containers/FN2V63AD2J.com.tencent.ScreenCapture2..."
if [ -d "$HOME/Library/Containers/FN2V63AD2J.com.tencent.ScreenCapture2" ]; then
    rm -rf "$HOME/Library/Containers/FN2V63AD2J.com.tencent.ScreenCapture2" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/FN2V63AD2J.com.tencent.ScreenCapture2" ]; then
    rm -f "$HOME/Library/Containers/FN2V63AD2J.com.tencent.ScreenCapture2" 2>/dev/null || true
fi

# Remove $HOME/Library/Group Containers/FN2V63AD2J.com.tencent
echo "Removing $HOME/Library/Group Containers/FN2V63AD2J.com.tencent..."
if [ -d "$HOME/Library/Group Containers/FN2V63AD2J.com.tencent" ]; then
    rm -rf "$HOME/Library/Group Containers/FN2V63AD2J.com.tencent" 2>/dev/null || true
elif [ -f "$HOME/Library/Group Containers/FN2V63AD2J.com.tencent" ]; then
    rm -f "$HOME/Library/Group Containers/FN2V63AD2J.com.tencent" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.tencent.qq.plist
echo "Removing $HOME/Library/Preferences/com.tencent.qq.plist..."
if [ -d "$HOME/Library/Preferences/com.tencent.qq.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.tencent.qq.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.tencent.qq.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.tencent.qq.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.tencent.qq.savedState
echo "Removing $HOME/Library/Saved Application State/com.tencent.qq.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.tencent.qq.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.tencent.qq.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.tencent.qq.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.tencent.qq.savedState" 2>/dev/null || true
fi

# Remove $HOME/Library/WebKit/com.tencent.qq
echo "Removing $HOME/Library/WebKit/com.tencent.qq..."
if [ -d "$HOME/Library/WebKit/com.tencent.qq" ]; then
    rm -rf "$HOME/Library/WebKit/com.tencent.qq" 2>/dev/null || true
elif [ -f "$HOME/Library/WebKit/com.tencent.qq" ]; then
    rm -f "$HOME/Library/WebKit/com.tencent.qq" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
