#!/bin/bash
# Uninstall script for Amadine
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Amadine..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Amadine if running..."
pkill -f "Amadine" 2>/dev/null || true

# Remove /Applications/Amadine.app
echo "Removing /Applications/Amadine.app..."
if [ -d "/Applications/Amadine.app" ]; then
    rm -rf "/Applications/Amadine.app" 2>/dev/null || true
elif [ -f "/Applications/Amadine.app" ]; then
    rm -f "/Applications/Amadine.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Amadine
echo "Removing $HOME/Library/Application Support/Amadine..."
if [ -d "$HOME/Library/Application Support/Amadine" ]; then
    rm -rf "$HOME/Library/Application Support/Amadine" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Amadine" ]; then
    rm -f "$HOME/Library/Application Support/Amadine" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.belightsoft.Amadine
echo "Removing $HOME/Library/Caches/com.belightsoft.Amadine..."
if [ -d "$HOME/Library/Caches/com.belightsoft.Amadine" ]; then
    rm -rf "$HOME/Library/Caches/com.belightsoft.Amadine" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.belightsoft.Amadine" ]; then
    rm -f "$HOME/Library/Caches/com.belightsoft.Amadine" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.belightsoft.Amadine.plist
echo "Removing $HOME/Library/Preferences/com.belightsoft.Amadine.plist..."
if [ -d "$HOME/Library/Preferences/com.belightsoft.Amadine.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.belightsoft.Amadine.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.belightsoft.Amadine.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.belightsoft.Amadine.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.belightsoft.Amadine.savedState
echo "Removing $HOME/Library/Saved Application State/com.belightsoft.Amadine.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.belightsoft.Amadine.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.belightsoft.Amadine.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.belightsoft.Amadine.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.belightsoft.Amadine.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
