#!/bin/bash
# Uninstall script for Splice
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Splice..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Splice if running..."
pkill -f "Splice" 2>/dev/null || true

# Kill application with bundle ID com.splice.Splice if running
echo "Stopping application with bundle ID com.splice.Splice if running..."
killall -9 "com.splice.Splice" 2>/dev/null || true

# Remove /Applications/Splice.app
echo "Removing /Applications/Splice.app..."
if [ -d "/Applications/Splice.app" ]; then
    rm -rf "/Applications/Splice.app" 2>/dev/null || true
elif [ -f "/Applications/Splice.app" ]; then
    rm -f "/Applications/Splice.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/*Splice*
echo "Removing $HOME/Library/Application Support/*Splice*..."
if [ -d "$HOME/Library/Application Support/*Splice*" ]; then
    rm -rf "$HOME/Library/Application Support/*Splice*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/*Splice*" ]; then
    rm -f "$HOME/Library/Application Support/*Splice*" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.splice*
echo "Removing $HOME/Library/Caches/com.splice*..."
if [ -d "$HOME/Library/Caches/com.splice*" ]; then
    rm -rf "$HOME/Library/Caches/com.splice*" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.splice*" ]; then
    rm -f "$HOME/Library/Caches/com.splice*" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.splice*
echo "Removing $HOME/Library/Preferences/com.splice*..."
if [ -d "$HOME/Library/Preferences/com.splice*" ]; then
    rm -rf "$HOME/Library/Preferences/com.splice*" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.splice*" ]; then
    rm -f "$HOME/Library/Preferences/com.splice*" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
