#!/bin/bash
# Uninstall script for GitKraken
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling GitKraken..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping GitKraken if running..."
pkill -f "GitKraken" 2>/dev/null || true

# Kill application with bundle ID com.axosoft.gitkraken if running
echo "Stopping application with bundle ID com.axosoft.gitkraken if running..."
killall -9 "com.axosoft.gitkraken" 2>/dev/null || true

# Remove /Applications/GitKraken.app
echo "Removing /Applications/GitKraken.app..."
if [ -d "/Applications/GitKraken.app" ]; then
    rm -rf "/Applications/GitKraken.app" 2>/dev/null || true
elif [ -f "/Applications/GitKraken.app" ]; then
    rm -f "/Applications/GitKraken.app" 2>/dev/null || true
fi

# Remove $HOME/.gitkraken
echo "Removing $HOME/.gitkraken..."
if [ -d "$HOME/.gitkraken" ]; then
    rm -rf "$HOME/.gitkraken" 2>/dev/null || true
elif [ -f "$HOME/.gitkraken" ]; then
    rm -f "$HOME/.gitkraken" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.axosoft.gitkraken.ShipIt
echo "Removing $HOME/Library/Application Support/com.axosoft.gitkraken.ShipIt..."
if [ -d "$HOME/Library/Application Support/com.axosoft.gitkraken.ShipIt" ]; then
    rm -rf "$HOME/Library/Application Support/com.axosoft.gitkraken.ShipIt" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.axosoft.gitkraken.ShipIt" ]; then
    rm -f "$HOME/Library/Application Support/com.axosoft.gitkraken.ShipIt" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/GitKraken
echo "Removing $HOME/Library/Application Support/GitKraken..."
if [ -d "$HOME/Library/Application Support/GitKraken" ]; then
    rm -rf "$HOME/Library/Application Support/GitKraken" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/GitKraken" ]; then
    rm -f "$HOME/Library/Application Support/GitKraken" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.axosoft.gitkraken
echo "Removing $HOME/Library/Caches/com.axosoft.gitkraken..."
if [ -d "$HOME/Library/Caches/com.axosoft.gitkraken" ]; then
    rm -rf "$HOME/Library/Caches/com.axosoft.gitkraken" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.axosoft.gitkraken" ]; then
    rm -f "$HOME/Library/Caches/com.axosoft.gitkraken" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.axosoft.gitkraken.ShipIt
echo "Removing $HOME/Library/Caches/com.axosoft.gitkraken.ShipIt..."
if [ -d "$HOME/Library/Caches/com.axosoft.gitkraken.ShipIt" ]; then
    rm -rf "$HOME/Library/Caches/com.axosoft.gitkraken.ShipIt" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.axosoft.gitkraken.ShipIt" ]; then
    rm -f "$HOME/Library/Caches/com.axosoft.gitkraken.ShipIt" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/GitKraken
echo "Removing $HOME/Library/Caches/GitKraken..."
if [ -d "$HOME/Library/Caches/GitKraken" ]; then
    rm -rf "$HOME/Library/Caches/GitKraken" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/GitKraken" ]; then
    rm -f "$HOME/Library/Caches/GitKraken" 2>/dev/null || true
fi

# Remove $HOME/Library/Cookies/com.axosoft.gitkraken.binarycookies
echo "Removing $HOME/Library/Cookies/com.axosoft.gitkraken.binarycookies..."
if [ -d "$HOME/Library/Cookies/com.axosoft.gitkraken.binarycookies" ]; then
    rm -rf "$HOME/Library/Cookies/com.axosoft.gitkraken.binarycookies" 2>/dev/null || true
elif [ -f "$HOME/Library/Cookies/com.axosoft.gitkraken.binarycookies" ]; then
    rm -f "$HOME/Library/Cookies/com.axosoft.gitkraken.binarycookies" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.axosoft.gitkraken
echo "Removing $HOME/Library/HTTPStorages/com.axosoft.gitkraken..."
if [ -d "$HOME/Library/HTTPStorages/com.axosoft.gitkraken" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.axosoft.gitkraken" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.axosoft.gitkraken" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.axosoft.gitkraken" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.axosoft.gitkraken.helper.plist
echo "Removing $HOME/Library/Preferences/com.axosoft.gitkraken.helper.plist..."
if [ -d "$HOME/Library/Preferences/com.axosoft.gitkraken.helper.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.axosoft.gitkraken.helper.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.axosoft.gitkraken.helper.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.axosoft.gitkraken.helper.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.axosoft.gitkraken.plist
echo "Removing $HOME/Library/Preferences/com.axosoft.gitkraken.plist..."
if [ -d "$HOME/Library/Preferences/com.axosoft.gitkraken.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.axosoft.gitkraken.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.axosoft.gitkraken.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.axosoft.gitkraken.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.axosoft.gitkraken.savedState
echo "Removing $HOME/Library/Saved Application State/com.axosoft.gitkraken.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.axosoft.gitkraken.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.axosoft.gitkraken.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.axosoft.gitkraken.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.axosoft.gitkraken.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
