#!/bin/bash
# Uninstall script for Topaz Gigapixel AI
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Topaz Gigapixel AI..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Topaz Gigapixel AI if running..."
pkill -f "Topaz Gigapixel AI" 2>/dev/null || true

# Remove $HOME/Library/Preferences/com.topaz-labs-llc.Topaz Gigapixel AI.plist
echo "Removing $HOME/Library/Preferences/com.topaz-labs-llc.Topaz Gigapixel AI.plist..."
if [ -d "$HOME/Library/Preferences/com.topaz-labs-llc.Topaz Gigapixel AI.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.topaz-labs-llc.Topaz Gigapixel AI.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.topaz-labs-llc.Topaz Gigapixel AI.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.topaz-labs-llc.Topaz Gigapixel AI.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.topazlabs.Topaz Gigapixel AI.plist
echo "Removing $HOME/Library/Preferences/com.topazlabs.Topaz Gigapixel AI.plist..."
if [ -d "$HOME/Library/Preferences/com.topazlabs.Topaz Gigapixel AI.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.topazlabs.Topaz Gigapixel AI.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.topazlabs.Topaz Gigapixel AI.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.topazlabs.Topaz Gigapixel AI.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.topazlabs.TopazGigapixelAI.plist
echo "Removing $HOME/Library/Preferences/com.topazlabs.TopazGigapixelAI.plist..."
if [ -d "$HOME/Library/Preferences/com.topazlabs.TopazGigapixelAI.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.topazlabs.TopazGigapixelAI.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.topazlabs.TopazGigapixelAI.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.topazlabs.TopazGigapixelAI.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.topazlabs.TopazGigapixelAI.savedState
echo "Removing $HOME/Library/Saved Application State/com.topazlabs.TopazGigapixelAI.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.topazlabs.TopazGigapixelAI.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.topazlabs.TopazGigapixelAI.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.topazlabs.TopazGigapixelAI.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.topazlabs.TopazGigapixelAI.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
