#!/bin/bash
# Uninstall script for ProcessSpy
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling ProcessSpy..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping ProcessSpy if running..."
pkill -f "ProcessSpy" 2>/dev/null || true

# Remove /Applications/ProcessSpy.app
echo "Removing /Applications/ProcessSpy.app..."
if [ -d "/Applications/ProcessSpy.app" ]; then
    rm -rf "/Applications/ProcessSpy.app" 2>/dev/null || true
elif [ -f "/Applications/ProcessSpy.app" ]; then
    rm -f "/Applications/ProcessSpy.app" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.itone.ProcessSpy
echo "Removing $HOME/Library/HTTPStorages/com.itone.ProcessSpy..."
if [ -d "$HOME/Library/HTTPStorages/com.itone.ProcessSpy" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.itone.ProcessSpy" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.itone.ProcessSpy" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.itone.ProcessSpy" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.itone.ProcessSpy.plist
echo "Removing $HOME/Library/Preferences/com.itone.ProcessSpy.plist..."
if [ -d "$HOME/Library/Preferences/com.itone.ProcessSpy.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.itone.ProcessSpy.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.itone.ProcessSpy.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.itone.ProcessSpy.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.itone.ProcessSpy.savedState
echo "Removing $HOME/Library/Saved Application State/com.itone.ProcessSpy.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.itone.ProcessSpy.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.itone.ProcessSpy.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.itone.ProcessSpy.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.itone.ProcessSpy.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
