#!/bin/bash
# Uninstall script for CleanMyMac
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling CleanMyMac..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping CleanMyMac if running..."
pkill -f "CleanMyMac" 2>/dev/null || true

# Remove /Applications/CleanMyMac_5.app
echo "Removing /Applications/CleanMyMac_5.app..."
if [ -d "/Applications/CleanMyMac_5.app" ]; then
    rm -rf "/Applications/CleanMyMac_5.app" 2>/dev/null || true
elif [ -f "/Applications/CleanMyMac_5.app" ]; then
    rm -f "/Applications/CleanMyMac_5.app" 2>/dev/null || true
fi

# Remove /Applications/{'target': 'CleanMyMac.app'}
echo "Removing /Applications/{'target': 'CleanMyMac.app'}..."
if [ -d "/Applications/{'target': 'CleanMyMac.app'}" ]; then
    rm -rf "/Applications/{'target': 'CleanMyMac.app'}" 2>/dev/null || true
elif [ -f "/Applications/{'target': 'CleanMyMac.app'}" ]; then
    rm -f "/Applications/{'target': 'CleanMyMac.app'}" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
