#!/bin/bash
# Uninstall script for Proton Pass
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Proton Pass..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Proton Pass if running..."
pkill -f "Proton Pass" 2>/dev/null || true

# Remove /Applications/Proton Pass.app
echo "Removing /Applications/Proton Pass.app..."
if [ -d "/Applications/Proton Pass.app" ]; then
    rm -rf "/Applications/Proton Pass.app" 2>/dev/null || true
elif [ -f "/Applications/Proton Pass.app" ]; then
    rm -f "/Applications/Proton Pass.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/me.proton.pass.electron..sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/me.proton.pass.electron..sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/me.proton.pass.electron..sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/me.proton.pass.electron..sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/me.proton.pass.electron..sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/me.proton.pass.electron..sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Proton Pass
echo "Removing $HOME/Library/Application Support/Proton Pass..."
if [ -d "$HOME/Library/Application Support/Proton Pass" ]; then
    rm -rf "$HOME/Library/Application Support/Proton Pass" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Proton Pass" ]; then
    rm -f "$HOME/Library/Application Support/Proton Pass" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/me.proton.pass.electron
echo "Removing $HOME/Library/Caches/me.proton.pass.electron..."
if [ -d "$HOME/Library/Caches/me.proton.pass.electron" ]; then
    rm -rf "$HOME/Library/Caches/me.proton.pass.electron" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/me.proton.pass.electron" ]; then
    rm -f "$HOME/Library/Caches/me.proton.pass.electron" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/me.proton.pass.electron.ShipIt
echo "Removing $HOME/Library/Caches/me.proton.pass.electron.ShipIt..."
if [ -d "$HOME/Library/Caches/me.proton.pass.electron.ShipIt" ]; then
    rm -rf "$HOME/Library/Caches/me.proton.pass.electron.ShipIt" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/me.proton.pass.electron.ShipIt" ]; then
    rm -f "$HOME/Library/Caches/me.proton.pass.electron.ShipIt" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/me.proton.pass.electron
echo "Removing $HOME/Library/HTTPStorages/me.proton.pass.electron..."
if [ -d "$HOME/Library/HTTPStorages/me.proton.pass.electron" ]; then
    rm -rf "$HOME/Library/HTTPStorages/me.proton.pass.electron" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/me.proton.pass.electron" ]; then
    rm -f "$HOME/Library/HTTPStorages/me.proton.pass.electron" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/Proton Pass
echo "Removing $HOME/Library/Logs/Proton Pass..."
if [ -d "$HOME/Library/Logs/Proton Pass" ]; then
    rm -rf "$HOME/Library/Logs/Proton Pass" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/Proton Pass" ]; then
    rm -f "$HOME/Library/Logs/Proton Pass" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/me.proton.pass.electron.plist
echo "Removing $HOME/Library/Preferences/me.proton.pass.electron.plist..."
if [ -d "$HOME/Library/Preferences/me.proton.pass.electron.plist" ]; then
    rm -rf "$HOME/Library/Preferences/me.proton.pass.electron.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/me.proton.pass.electron.plist" ]; then
    rm -f "$HOME/Library/Preferences/me.proton.pass.electron.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/me.proton.pass.electron.savedState
echo "Removing $HOME/Library/Saved Application State/me.proton.pass.electron.savedState..."
if [ -d "$HOME/Library/Saved Application State/me.proton.pass.electron.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/me.proton.pass.electron.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/me.proton.pass.electron.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/me.proton.pass.electron.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
