#!/bin/bash
# Uninstall script for Hyper
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Hyper..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Hyper if running..."
pkill -f "Hyper" 2>/dev/null || true

# Remove /Applications/Hyper.app
echo "Removing /Applications/Hyper.app..."
if [ -d "/Applications/Hyper.app" ]; then
    rm -rf "/Applications/Hyper.app" 2>/dev/null || true
elif [ -f "/Applications/Hyper.app" ]; then
    rm -f "/Applications/Hyper.app" 2>/dev/null || true
fi

# Remove binary /Applications/Hyper.app/Hyper.app/Contents/Resources/bin/hyper
echo "Removing binary /Applications/Hyper.app/Hyper.app/Contents/Resources/bin/hyper..."
if [ -f "/Applications/Hyper.app/Hyper.app/Contents/Resources/bin/hyper" ]; then
    rm -f "/Applications/Hyper.app/Hyper.app/Contents/Resources/bin/hyper" 2>/dev/null || true
fi

# Remove $HOME/.hyper.js
echo "Removing $HOME/.hyper.js..."
if [ -d "$HOME/.hyper.js" ]; then
    rm -rf "$HOME/.hyper.js" 2>/dev/null || true
elif [ -f "$HOME/.hyper.js" ]; then
    rm -f "$HOME/.hyper.js" 2>/dev/null || true
fi

# Remove $HOME/.hyper_plugins
echo "Removing $HOME/.hyper_plugins..."
if [ -d "$HOME/.hyper_plugins" ]; then
    rm -rf "$HOME/.hyper_plugins" 2>/dev/null || true
elif [ -f "$HOME/.hyper_plugins" ]; then
    rm -f "$HOME/.hyper_plugins" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/co.zeit.hyper.sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/co.zeit.hyper.sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/co.zeit.hyper.sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/co.zeit.hyper.sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/co.zeit.hyper.sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/co.zeit.hyper.sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/Hyper
echo "Removing $HOME/Library/Application Support/Hyper..."
if [ -d "$HOME/Library/Application Support/Hyper" ]; then
    rm -rf "$HOME/Library/Application Support/Hyper" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/Hyper" ]; then
    rm -f "$HOME/Library/Application Support/Hyper" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/co.zeit.hyper
echo "Removing $HOME/Library/Caches/co.zeit.hyper..."
if [ -d "$HOME/Library/Caches/co.zeit.hyper" ]; then
    rm -rf "$HOME/Library/Caches/co.zeit.hyper" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/co.zeit.hyper" ]; then
    rm -f "$HOME/Library/Caches/co.zeit.hyper" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/co.zeit.hyper.ShipIt
echo "Removing $HOME/Library/Caches/co.zeit.hyper.ShipIt..."
if [ -d "$HOME/Library/Caches/co.zeit.hyper.ShipIt" ]; then
    rm -rf "$HOME/Library/Caches/co.zeit.hyper.ShipIt" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/co.zeit.hyper.ShipIt" ]; then
    rm -f "$HOME/Library/Caches/co.zeit.hyper.ShipIt" 2>/dev/null || true
fi

# Remove $HOME/Library/Cookies/co.zeit.hyper.binarycookies
echo "Removing $HOME/Library/Cookies/co.zeit.hyper.binarycookies..."
if [ -d "$HOME/Library/Cookies/co.zeit.hyper.binarycookies" ]; then
    rm -rf "$HOME/Library/Cookies/co.zeit.hyper.binarycookies" 2>/dev/null || true
elif [ -f "$HOME/Library/Cookies/co.zeit.hyper.binarycookies" ]; then
    rm -f "$HOME/Library/Cookies/co.zeit.hyper.binarycookies" 2>/dev/null || true
fi

# Remove $HOME/Library/Logs/Hyper
echo "Removing $HOME/Library/Logs/Hyper..."
if [ -d "$HOME/Library/Logs/Hyper" ]; then
    rm -rf "$HOME/Library/Logs/Hyper" 2>/dev/null || true
elif [ -f "$HOME/Library/Logs/Hyper" ]; then
    rm -f "$HOME/Library/Logs/Hyper" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/ByHost/co.zeit.hyper.ShipIt.*.plist
echo "Removing $HOME/Library/Preferences/ByHost/co.zeit.hyper.ShipIt.*.plist..."
if [ -d "$HOME/Library/Preferences/ByHost/co.zeit.hyper.ShipIt.*.plist" ]; then
    rm -rf "$HOME/Library/Preferences/ByHost/co.zeit.hyper.ShipIt.*.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/ByHost/co.zeit.hyper.ShipIt.*.plist" ]; then
    rm -f "$HOME/Library/Preferences/ByHost/co.zeit.hyper.ShipIt.*.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/co.zeit.hyper.helper.plist
echo "Removing $HOME/Library/Preferences/co.zeit.hyper.helper.plist..."
if [ -d "$HOME/Library/Preferences/co.zeit.hyper.helper.plist" ]; then
    rm -rf "$HOME/Library/Preferences/co.zeit.hyper.helper.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/co.zeit.hyper.helper.plist" ]; then
    rm -f "$HOME/Library/Preferences/co.zeit.hyper.helper.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/co.zeit.hyper.plist
echo "Removing $HOME/Library/Preferences/co.zeit.hyper.plist..."
if [ -d "$HOME/Library/Preferences/co.zeit.hyper.plist" ]; then
    rm -rf "$HOME/Library/Preferences/co.zeit.hyper.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/co.zeit.hyper.plist" ]; then
    rm -f "$HOME/Library/Preferences/co.zeit.hyper.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/co.zeit.hyper.savedState
echo "Removing $HOME/Library/Saved Application State/co.zeit.hyper.savedState..."
if [ -d "$HOME/Library/Saved Application State/co.zeit.hyper.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/co.zeit.hyper.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/co.zeit.hyper.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/co.zeit.hyper.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
