#!/bin/bash
# Uninstall script for BlurScreen
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling BlurScreen..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping BlurScreen if running..."
pkill -f "BlurScreen" 2>/dev/null || true

# Kill application with bundle ID com.sanskar.blurscreen if running
echo "Stopping application with bundle ID com.sanskar.blurscreen if running..."
killall -9 "com.sanskar.blurscreen" 2>/dev/null || true

# Remove $HOME/Library/Caches/com.sanskar.blurscreen
echo "Removing $HOME/Library/Caches/com.sanskar.blurscreen..."
if [ -d "$HOME/Library/Caches/com.sanskar.blurscreen" ]; then
    rm -rf "$HOME/Library/Caches/com.sanskar.blurscreen" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.sanskar.blurscreen" ]; then
    rm -f "$HOME/Library/Caches/com.sanskar.blurscreen" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.sanskar.blurscreen
echo "Removing $HOME/Library/HTTPStorages/com.sanskar.blurscreen..."
if [ -d "$HOME/Library/HTTPStorages/com.sanskar.blurscreen" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.sanskar.blurscreen" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.sanskar.blurscreen" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.sanskar.blurscreen" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.sanskar.blurscreen.plist
echo "Removing $HOME/Library/Preferences/com.sanskar.blurscreen.plist..."
if [ -d "$HOME/Library/Preferences/com.sanskar.blurscreen.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.sanskar.blurscreen.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.sanskar.blurscreen.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.sanskar.blurscreen.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
