#!/bin/bash
# Uninstall script for SQLPro for MySQL
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling SQLPro for MySQL..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping SQLPro for MySQL if running..."
pkill -f "SQLPro for MySQL" 2>/dev/null || true

# Remove /Applications/SQLPro for MySQL.app
echo "Removing /Applications/SQLPro for MySQL.app..."
if [ -d "/Applications/SQLPro for MySQL.app" ]; then
    rm -rf "/Applications/SQLPro for MySQL.app" 2>/dev/null || true
elif [ -f "/Applications/SQLPro for MySQL.app" ]; then
    rm -f "/Applications/SQLPro for MySQL.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.hankinsoft.osx.mysql.sfl*
echo "Removing $HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.hankinsoft.osx.mysql.sfl*..."
if [ -d "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.hankinsoft.osx.mysql.sfl*" ]; then
    rm -rf "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.hankinsoft.osx.mysql.sfl*" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.hankinsoft.osx.mysql.sfl*" ]; then
    rm -f "$HOME/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.hankinsoft.osx.mysql.sfl*" 2>/dev/null || true
fi

# Remove $HOME/Library/Containers/com.hankinsoft.osx.mysql
echo "Removing $HOME/Library/Containers/com.hankinsoft.osx.mysql..."
if [ -d "$HOME/Library/Containers/com.hankinsoft.osx.mysql" ]; then
    rm -rf "$HOME/Library/Containers/com.hankinsoft.osx.mysql" 2>/dev/null || true
elif [ -f "$HOME/Library/Containers/com.hankinsoft.osx.mysql" ]; then
    rm -f "$HOME/Library/Containers/com.hankinsoft.osx.mysql" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
