#!/bin/bash
# Uninstall script for PixelSnap
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling PixelSnap..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping PixelSnap if running..."
pkill -f "PixelSnap" 2>/dev/null || true

# Kill application with bundle ID pl.maketheweb.pixelsnap2 if running
echo "Stopping application with bundle ID pl.maketheweb.pixelsnap2 if running..."
killall -9 "pl.maketheweb.pixelsnap2" 2>/dev/null || true

# Remove /Applications/PixelSnap 2.app
echo "Removing /Applications/PixelSnap 2.app..."
if [ -d "/Applications/PixelSnap 2.app" ]; then
    rm -rf "/Applications/PixelSnap 2.app" 2>/dev/null || true
elif [ -f "/Applications/PixelSnap 2.app" ]; then
    rm -f "/Applications/PixelSnap 2.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/PixelSnap
echo "Removing $HOME/Library/Application Support/PixelSnap..."
if [ -d "$HOME/Library/Application Support/PixelSnap" ]; then
    rm -rf "$HOME/Library/Application Support/PixelSnap" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/PixelSnap" ]; then
    rm -f "$HOME/Library/Application Support/PixelSnap" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/pl.maketheweb.pixelsnap2
echo "Removing $HOME/Library/Caches/pl.maketheweb.pixelsnap2..."
if [ -d "$HOME/Library/Caches/pl.maketheweb.pixelsnap2" ]; then
    rm -rf "$HOME/Library/Caches/pl.maketheweb.pixelsnap2" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/pl.maketheweb.pixelsnap2" ]; then
    rm -f "$HOME/Library/Caches/pl.maketheweb.pixelsnap2" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/SentryCrash/PixelSnap 2
echo "Removing $HOME/Library/Caches/SentryCrash/PixelSnap 2..."
if [ -d "$HOME/Library/Caches/SentryCrash/PixelSnap 2" ]; then
    rm -rf "$HOME/Library/Caches/SentryCrash/PixelSnap 2" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/SentryCrash/PixelSnap 2" ]; then
    rm -f "$HOME/Library/Caches/SentryCrash/PixelSnap 2" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/pl.maketheweb.pixelsnap2.plist
echo "Removing $HOME/Library/Preferences/pl.maketheweb.pixelsnap2.plist..."
if [ -d "$HOME/Library/Preferences/pl.maketheweb.pixelsnap2.plist" ]; then
    rm -rf "$HOME/Library/Preferences/pl.maketheweb.pixelsnap2.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/pl.maketheweb.pixelsnap2.plist" ]; then
    rm -f "$HOME/Library/Preferences/pl.maketheweb.pixelsnap2.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
