#!/bin/bash
# Uninstall script for FreeMacSoft AppCleaner
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling FreeMacSoft AppCleaner..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping FreeMacSoft AppCleaner if running..."
pkill -f "FreeMacSoft AppCleaner" 2>/dev/null || true

# Remove /Applications/AppCleaner.app
echo "Removing /Applications/AppCleaner.app..."
if [ -d "/Applications/AppCleaner.app" ]; then
    rm -rf "/Applications/AppCleaner.app" 2>/dev/null || true
elif [ -f "/Applications/AppCleaner.app" ]; then
    rm -f "/Applications/AppCleaner.app" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
