#!/bin/bash
# Uninstall script for BetterDisplay
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling BetterDisplay..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping BetterDisplay if running..."
pkill -f "BetterDisplay" 2>/dev/null || true

# Kill application with bundle ID pro.betterdisplay.BetterDisplay if running
echo "Stopping application with bundle ID pro.betterdisplay.BetterDisplay if running..."
killall -9 "pro.betterdisplay.BetterDisplay" 2>/dev/null || true

# Remove /Applications/BetterDisplay.app
echo "Removing /Applications/BetterDisplay.app..."
if [ -d "/Applications/BetterDisplay.app" ]; then
    rm -rf "/Applications/BetterDisplay.app" 2>/dev/null || true
elif [ -f "/Applications/BetterDisplay.app" ]; then
    rm -f "/Applications/BetterDisplay.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/BetterDisplay
echo "Removing $HOME/Library/Application Support/BetterDisplay..."
if [ -d "$HOME/Library/Application Support/BetterDisplay" ]; then
    rm -rf "$HOME/Library/Application Support/BetterDisplay" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/BetterDisplay" ]; then
    rm -f "$HOME/Library/Application Support/BetterDisplay" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/BetterDummy
echo "Removing $HOME/Library/Application Support/BetterDummy..."
if [ -d "$HOME/Library/Application Support/BetterDummy" ]; then
    rm -rf "$HOME/Library/Application Support/BetterDummy" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/BetterDummy" ]; then
    rm -f "$HOME/Library/Application Support/BetterDummy" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/pro.betterdisplay.BetterDisplay
echo "Removing $HOME/Library/Caches/pro.betterdisplay.BetterDisplay..."
if [ -d "$HOME/Library/Caches/pro.betterdisplay.BetterDisplay" ]; then
    rm -rf "$HOME/Library/Caches/pro.betterdisplay.BetterDisplay" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/pro.betterdisplay.BetterDisplay" ]; then
    rm -f "$HOME/Library/Caches/pro.betterdisplay.BetterDisplay" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/SentryCrash/BetterDisplay
echo "Removing $HOME/Library/Caches/SentryCrash/BetterDisplay..."
if [ -d "$HOME/Library/Caches/SentryCrash/BetterDisplay" ]; then
    rm -rf "$HOME/Library/Caches/SentryCrash/BetterDisplay" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/SentryCrash/BetterDisplay" ]; then
    rm -f "$HOME/Library/Caches/SentryCrash/BetterDisplay" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/pro.betterdisplay.BetterDisplay
echo "Removing $HOME/Library/HTTPStorages/pro.betterdisplay.BetterDisplay..."
if [ -d "$HOME/Library/HTTPStorages/pro.betterdisplay.BetterDisplay" ]; then
    rm -rf "$HOME/Library/HTTPStorages/pro.betterdisplay.BetterDisplay" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/pro.betterdisplay.BetterDisplay" ]; then
    rm -f "$HOME/Library/HTTPStorages/pro.betterdisplay.BetterDisplay" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/pro.betterdisplay.BetterDisplay.binarycookies
echo "Removing $HOME/Library/HTTPStorages/pro.betterdisplay.BetterDisplay.binarycookies..."
if [ -d "$HOME/Library/HTTPStorages/pro.betterdisplay.BetterDisplay.binarycookies" ]; then
    rm -rf "$HOME/Library/HTTPStorages/pro.betterdisplay.BetterDisplay.binarycookies" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/pro.betterdisplay.BetterDisplay.binarycookies" ]; then
    rm -f "$HOME/Library/HTTPStorages/pro.betterdisplay.BetterDisplay.binarycookies" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/pro.betterdisplay.BetterDisplay.plist
echo "Removing $HOME/Library/Preferences/pro.betterdisplay.BetterDisplay.plist..."
if [ -d "$HOME/Library/Preferences/pro.betterdisplay.BetterDisplay.plist" ]; then
    rm -rf "$HOME/Library/Preferences/pro.betterdisplay.BetterDisplay.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/pro.betterdisplay.BetterDisplay.plist" ]; then
    rm -f "$HOME/Library/Preferences/pro.betterdisplay.BetterDisplay.plist" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
