#!/bin/bash
# Uninstall script for Principle
# Generated by IntuneBrew

# Exit on error
set -e

echo "Uninstalling Principle..."

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Kill application process if running
echo "Stopping Principle if running..."
pkill -f "Principle" 2>/dev/null || true

# Remove /Applications/Principle.app
echo "Removing /Applications/Principle.app..."
if [ -d "/Applications/Principle.app" ]; then
    rm -rf "/Applications/Principle.app" 2>/dev/null || true
elif [ -f "/Applications/Principle.app" ]; then
    rm -f "/Applications/Principle.app" 2>/dev/null || true
fi

# Remove $HOME/Library/Application Support/com.danielhooper.principle
echo "Removing $HOME/Library/Application Support/com.danielhooper.principle..."
if [ -d "$HOME/Library/Application Support/com.danielhooper.principle" ]; then
    rm -rf "$HOME/Library/Application Support/com.danielhooper.principle" 2>/dev/null || true
elif [ -f "$HOME/Library/Application Support/com.danielhooper.principle" ]; then
    rm -f "$HOME/Library/Application Support/com.danielhooper.principle" 2>/dev/null || true
fi

# Remove $HOME/Library/Caches/com.danielhooper.principle
echo "Removing $HOME/Library/Caches/com.danielhooper.principle..."
if [ -d "$HOME/Library/Caches/com.danielhooper.principle" ]; then
    rm -rf "$HOME/Library/Caches/com.danielhooper.principle" 2>/dev/null || true
elif [ -f "$HOME/Library/Caches/com.danielhooper.principle" ]; then
    rm -f "$HOME/Library/Caches/com.danielhooper.principle" 2>/dev/null || true
fi

# Remove $HOME/Library/HTTPStorages/com.danielhooper.principle
echo "Removing $HOME/Library/HTTPStorages/com.danielhooper.principle..."
if [ -d "$HOME/Library/HTTPStorages/com.danielhooper.principle" ]; then
    rm -rf "$HOME/Library/HTTPStorages/com.danielhooper.principle" 2>/dev/null || true
elif [ -f "$HOME/Library/HTTPStorages/com.danielhooper.principle" ]; then
    rm -f "$HOME/Library/HTTPStorages/com.danielhooper.principle" 2>/dev/null || true
fi

# Remove $HOME/Library/Preferences/com.danielhooper.principle.plist
echo "Removing $HOME/Library/Preferences/com.danielhooper.principle.plist..."
if [ -d "$HOME/Library/Preferences/com.danielhooper.principle.plist" ]; then
    rm -rf "$HOME/Library/Preferences/com.danielhooper.principle.plist" 2>/dev/null || true
elif [ -f "$HOME/Library/Preferences/com.danielhooper.principle.plist" ]; then
    rm -f "$HOME/Library/Preferences/com.danielhooper.principle.plist" 2>/dev/null || true
fi

# Remove $HOME/Library/Saved Application State/com.danielhooper.principle.savedState
echo "Removing $HOME/Library/Saved Application State/com.danielhooper.principle.savedState..."
if [ -d "$HOME/Library/Saved Application State/com.danielhooper.principle.savedState" ]; then
    rm -rf "$HOME/Library/Saved Application State/com.danielhooper.principle.savedState" 2>/dev/null || true
elif [ -f "$HOME/Library/Saved Application State/com.danielhooper.principle.savedState" ]; then
    rm -f "$HOME/Library/Saved Application State/com.danielhooper.principle.savedState" 2>/dev/null || true
fi

echo "Uninstallation complete!"
exit 0
